### PR TITLE
adding float support for sserial.

### PR DESCRIPTION
**Pull request by saeugetier**
Pull request regarding issue https://github.com/machinekit/machinekit/issues/1250

### CODE REVIEW

**Comment by saeugetier** [comment]
The changes has been checked on a DE0Nano connected to STMBL motor driver via sserial.

**Comment by ArcEye** [comment]
Thanks for the PR and testing.  Hopefully it will cure your problems.

I don't quite understand the code at 1524, since a hal_float_t is actually is really a double.  There must have been an expectation of data coming from a source that was a true float, as well as hal_float_t pins etc.  But that is Andy's code not yours 😄

**Comment by saeugetier** [comment]
I will take a closer look on this. Thank you for the review.

**Comment by ArcEye** [comment]
I wouldn't worry too much. I didn't look through the whole file, that snippet just struck me as odd.

Like most of the hm2 code, it comes under the category of 'if it works, leave well alone' 😄

**Pull request merged**
