### PR TITLE
Fix incorrect left\rigth jogging

### PR DESCRIPTION
**Pull request by marksue**
Fix for issue #699.

### CODE REVIEW

**Comment by strahlex** [comment]
https://github.com/machinekit/machinekit/issues/700

**Comment by strahlex** [comment]
Can you please fix these type of problems too: https://github.com/machinekit/machinekit/issues/663

**Comment by mhaberler** [comment]
is there anything forthcoming or should we close this?

**Comment by marksue** [comment]
Sorry for the hesitation but Machinekit is quite new for me and regarding #663 I want to make my own picture. The situation is as followed:
1.	With the proposed pull requests, the XHC-HB04 MPG is working but not safe (see 4).
2.	The code still contains data types like int, char …  and so on. That is in fact a little bit unclean.
3.	The suggestion in #663 is (if I understand right) to use HAL types at all, but this is a little bit unclear for me (as I wrote in #663). Using the current defined HAL types would (IMO) not really improve the situation, instead the code would be polluted with volatiles. Moreover 8 bit HAL data types are missing in HAL but needed here.  Using __u8, __s8, __u16 ... instead of HAL types would (IMO) more useful, but I feel not desired. What is your suggestion here?
4.	I realized that data accesses with hal_float_t data types are not atomic. This is critical, because the xhc-hb04 is a use space component that can be interrupted by real time components of course.  Are there functions or macros which can be used to encapsulate HAL accesses?

**Comment by marksue** [comment]
closed was incorrect, sorry.

**Comment by mhaberler** [comment]
where exactly does atomicity come in?

**Pull request merged**
