### PR TITLE
Travis CI:  Jessie builds + minor updates

### PR DESCRIPTION
**Pull request by zultron**
This PR introduces Travis CI builds for Jessie.  This completes the final flow for updating the deb.dovetail-automata.com package repo; see #791.

I have updated the Travis CI `machinekit/machinekit` settings to point to an updated set of Docker containers built from [my modifications][1] to @kinsamanka's repo; the most notable change is addition of Jessie containers.  [Docker Registry link][2]

The other changes in this commit are minor:
- Only push to packagecloud.io when building from the `master` branch (safety measure)
- Always run regression tests in the `run_tests` matrix (duh on my part)

[1]: https://github.com/zultron/mkdocker
[2]: https://hub.docker.com/r/zultron/mkdocker/builds/

### CODE REVIEW

**Comment by zultron** [comment]
Well what a let-down, over 30 minutes and Travis CI is still ignoring my most exciting PR in months.  ;(

**Comment by bobvanderlinden** [comment]
Maybe limiting the number of concurrent builds would help?
https://travis-ci.org/machinekit/machinekit/settings

Otherwise we should consider only doing the tests for PRs?

**Comment by zultron** [comment]
@bobvanderlinden Thanks!  Looks like Travis has a backlog.  I'll just be patient, and the jobs are trickling through anyway.  :)

https://www.traviscistatus.com/

**Comment by zultron** [comment]
Oh yeah!  The first Maintainer to click the 'Merge' button gets his name on the first Machinekit packages to come out of these package streams!

**Comment by bobvanderlinden** [comment]
Ooh, hehe good timing on Travis ;) When I looked it was already past 2 hours.

It looks good to me. I was a bit hesitant about doing that many `build_deb` for PRs, but then again testing for packaging problems is useful as well.

**Comment by zultron** [comment]
And @bobvanderlinden is the lucky winner!

Thanks.  I don't see a way to prune the `.travis.yml` build matrix for PRs but not merges.  Anyway, we can take that topic over to #791.

**Pull request merged**
