### PR TITLE
Fix for Protobuf upstream mismatches

### PR DESCRIPTION
**Pull request by machinekoder**
Potential fix for https://github.com/machinekit/machinekit/issues/1131

### CODE REVIEW

**Comment by machinekoder** [comment]
This PR needs some testing, since I currently get Cython compile errors on my machine.

**Comment by ArcEye** [comment]
Tried to run your patch on a copy of master, but it throws all sorts of errors
Looks like it was based upon the master before the https://github.com/machinekit/machinekit/commit/1e1df875f9fb6ae53f19d39efd1ae47caf07f0e3 merge

Can only suggest you do a fresh pull, test a build and then apply your patch to that and re-submit.
Hopefully the cython errors will disappear and what the clashes in the patch are will be apparent to you.

**Comment by machinekoder** [comment]
I just updated the branch. Unfortunately I still get Cython errors.

**Comment by ArcEye** [comment]
Again I can't apply this as a patch, gets stuck in a circular path of patching a previously patched file.
Something peculiar about how github produces the patch I think, as it merges fine.

I think the cython errors issue must be down to your own local setup.

I can build fine on Jessie with gcc-4.9.2 and cython 0.21 and have just built the merged repo.
Travis builds fine too for Wheezy and Jessie.

All I can suggest is building a fresh separate clone of master.
If that errors, it is your build env.  If it doesn't, there is something different in your main repo causing it.

**Pull request merged**
