### PR TITLE
Remap for M19

### PR DESCRIPTION
**Pull request by pmcstone**

### CODE REVIEW

**Comment by luminize** [comment]
@zultron @pmcstone are there sections in the docs that need to be updated?

**Comment by mhaberler** [comment]
fine, and is there actually a test case which shows that this works? setting the remappable attribute usually is just a small part of the job

**Comment by zultron** [comment]
@luminize, I'll get the documentation when I fix up #957.

**Comment by luminize** [comment]
@zultron ok, thx!

**Pull request merged**
