### PR TITLE
DO NOT MERGE: lib/machinekit/hal: return bool for HAL_BIT

### PR DESCRIPTION
**Pull request by machinekoder**
fix for https://github.com/machinekit/machinekit/issues/996
needs to be decided if compatibility to old hal module should be kept

### CODE REVIEW

**Comment by luminize** [comment]
@machinekoder is this still active?

**Comment by machinekoder** [comment]
We still need to decide on #996

**Comment by ArcEye** [comment]
IMHO any change should _allow_ the use of bool, but not _enforce_ it.
Otherwise it risks breaking all sorts of programs and configs we have no knowledge of.

Personally, so long as **hal_bit_t** is **int**, I don't see why a python implementation would need to be anything different, on anything other than aesthetic grounds.

**Comment by machinekoder** [comment]
I can live with checking identity with `1` and `0` so I thin we can close this.

**Pull request closed without merging**
