### PR TITLE
bb_gpio and hpg: changing HAL params to pins

### PR DESCRIPTION
**Pull request by strahlex**
fixup for https://github.com/machinekit/machinekit/issues/610

### CODE REVIEW

**Comment by strahlex** [comment]
Buildbot seems fine. Can someone please take a look at the code and try the changes

**Comment by mhaberler** [comment]
@cdsteinkuehler - I think it would help if you looked over this - you're the most familiar with this comps?

**Comment by cdsteinkuehler** [comment]
On 5/15/2015 3:25 AM, Michael Haberler wrote:
> @cdsteinkuehler - I think it would help if you looked over this - you're the most familiar with this comps?

The code changes look OK, I'm just wondering why the need to switch to
pins instead of parameters and newf instead of new.  In the case of the
hal_pru_generic code, I was modeling the hm2 driver to make both
switching from PRU to real hardware and pulling new features from the
hm2 code easier.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by strahlex** [comment]
@cdsteinkuehler  See issue https://github.com/machinekit/machinekit/issues/610. There is no reason to use params anymore. Params are not implemented in the Python API and probably will never be. For `newf` there is no specific reason except that it makes the name variable obsolete.

If hm2 uses params then it should be changed there as well.

**Comment by strahlex** [comment]
@cdsteinkuehler I experimented with changing the stepgen settings at runtime. This could e.g. be useful to switch between velocity extrusion and joint-based extrusion at runtime. The only problem I experienced was that the position-fb retained the old value and therefore when switchting from velocity to position mode the stepgen started to generate steps. Does it make sense to change the settings at runtime? If so the subcounts variable needs to be reset when switchting between velocity and position mode.

**Pull request merged**
