### PR TITLE
Convert all `python` commands, to `python2`

### PR DESCRIPTION
**Pull request by ArcEye**
In Debian the symlink `/usr/bin/python` points to `/usr/bin/python2.7`
In other distros such a Gentoo, it points to `/usr/bin/python3.6`,
which is the default python version.

By specifying the python version as 2, machinekit will build and operate
on other distros, without the default python version having to be reset globally.
Since Debian has symlink for `/usr/bin/python2`, which also points to
`/usr/bin/python2.7`, the change has no effect there.

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
@l29ah your PR #1331 was a valid idea, albeit incomplete.

This should ensure you can build AND run machinekit on Gentoo.

**Comment by ArcEye** [comment]
The failure is one of the runtests
```
Running test: tests/threads.0
line 2864: got 0, expected 2 or 1
*** tests/threads.0: FAIL: checkresult exited with 1
```
Not immediately clear what the error was caused by, I'll run it locally and check

**Comment by ArcEye** [comment]
Think the failure was just a glitch.
I made a change to prompt a new test, but what I changed could not be the cause, as its unchanged form is used in 8 other runtests that worked fine.

**Comment by ArcEye** [comment]
bump,bump

**Comment by machinekoder** [comment]
Seeing this, I think it would also make sense to make to streamline the shebang calls to look alike:

```bash
#!/usr/bin/env python2
```

Else some script may end up running with a different python interpreter than others.

**Comment by ArcEye** [comment]
I have wondered about that too.
It would seem to make sense do change the ones using `/usr/bin/env` to use the direct symlink of `python2`.
We don't know where env will lead on other distros.

**Comment by l29ah** [comment]
src/machinetalk/scripts/extract-mottypes is still calling `python`

**Comment by ArcEye** [comment]
Thanks, also extract-nmltypes in the same dir.
Somehow missed in the mass sed substitution the first time around.
I'll have another search through and fix later.

**Pull request merged**
