### PR TITLE
Fix: BBB pru_pwm forgot to update the output when enable <= 0 leaving output on

### PR DESCRIPTION
**Pull request by the-snowwhite**
setp hpg.pwmgen.0x.out.0x.enable    0
Now turns pwm output off

Tested on BBB + CRAMPS2 board

### CODE REVIEW

**Comment by mhaberler** [comment]
PR's are about solving problems. Which problem does this solve?

Also, this is a mess:   5,871 additions and 1,569 deletions. in a single commit?

please make this a _minimal_ change.

**Comment by strahlex** [comment]
@the-snowwhite Please cherry-pick the commit that fixes the problem into a new branch, rename or delete this branch, rename the new branch to the old name and force push the branch to GitHub to fix-up the PR.

**Comment by mhaberler** [comment]
please do this yourself, and file a clean PR.

**Comment by the-snowwhite** [comment]
Hmm sorry for the mess I tried to clean up and sync  my old machinekit fork
I think it will be easier to delete the old fork and make a new...

**Comment by the-snowwhite** [comment]
https://github.com/machinekit/machinekit/pull/721

**Pull request closed without merging**
