### PR TITLE
Work

### PR DESCRIPTION
**Pull request by the-snowwhite**
I cleaned up the socfpga hostmot2 memory utility:

  mksocmemio

and this is an attempt to move it in from the mksocfpga repo so that it (only) gets compiled in MK in the socfpga flavor.

Also a fix for the joint.x error and a new (no bitfile load) config demonstrating how to use the:

      already_programmed=1

Setting (this took me a while to figure out)

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by the-snowwhite** [comment]
The changes to the submake file need an extra look:
https://github.com/machinekit/machinekit/pull/1369/files#diff-b95f3ce6cb4f8632848c66ea2be6b1f5R33



https://github.com/machinekit/machinekit/pull/1369/files#diff-b95f3ce6cb4f8632848c66ea2be6b1f5R33

**Comment by luminize** [comment]
Add to whitelist

**Comment by ArcEye** [comment]
>  The changes to the submake file need an extra look:
https://github.com/machinekit/machinekit/pull/1369/files#diff-b95f3ce6cb4f8632848c66ea2be6b1f5R33

Looks OK, the binary is built and included into an armhf package automatically

**Pull request merged**
