### PR TITLE
Remove localization file for non-existing 'rs' country code.

### PR DESCRIPTION
**Pull request by dwrobel**

### CODE REVIEW

**Comment by dwrobel** [comment]
rpmlint tool complained for the 'rs' subdirectory and I couldn't find country for 'rs' so either it should be removed or renamed to something different. Interestingly, copy-pasting some of translated texts to google translator detected Croatian language.

**Comment by ArcEye** [comment]
AFAIK `rs` is the country code for `Republic of Serbia`, hence Croatian language

Don't know why you are running rpmlint, but this does not seem to be an error.

**Comment by dwrobel** [comment]
> AFAIK rs is the country code for Republic of Serbia, hence Croatian language

It's only wikipedia (so, not normative reference) https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, but according to it Serbia has 'sr' country code and there is not 'rs' one.

> Don't know why you are running rpmlint, but this does not seem to be an error.

I'm considering to prepare an RPM package for Fedora, but it has to meet certain criterias.

**Comment by ArcEye** [comment]
> It's only wikipedia (so, not normative reference) https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, but according to it Serbia has 'sr' country code and there is no 'rs' one.

That seems pretty selective searching, enter 'country code RS' and you will get lots of hits, including this.
https://en.wikipedia.org/wiki/ISO_3166-2:RS

If you want to produce packages for Fedora and the use of up to date iso codes offends some criterea of theirs, then leave it out of your package.
I don't think we are going to delete perfectly valid files from our repo to assist building packages for a distro we do not officially support.  Keeping things running with Debian is difficult enough.

**Pull request closed without merging**
