### PR TITLE
Machinetalk hardening

### PR DESCRIPTION
**Pull request by strahlex**
Fix for https://github.com/machinekit/machinekit/issues/859
and https://github.com/machinekit/machinekit/issues/860

Please test.

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
How can I test this properly? Specifically the broker support.

**Comment by strahlex** [comment]
Should be pretty easy with node. Create a chain of dealer-routers, send a supported message and 
wait for the answer. e.g.
```
halrcmd < DEALER (connect) <ROUTER (bind) < DEALER (connect) < send msg
tcp:xyz      tcp:xyz                      ipc:test                  ipc:test
```
I also will upload my broker repo.

**Comment by abc838** [comment]
连接

**Comment by luminize** [comment]
> On 07 Feb 2016, at 13:02, abc838 <notifications@github.com> wrote:
> 
> 连接
> 

@abc838
Please use english as language in communication.

**Comment by mhaberler** [comment]
this has been sitting here for a while - is this PR still current and good to merge?

**Comment by strahlex** [comment]
Someone should test it:
-  send broken messages to mkwrapper and Haltalk (e.g. just some random string)
- send multi-frame messages to mkwrapper and Haltalk

**Comment by strahlex** [comment]
Added tests to pymachinetalk: https://github.com/strahlex/pymachinetalk/tree/machinetalk-testing

One thing needs to be considered: How should a Machinetalk socket behave when broken messages are received? Either we return a error message or we just ignore it. Currently halrcmd just ignores messages. However, when implementing a new binding it can be confusing to receive nothing in case encoding failed.

**Comment by mhaberler** [comment]
@strahlex I think raising an Exception would be the right thing - that leaves handling to using code

**Pull request merged**
