### PR TITLE
Changed hal_pru_generic.c to get rid of unnecessary error messages

### PR DESCRIPTION
**Pull request by muggins**
Changed calls to rtapi_print to call rtapi_print_msg with a lower priority RTAPI_MSG_DBG.
This should allow the information to be available for debugging without showing up everytime you start the program.
https://github.com/machinekit/machinekit/commit/4501b588298a5efe34ad4ff9d52bac1920ebf14
https://github.com/machinekit/machinekit/commit/ff7247100bb0d7fd273e1b0c8b2cad41887cf2e74

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by cdsteinkuehler** [comment]
The hal_pru_generic changes seem fine, but there are a lot of other config changes included in this.  They mostly seem OK, but I don't have time to review them all right now.  Separating the changes into a few different PRs to separate the config updates & the driver changes seems prudent.

**Comment by ArcEye** [comment]
You need to remove hal_pru_generic.c from this PR and change the text to relate to the config changes in the rest of the files.

This PR appears to be in your master branch, which will make things more difficult.

I would suggest that from your master you create a new branch, which will have the same commit in it.
Then do a soft reset, just add back the files you need and make a new commit and new PR from it.
Then you can do a hard reset on your master branch to remove the old PR and update it as normal.
eg
```
git checkout -b config-changes
git checkout config-changes
git reset --soft HEAD~
git add <all the config files but not hal_pru_generic.c>
git commit -s

git checkout master
git reset --hard HEAD~
```
Just be sure that all the files you need are in the new branch and don't update or pull to master
until the HEAD is reset back to the previous commit.

**Comment by ArcEye** [comment]
Dealt with in #1465

**Pull request closed without merging**
