### PR TITLE
Build setsserial utility for Mesa boards

### PR DESCRIPTION
**Pull request by ArcEye**
Modify Makefile to build setsserial module
linking with required objects

Update header #includes in setsserial.c

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by mhaberler** [comment]
buildbot failed to pass

**Comment by ArcEye** [comment]
OK, I'll look at the buildbot logs, it builds and works so there must be some strange interaction somewhere.

**Comment by mhaberler** [comment]
not sure it builds: http://buildbot.dovetail-automata.com/builders/d7-64-bld/builds/941/steps/chroot-make/logs/stdio

````
In file included from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/kernel.h:15:0,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/asm-generic/bug.h:13,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/bug.h:38,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bug.h:4,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/thread_info.h:11,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/preempt.h:9,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/mmzone.h:7,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/gfp.h:4,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:52,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-amd64/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/dynamic_debug.h: In function 'ddebug_dyndbg_module_param_cb':
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/dynamic_debug.h:111:2: error: implicit declaration of function 'strstr' [-Werror=implicit-function-declaration]
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/dynamic_debug.h:111:6: warning: incompatible implicit declaration of built-in function 'strstr' [enabled by default]
In file included from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/cpumask.h:11:0,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/cpumask.h:4,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/msr.h:10,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/processor.h:20,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/thread_info.h:22,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/thread_info.h:54,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/preempt.h:9,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/mmzone.h:7,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/gfp.h:4,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:52,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-amd64/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h: In function 'bitmap_zero':
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h:165:3: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h:165:3: warning: incompatible implicit declaration of built-in function 'memset' [enabled by default]
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h: In function 'bitmap_fill':
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h:174:3: warning: incompatible implicit declaration of built-in function 'memset' [enabled by default]
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h: In function 'bitmap_copy':
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h:186:3: error: implicit declaration of function 'memcpy' [-Werror=implicit-function-declaration]
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bitmap.h:186:3: warning: incompatible implicit declaration of built-in function 'memcpy' [enabled by default]
In file included from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/realmode.h:5:0,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/acpi.h:32,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/fixmap.h:19,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/apic.h:12,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/smp.h:13,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/mmzone_64.h:10,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/mmzone.h:4,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/mmzone.h:909,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/gfp.h:4,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:52,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-amd64/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h: In function 'memset_io':
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h:205:2: warning: incompatible implicit declaration of built-in function 'memset' [enabled by default]
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h: In function 'memcpy_fromio':
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h:211:2: warning: incompatible implicit declaration of built-in function 'memcpy' [enabled by default]
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h: In function 'memcpy_toio':
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/io.h:217:2: warning: incompatible implicit declaration of built-in function 'memcpy' [enabled by default]
In file included from /usr/include/wordexp.h:22:0,
                 from /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-amd64/rtapi/userpci/string.c:50:
/usr/include/features.h:323:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.
````

and http://buildbot.dovetail-automata.com/builders/d8-32-bld/builds/63/steps/chroot-make/logs/stdio :+1: 

looks like ULAPI/RTAPI confusion or DSO vs KBUILD?

````
In file included from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/kernel.h:15:0,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/asm-generic/bug.h:13,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/bug.h:38,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/bug.h:4,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/thread_info.h:11,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/preempt.h:9,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/mmzone.h:7,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/gfp.h:4,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:52,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/dynamic_debug.h: In function 'ddebug_dyndbg_module_param_cb':
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/dynamic_debug.h:111:2: error: implicit declaration of function 'strstr' [-Werror=implicit-function-declaration]
  if (strstr(param, "dyndbg")) {
  ^
In file included from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/page.h:13:0,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/thread_info.h:11,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/thread_info.h:54,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/preempt.h:9,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/spinlock.h:50,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/mmzone.h:7,
                 from /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/gfp.h:4,

                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:52,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/page_32.h: In function 'clear_page':
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/page_32.h:41:2: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
  memset(page, 0, PAGE_SIZE);
  ^
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/page_32.h: In function 'copy_page':
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/page_32.h:46:2: error: implicit declaration of function 'memcpy' [-Werror=implicit-function-declaration]
  memcpy(to, from, PAGE_SIZE);
  ^
In file included from /usr/include/wordexp.h:21:0,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/rtapi/userpci/string.c:50:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
In file included from /usr/include/string.h:25:0,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/rtapi/userpci/string.h:53,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/drivers/mesa-hostmot2/setsserial.c:21:
/usr/include/features.h: At top level:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
cc1: some warnings being treated as errors
compilation terminated.
make[5]: *** [/var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/rtapi/userpci/string.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /usr/include/stdlib.h:24:0,
                 from /var/lib/buildslave/d8-32-bldtest/build/source/machinekit/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/rtapi/userpci/firmware.c:51:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
````

**Comment by ArcEye** [comment]
I see this is just the Wheezy rtai 3.8.1 package kernel with package headers, I built on a Jessie 4.04-rt-preeempt kernel with full kernel sources, just done it again and builds fine

Some of the errors are bizarre
`/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>`

That include has been in `/usr/include/x86{_64}_linux_gnu/sys` since round about the 2.8 kernels

Most of the errors seem to relate to string.h  (memset, memcpy, strstr etc), yet userpci/string.h which
is included with setsserial.c pulls that and stdlib.h in anyway.

I will pull it for now, don't have time to chase strange errors, it was just to get Dave going reflashing his Mesa board anyway, no sign that anyone else even uses Mesa (apart from us two and Dave)

**Comment by unseenlaser** [comment]
got to be with the way it's trying to use rtai or in the autoconfiguration tasks

**Pull request closed without merging**
