### PR TITLE
add hostmot2 driver for the new socfpga port('s), and an example config

### PR DESCRIPTION
**Pull request by the-snowwhite**
Signed-off-by: the-snowwhite <producer@holotronic.dk>

### CODE REVIEW

**Comment by the-snowwhite** [comment]
@cdsteinkuehler 
OK I lost the old thread since I had to reset my fork to be able to do a new PR.

**Comment by cdsteinkuehler** [comment]
That change-set looks much cleaner, thanks!
And the build passed, so it looks good to go!!!

**Comment by the-snowwhite** [comment]
OK great  :-)
ill just grab some food and try the package install  after wards

**Comment by the-snowwhite** [comment]
I'm not so sure about this:

https://travis-ci.org/machinekit/machinekit/jobs/115410749

    machinekit@mksocfpga:~$ sudo apt install machinekit-rt-preempt
    
    The following packages have unmet dependencies:
     machinekit-rt-preempt : Depends: machinekit (= 0.1.1457560470-1mk.travis.master.git1200f355~1jessie) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

---

Ok no problem just temporary installing ok now

**Comment by the-snowwhite** [comment]
Yes Thanks it's working

Now wonder if / when there is / will be something usable for the socfpga's here:   :-)

http://ftp.nl.debian.org/debian/dists/testing/main/installer-armhf/current/images/

https://www.debian.org/devel/debian-installer/

**Pull request merged**
