### PR TITLE
do not presume python == python2

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by luminize** [comment]
Add to whitelist

**Comment by Shaeto** [comment]
btw python protobuf and protoc plugin are available for python 3 also, imho it is better to choose python version in configure.ac or use system wide/user settings than fix it in make rules

**Comment by ArcEye** [comment]
You have pushed this PR from linuxcnc, which means you cannot have tested it, which should disqualify it immediately.

You have not submitted this PR to linuxcnc either, just one commit with your moniker on it
https://github.com/LinuxCNC/linuxcnc/commit/53191113309498d26d41667e5f69765e087bd69b

Stretch still has a symlink /usr/bin/python which points to python-2.7 as in fact does Buster.

Since neither machinekit or Linuxcnc use python3, I don't know if this is python pedantry or if there is something to follow that requires this

**Comment by ArcEye** [comment]
Looking at your other repos, I imagine this stems from your wanting to make it easier to build on Gentoo.
Gentoo, unlike Debian, appears to default to python 3.6 (or whatever version they are on).
The format you have used is as recommended in the Gentoo python wiki, to get around this.

If that is what is going on, please say.

We can't really be expected to guess why someone who has not even forked machinekit, 
so presumably does not use it, wants us to change something in it, that works perfectly well with the distros we support.

**Comment by l29ah** [comment]
On Wed, Dec 13, 2017 at 09:53:28AM +0000, ArcEye wrote:
> You have pushed this PR from linuxcnc, which means you cannot have tested it, which should disqualify it immediately.

I did not.

> You have not submitted this PR to linuxcnc either, just one commit with your moniker on it
> https://github.com/LinuxCNC/linuxcnc/commit/53191113309498d26d41667e5f69765e087bd69b

How is this related to the pull request?

> Stretch still has a symlink /usr/bin/python which points to python-2.7 as in fact does Buster.
> Since neither machinekit or Linuxcnc use python3, I don't know if this is python pedantry or if there is something to follow that requires this

Different distros have different stance on this. I'm using Gentoo, where python is usually python3.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
On Wed, Dec 13, 2017 at 08:51:27AM +0000, Evgeny Sabelskiy wrote:
> btw python protobuf and protoc plugin are available for python 3 also, imho it is better to choose python version in configure.ac or use system wide/user settings than fix it in make rules

The scripts that use protobuf and protoc plugins shipped in machinekit fail to run in python3, hence my pull request.
I haven't touched python incantations in the make rules.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ArcEye** [comment]
>> You have not submitted this PR to linuxcnc either, just one commit with your moniker on it LinuxCNC@5319111

> How is this related to the pull request?

You have only forked Linuxcnc and have not submitted this patch to them, made me wonder why we had been honoured.

The bottom line on this is that we don't pretend to support Gentoo, or any other distro that defaults to a later version of python, which will not work with Machinekit as currently set up.

At some point; if python ever gets its act together and ports all the v2 libs to v3, or makes v3 backwardly compatible, or we convert our own programs to use v3, we might need to do this.

If you want to change Machinekit, so that it can be built and used on a v3 by default system, without resetting the default to python2, you will need to:

- Fork machinekit and make the changes to that fork.
We are not going to accept PRs from other repos which are considerably different to ours.

- Fix all **237** instances of  `/usr/bin/env python` and `/usr/bin/python` in the code base, plus all instances of `exec python` or simply `python` etc. in the myriad of scripts etc.

We are not being difficult for the sake of it and hope you can appreciate the issues involved from our perspective

**Comment by l29ah** [comment]
On Thu, Dec 14, 2017 at 09:31:51AM +0000, ArcEye wrote:
> You have only forked Linuxcnc and have not submitted this patch to them, made me wonder why we had been honoured.

`hub fork` decided to re-use my linuxcnc repo for machinekit, dunno why, maybe one can't have separate repos for forks of one project?

> - Fork machinekit and make the changes to that fork.
> We are not going to accept PRs from other repos which are considerably different to ours.

wat
I suggest you to learn github's user interface or use `git` to examine my changes.

> - Fix all **237** instances of  `/usr/bin/env python` and `/usr/bin/python` in the code base, plus all instances of `exec python` or simply `python` etc. in the myriad of scripts etc.

I've only fixed the ones i could test. I'm certainly not going to go through all the code base and find out how is it used, if used at all, and test it.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Pull request closed without merging**
