### PR TITLE
Travis-CI Improvements

### PR DESCRIPTION
**Pull request by kinsamanka**
# Note: this PR will fail the current CI tests

Delete the travis env `DOCKER_CONTAINER` and then restart the tests. 

## Improvements
- gcc 4.7 for wheezy builds
- ccache support 

[travis-ci results](https://travis-ci.org/kinsamanka/machinekit/builds/97648560)

The Docker container was renamed due to issues encountered with the Docker registry autobuilder. Improvements made by @zultron on the original mkdocker container were incorporated into this new container. The dockerfiles can be found [here](http://github.com/kinsamanka/machinekit_builder)

### CODE REVIEW

**Comment by mhaberler** [comment]
"Delete the travis env DOCKER_CONTAINER and then restart the tests." - towards whom is this directed?

should this be merged nevertheless?

**Comment by kinsamanka** [comment]
To the maintainer who will merge this PR :-) 

The new docker container used breaks the current travis setup. So while this PR is tested all new PRs will fail the travis-ci tests.

**Comment by mhaberler** [comment]
@kinsamanka call me an idiot - what do I need to do before/after I hit the merge button ;-?

**Comment by zultron** [comment]
This PR looks fine to me.  Have you checked if the Travis CI caching facility can be used?  I think it's available for the GCE containers for free.

Why don't you set up the Travis CI repo settings how you need to get this to pass, and rerun the build?  Once we see it pass, someone can merge it.

**Comment by kinsamanka** [comment]
GCE is for non-docker based builds only.

If we can run the regression tests on chroot, we might be able to use the GCE based containers.

**Pull request merged**
