### PR TITLE
ArcEye/update-iocontrol-set-current-tool 0 allowed

### PR DESCRIPTION
**Pull request by alkabal**
Hi again

Very cool the new stuff with one, only one thing for me 0 is a valid number for reset purpose for safety if something ATC failure

I hope this is acceptable but T0M6 is a valid Gcode
the issue : after some crahs of the ATC or E-stop killing when ATC is moving if the ATC need to be homed again axis don't know that with old number in memory now ask a gcode with same number and bye bye if your ATC is in some wrong position.

Br

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by alkabal** [comment]
this solve one week of time sleepless for fight with actual system for reset the tool to 0.

**Comment by luminize** [comment]
Ok to test

**Comment by ArcEye** [comment]
The whole point of the original commit was to allow the GUI and NML to be updated as to the current tool position in the ATC.
For those purposes 0 is NOT a valid tool number, as that position does not exist.

You need to fix whatever defects in your Tool changer component or your other setup that require resets to get out of trouble. 
I have never had to use T0M6 and with an ATC it makes no sense whatsoever.

If you want to change iocontrol for solely your own purposes, that is fine, but you cannot change a general purpose distributed  component to suit your own needs.

The command for T0M6 will be passed by iocontrol to your tool changer component and that is where it needs to be dealt with.

Telling the system that your ATC is at a non-existent position is not the answer.

**Comment by alkabal** [comment]
In the way you says after a failure ATC need to correct herself, so ATC need to move without user asking ?can be dangerous.

Your first modified files allows to ask 0, in the GUI send T0M6 make a clean reset i have some trouble to understand.

In the whole iocontrol nothing other make some check of this type, this is the job for other side of iocontrol, so this i the ATC or other who deal with it.

As my understanding ioncontrol is a open user/component interface i think this release with the check of the toolnumber is not in the way of general purpose.

Br

**Pull request closed without merging**
