### PR TITLE
man/man-generated rework, this PR replaces PR #445

### LINKED ISSUE #433: generating .asciidoc for pushing to machinekit-man
We need to use the (generated) manpages for building .asciidoc files that represent homo-sapiens readable documentation of i.e. the components and drivers. Buildbot thing for pushing to machinekit-man

### LINKED ISSUE #434: enhancement of troff-to-asciidoc.py
the [troff-to-asciidoc conversion script](https://github.com/machinekit/machinekit/blob/master/scripts/troff-to-asciidoc.py) now has errors when parsing some manpages. (like no info in SYNOPSIS section). Therefore the ignoring of the error in [this](https://github.com/machinekit/machinekit/blob/master/src/hal/components/Submakefile#L52), [this](https://github.com/machinekit/machinekit/blob/master/src/hal/components/Submakefile#L62) and [this](https://github.com/machinekit/machinekit/blob/master/src/hal/components/Submakefile#L73) line for ignoring this error during build.

Probably we want to run this not from the Submakefile anymore, but separately so we can more easy also generate the `.1`, `.3rtapi`, `.3hal` and `.9` files in `man/man1`, `man3` and `man9`

### PR DESCRIPTION
**Pull request by luminize**
this branch replaces #445 by not having the asciidoc files added and committed.
fixes #433
fixed #434
and prepares has a Makefile in man/man-generated which can be used to generate `.asciidoc` files

### CODE REVIEW

**Comment by zultron** [comment]
Looks good!  (Pending Buildbot)

Looks like I have yet another Buildbot update to integrate:  Generating man-pages.

**Comment by luminize** [comment]
Should we try Docker??? ;)

**Comment by zultron** [comment]
I'm still looking at Docker, trying to understand exactly what it does.

Looks like it's not the cloud-based package-building platform I hoped 
for.  It does make image building simple and repeatable, and makes 
images easy to distribute.

Packages for the images still need to be built somewhere.  Those could 
be built in a Docker 'container', maybe even a Docker Buildbot 
container.  Containers run on your own hardware, so that would make it 
easy for anyone to set up a Buildbot.

There's another service, 'resin.io', that supposedly works with Docker 
and may build software.  I haven't looked carefully enough yet.

It looks like it could be possible to move much of the Buildbot 
heavy-lifting to the cloud by building packages in OBS and installing 
them in a Docker container.  The Buildbot would still need to run the 
'RIP' builds for the tests, still a heavy job.

That's partly what my 'master daemon' project is about:  enabling tests 
to run inside of package builds (and getting Michael's nosetests into 
production).  Alternatively, it might be easier/faster to put the tests 
into packages so that the RIP build isn't necessary, and tests could run 
directly against the packages.  Then the Buildbot master would only need 
to run lightweight logistics, and test build slaves could be run in VMs 
on an ordinary PC.

Anyway, lots of work there, and competing priorities!

	John

**Comment by luminize** [comment]
Buildbot succeeded. Going to read up on the RIP installation troubles :)

**Comment by zultron** [comment]
Whoops, didn't mean to clutter this issue with all that.  Sorry!

Stand by for merge.

**Pull request merged**
