### PR TITLE
hostmot2: add support for mesanet ethernet boards 7i80, 7i76e, 7i92

### PR DESCRIPTION
**Pull request by micges**
Signed-off-by: Michael Geszkiewicz <micges@wp.pl>

### CODE REVIEW

**Comment by strahlex** [comment]
Buildbot failed

**Comment by zultron** [comment]
Yep, kthreads module builds only, choking on `hm2_eth.c`.

**Comment by micges** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Yeah, driver must be disabled under rtai, working on it.

**Comment by micges** [comment]
I think it's working now.

**Comment by mhaberler** [comment]
@micges - super, wildly appreciated!!

**Comment by micges** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
I'm just warming up :)
 
Hm2_eth driver tested on 7i80DB and 7i76e, much more tests will be prepared later especially for mesa epp boards.
From now I'll be maintaining hostmot2 driver and I'll try to help with motion redesign/fix/improve as I've touched few parts while maintaining joint_axes branch and making it working (not finished but usable).
 
Michael

**Pull request merged**
