### PR TITLE
Add demux16 and demux16v2 components to instantiated components.

### PR DESCRIPTION
**Pull request by ArcEye**
Adapted from components (c) Les Newell <lesATsheetcamDOTcom>

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
Whoever looks at this can you also merge https://github.com/machinekit/Machinekit-HAL/pull/15, still stacking from yesterday
Cheers

**Comment by luminize** [comment]
I'll await the CI and merge when completed.

**Comment by ArcEye** [comment]
Bump.

**Comment by luminize** [comment]
Forgot I was waiting :)

**Comment by ArcEye** [comment]
No problem, I was doing something else last couple of days and just checked back in

**Pull request merged**
