### PR TITLE
Fixes for Jessie

### PR DESCRIPTION
**Pull request by zultron**
Stack of commits needed for Jessie & new build scripts

### CODE REVIEW

**Comment by zultron** [comment]
Ok, this branch is ready for merge.  Buildbot passes.

**Comment by RunningLight** [comment]
I'm creating virtual machines from the just-released jessie images so I can test this at home. I assume that unless I run into something unexpected, I can update the building-from-sources page which currently emphasizes wheezy while I'm at it.

**Comment by zultron** [comment]
I don't have Jessie packages online.  (Actually have old, out-of-date ones.)  Aside from kernel (and keyring) packages, Jessie still needs `czmq` and `libwebsockets`.

If you want to start testing, I can push a repo out today.

**Comment by RunningLight** [comment]
That would be great. The new jessie images just finished installing.

**Comment by zultron** [comment]
The Jessie (and Wheezy and Trusty) packages are copying right now.  It'll take a while to finish.

The repo is at http://deb.dovetail-automata.com/deb-testing/.  Problems you'll find:

- It uses a temporary signing key.
- Machinekit won't compile on Jessie armhf qemu.  Apparently this is a regression in qemu.  Armhf packages must be compiled on armhf hardware.
- These packages are *completely* untested.  Please report bugs!

**Comment by RunningLight** [comment]
Hmmm. Freshly installed a debian jessie amd64 virtual machine and followed steps in `http://machinekit.io/docs/build-from-source`, making what I thought were appropriate changes for jessie vs wheezy and for your temporary repo location. Build failed at `scripts/apt-installbuilddeps` with
```
E: Unable to locate package libzmq4-dev
```
Too tired to look uplist to see what was done about this previously. Will tackle tomorrow.

**Comment by zultron** [comment]
Ok, to be not perfectly helpful, I don't use `scripts/apt-installbuilddeps`.  The issue here is that I'm dropping `libzmq4` from the pkg repo, so you need to install Jessie's `libzmq3` instead.

(The `libzmq4` fiasco was from my expectation that when ZeroMQ v. 4 came out, the Debian package name would be bumped; instead it became `zeromq3-4.0.0`, but still with .so v. 3.x, and then wasn't renamed after the upstream .so version bump at 4.0.something.  :P )

**Comment by RunningLight** [comment]
Well, we have to use something (we discussed it in machinekit/machinekit.github.io#25)

I've confessed before that the Tao of Debian is not in me. From `debian/control` by way of `debian/control.in` comes the line

```
libzmq3-dev (>= 4.0.4) | libzmq4-dev (>= 4.0.4)'
```
I thought the vertical bar meant `or`?

Anyway, after installing libzmq3-dev manually, the build is proceeding as I write this. One more modification to the instructions.

**Comment by RunningLight** [comment]
Ok, build finished, but then `sudo make setuid` reports

```
...
Makefile:732: recipe for target 'setuid' failed
make: [setuid] Error 1 (ignored)
```

where lines 731/732 of Makefile read

```
setuid:
            $(call fix_perms,../libexec/linuxcnc_module_helper)
```

Since `make` ignored the error so did I.

Ran `. ./scripts/rip-environment` and invoked `machinekit`

Got a popup error window complaining about a missing `bwidget 1.7 package` so I installed `bwidget` manually.

Invoked `machinekit` again and selected `sim/axis-mm`. The Axis GUI comes up and I can take the simulated machine out of emergency stop but toggling  machine power gets me nowhere. The following shows up on sysout

```
TCL error in asynchronous code:
wrong # args: should be ".toolbar.program_step cmd ?arg ...?"
    while executing
".toolbar.program_step"
    invoked from within
"if {$::last_interp_state != $::INTERP_IDLE || $::last_task_state != $::task_state} {
		set_mode_from_tab
	    }"
    (procedure "update_state" line 44)
    invoked from within
"update_state"
    ("after" script)
```

To quote the old vaudeville routine, 'slowly I turned, step by step'.

**Comment by mhaberler** [comment]
bwidget was removed from builddeps recently, but it should be in the deps for running ml

Do we have any retirement home contact where we can find a TCL coder ;-?

**Comment by zultron** [comment]
Right, `bwidget` isn't a real build dep, but it is still in the `machinekit` package `Depends:` list.  (I did that as a step toward cross-compiling, since `bwidget` doesn't support `Multi-Arch:`.)  Looks like this `apt-installbuilddeps` script needs to be looked at to install 'runtime-deps' as well?

The `tcl` package is bumped to v. 8.6 in Jessie and Trusty, but v. 8.5 is still available.  Want to try removing 8.6, installing 8.5 and trying again?

**Comment by RunningLight** [comment]
Well, in the near term, we can just keep amending the list of needed packages in the build-from-source instructions, but, yes, I think this script should be looked at. The less user-intervention required the better.

I'll try downgrading to 8.5 and rebuilding in a bit...(re)setting up tftp/nfs support for my ARM boards at the moment to catch up with Doug. Still, I thought 8.6 used to work?!?

The pressure is on now that Debian 8.0 is the default. I noticed that RCN has already updated the packages on eewiki for the ARM boards he supports.

**Comment by mhaberler** [comment]
I think such fixups should go through direct editing of https://github.com/machinekit/machinekit.github.io

(or do you think it makes sense to do a PR/find an admin to merge? I think there should be some lower bar of change significance below we'd just do it directly before it gets forgotten)

**Comment by mhaberler** [comment]
re apt-installbuilddeps: these are the steps it takes for pulling in build deps:

what is the right dpkg incantation to get the runtime deps? 
I'll give it a stab - educate me ;)


````
method2 ()
{
  pfx="dpkg-checkbuilddeps: Unmet build dependencies:"
  deps=`dpkg-checkbuilddeps 2>&1 | grep "^$pfx" | \
        sed -e "s/$pfx//" -e s'/([^)]*)//g'`
  echo apt-get "$@" install $deps
  apt-get "$@" install $deps
  dpkg-checkbuilddeps
}
````

**Comment by RunningLight** [comment]
Re @haberler remark about directly editing machinekit.github.io, I could go either way. At the moment, though, I'm more concerned about getting our facts right:)

**Comment by RunningLight** [comment]
FYI, the Trusty packages in ./deb-testing/ worked just fine once I added libzmq3-dev and bwidget by hand. Cython is available in the mainline repo so no backport is needed.

Test host: Ubuntu 14.04.2LTS in a VM in Oracle VirtualBox.

**Comment by RunningLight** [comment]
FYI, trying to test the Wheezy packages in ./deb-testing/, I ran into a problem early on. apt can't find libwebsockets-dev.

**Comment by strahlex** [comment]
This merge introduced a problem with the package updates on Wheezy:
```
sudo apt-get upgrade     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have been kept back:
  cloud9-installer machinekit machinekit-dev machinekit-xenomai
```
and
```
sudo apt-get install machinekit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 machinekit : Depends: python (= 2.7) but 2.7.3-4+deb7u1 is to be installed
```

**Comment by RunningLight** [comment]
Regarding the need to satisfy runtime-dependencies in an rip build, e.g., for `bwidget`, the only idea I've come up with is to write our own script which parses the `debian/control` file. As things stand now, `debian/configure` generates the `Package: machinekit` section in the control file which includes a list of  runtime dependencies in its `Depends:` stanza. I've played with various packaging helpers and searched the usual suspects and so far I don't see anything which meets our need. To be frank, writing our own script doesn't seem much better than installing the dependencies by hand as we do now in the building-from-source instructions since @zultron had to generate that the list in that `Depends:` stanza by hand (yes?).

**Comment by RunningLight** [comment]
@strahlex I was building from sources so didn't see this problem. Just guessing, but it may trace back to `debian/control` where we have the requirement

```
Package: machinekit
...
Depends: ... ,
python ( = ${python:Versions})'
...
```
In other sections of the control file like `Source: machinekit` and `Package: machinekit-dev` we are more lenient on the version of python required, either specifying a lower limit or lower and upper limits on the version and not a strict equality.

**Comment by strahlex** [comment]
@RunningLight >= 2.6 << 3.0 might be sufficient at the moment. Except websockets I am always using the latest packages version here on OpenSUSE Tumbleeweed which is a rolling release distro

**Comment by RunningLight** [comment]
@zultron any technical reason the stated python requirements differ subtly between sections in `debian/control`? Do you think this is the root cause of @strahlex's observed problem or is it just another one of my famous red herrings which turn out to be academically interesting at best and utter nonsense at worst?

@strahlex I only addressed the second part of your report. Do you think the `cloud9-installer` package is kept back for the same reason? (I've never tried cloud9 and don't know its dependencies.)

**Comment by zultron** [comment]
I might've been too hasty committing c3ce094f.  I'll put in a PR to revert it.

**Comment by strahlex** [comment]
@RunningLight No different problem `cloud9-installer : Depends: c9-core-installer but it is not going to be installed`

**Comment by zultron** [comment]
@RunningLight, does #606 address the "python requirements [that] differ subtly between sections in debian/control"?  I believe that's part of Alexander's fix, but evidently there's more.  :package: 

@strahlex, try installing with `aptitude`.  It gives a clear statement of why the dep solver failed.

**Comment by RunningLight** [comment]
@zultron  regarding your question three days ago, yes, #606 seems to have resolved the subtle differences in python requirements I mentioned occur in the `debian/control` file which is created by `configure`. However, where the requirement is stated explicitly (in the `Source` section), it is now only a lower bound (>=2.6.6-3~). As I read it, this wouldn't prevent trying to link to Python 3. Is this a potential problem?

**Comment by zultron** [comment]
@RunningLight, the `python` package is implicitly v. 2 only.  To install Python 3, one must explicitly request `python3`.

The lower bound is there just to strictly follow the `dh_python2(1)` manpage, even though MK doesn't target any distro that ships a python that old.

**Pull request merged**
