### PR TITLE
CHIP GPIO driver

### PR DESCRIPTION
**Pull request by machinekoder**
GPIO driver for the [NextThing CHIP](https://getchip.com/pages/chip). Drives the CSID pins per memory map.

Mass production has started and so we need a driver. Tested with a self-compiled RT PREEMPT kernel.

### CODE REVIEW

**Comment by machinekoder** [comment]
Can a build system guru please check if the integration is correct.

**Comment by evanmj** [comment]
Excellent! I was wondering why I bought 2 of these. I am happy to see support for it. Thanks!

**Comment by machinekoder** [comment]
@zultron Does this look sane?

**Comment by ArcEye** [comment]
I have patched a branch and built this driver OK using `./configure --with-platform-chip`
I assume the distribution will be via SD images, it would not be included in any packages.

Can't do anything else with it on a x86_amd64 rt-preempt system :smile:  
The build bit works fine.

**Comment by machinekoder** [comment]
I wonder how the Raspberry GPIO driver is deployed. Does it hurt to add this driver to the armhf package? Would be a lot more convenient to have it in the Machinekit package.

**Comment by machinekoder** [comment]
I found and fixed some issues in the driver.

**Comment by ArcEye** [comment]
Sorry been doing other stuff.

> I wonder how the Raspberry GPIO driver is deployed. Does it hurt to add this driver to the armhf package? Would be a lot more convenient to have it in the Machinekit package.

AFAICT the other drivers that are only going to be required on armf platforms like BBB and raspberry, are built by default when the armf platform is selected.
```
--with-platform-socfpga 
		      Build for Socfpga platform (default for ARM arch)
--with-platform-beaglebone
                      Build for Beaglebone platform (default for ARM arch)
--with-platform-raspberry
                      Build for Raspberry platform (default for ARM arch)
```

Because you copied the configure.ac  entries for these to select your CHIP driver, that should also apply to your driver.

I will merge, I know it builds OK and we can check for its presence in the armf packages once completed.

**Comment by ArcEye** [comment]
They haven't all finished building yet, but the driver is being included in the armhf packages, so looks OK
```
$ INTEL-i7:/downloads# dpkg --contents machinekit-xenomai_0.1.1473781726-1mk.travis.master.git7aa0c928~1wheezy_armhf.deb | grep hal_chip

-rw-r--r-- root/root     10312 2016-09-13 17:24 ./usr/lib/linuxcnc/xenomai/hal_chip_gpio.so
```

**Comment by machinekoder** [comment]
Thanks. Btw. we are featured on the [CHIP blog](http://blog.nextthing.co/3-great-community-created-tutorials-quake-ii-fluxbox-and-machinekit/).

**Comment by luminize** [comment]
Nice @strahlex !

**Comment by zhivko** [comment]
Very Nice I wonder how this platform compare to BeagleBone Black in
performance - for price I see it is much cheaper.
regards

**Comment by ArcEye** [comment]
> Thanks. Btw. we are featured on the CHIP blog.

Pity they used a very old Linuxcnc graphic for Axis :(

That's a good blog on the CHIP board.  
Now I have finally received all the bits for my Pine64 board, I must look into mmap GPIO on that.  The  /sys access works fine, just a question of figuring out the memory block location.

**Comment by machinekoder** [comment]
@zhivko Performance-wise the CHIP can't hold up with the BBB. The CHIP does not feature a PRU or FPGA for offloading signal generation.

**Pull request merged**
