### PR TITLE
emcmodule.cc: Added python method to set axis home parameters

### PR DESCRIPTION
**Pull request by jpmoniz**
Patch to allow the setting of axis homing parameters while inside GUI.

### CODE REVIEW

**Comment by mhaberler** [comment]
waiting for http://buildbot.dovetail-automata.com/grid to declary victory..

**Comment by jpmoniz** [comment]
Will do. Thanks for the guidance!!

**Comment by mhaberler** [comment]
what you can do next time: correct the patch, and force-push it
github will automatically update the pull request with the new tip, and the buildbot will trigger again; so no need to close and reopen the PR

**Comment by jpmoniz** [comment]
No. That was me just not reading and pushing the wrong button, when trying to thank you

**Comment by mhaberler** [comment]
ah, ok - so reduced need for handholding then ;)

**Pull request merged**
