### PR TITLE
Merge machinekit-multicore into machinekit - Full history

### PR DESCRIPTION
**Pull request by ArcEye**
Multicore support -

    - v2 pin_ptr
    - pin handle is a descriptor reference, not a raw memory location
    - all pin ops wrapped in inline accessors, using atomic ops
    - settable memory barrier on per-pin basis (pre-op read barrier, post-op =
    write barrier)
    - v2+v1 pins completely interoperable
    - integrates concurrencykit.org primitives

    Ringbuffers
    - lockfree-queues for messaging between any combination of RT and non-RT =
    comps
    - stream (character-oriented) flavor
    - record (type-length) flavor
    - multipart (n*(type,length,value) flavor) - mirrors zeroMQ message =
    structure
    - strongly typed messaging support through multipart type field
    - choice of encoded vs unrolled-into-C-struct format by conveying =
    encoding in type field (fast vs simple)

    Triple-buffer support primitives
    - for last-update-counts semantics (eg like emcstat or comms between =
    base+servo thread in stepgen, encoder)
    - stepgen, encoder, encoder_ratio, pwmgen multicore-hardened - drops =
    need for 'rate-monotonic scheduling' requirement
    - based on =
    http://remis-thoughts.blogspot.co.at/2012/01/triple-buffering-as-concurren=
    cy_30.html

    Extends Instantiable components
    - They can now use v2 pin_ptrs and supports accessors
    - creates code to reuse kernel module parameters safely over sucessive instances

    Extends HAL object management
    - completely hide the HAL internals (like explicit list walks) behind a =
    selector and iterator API. No need for any using code to poke around in =
    the HAL shm segment.
    - Split out generic HAL object management from type-specific operations, =
    making the HAL object API usable for all objects uniformly (no per-type =
    lists).

    Extends RTAPI-level K&R-based shared memory allocator=20
    - full malloc/free functionality. Removes the 41-char HAL name limit =
    since all names dynamically allocated.

### CODE REVIEW

**Comment by ArcEye** [comment]
This PR is byte identical in code to the previous #1121 
The git history however has been preserved

Assuming Travis builds OK, I will do tests with hm2_soc_ol / hm2_pci  etc just to be sure and advise
ready to merge

**Comment by ArcEye** [comment]
Good so far - Travis builds.

I have also pulled the branch into a clone of machinekit/master.  It pulls without errors and builds.
Normal axis_mm sim and the v2-icomp-demo sim run

Have now built it on the DE0-NANO-Soc.
hm2-soc-ol-stepper sim runs OK.  
hostmot2 and hm2_soc_ol loaded from the command line and all pins and params visible.

Just remains to test with the DB25 interface connected to a real machine

**Comment by ArcEye** [comment]
Real world test running a mill with 7i76 interface passed.

Ready to merge when you are brave enough to hit the button :smile: 

I will do a short post after lunch, mostly to advise DE0-NANO users of the changed newinst line

**Comment by dkhughes** [comment]
This newinst line affects all users of hm2-soc, including Zynq, correct?

**Comment by ArcEye** [comment]
> This newinst line affects all users of hm2-soc, including Zynq, correct?

Yes, the solution is simply to use the `--` delimiter before the config line as per
https://github.com/machinekit/machinekit-multicore/blob/master/configs/hm2-soc-stepper/hm2-soc-ol-stepper-5i25.hal#L40

**Pull request merged**
