### PR TITLE
src/Makefile: fix 'cp: cannot copy cyclic symbolic link - during make…

### PR DESCRIPTION
**Pull request by koppi**
…', mentioned in #613.

### CODE REVIEW

**Comment by zultron** [comment]
This PR doesn't pass Buildbot.

In addition, using `cpio` creates copies of the files rather than hard links.  Can you look into `cp -l` or other hard-linking methods?

**Comment by koppi** [comment]
@zultron cp -rlfd worked for me.

**Comment by zultron** [comment]
Sounds good.

The final PR contains 6 patches to fix 1 line.  Can you squash those together and force-push your branch?  (`git rebase -i` is your friend)

**Comment by koppi** [comment]
Thank's for the git hints, just squashed and  force-pushed the branch.

**Pull request merged**
