### PR TITLE
machinetalk/mwkrapper: implemented program extensions

### PR DESCRIPTION
**Pull request by strahlex**
This adds support for program extensions other than ngc to mkwrapper

### CODE REVIEW

**Comment by strahlex** [comment]
Buildbot runtests failed. I have no idea why this patch could influence the runtests

**Comment by strahlex** [comment]
@zultron Was that also related to the low disk space?

**Comment by strahlex** [comment]
Buildbot tests work now. Was maybe the low disk space that caused the error.
Ready to merge

**Comment by zultron** [comment]
The failure of the POSIX tests?  I can't explain it.  Maybe a remnant effect of the full disk, since those tests are not among the few heisenbug tests that intermittently fail.  Should be OK, but I'm keeping an eye out for repeats....

**Pull request merged**
