### PR TITLE
Fixes R_ARM_MOVW_ABS_NC relocation issue on armv7hl

### PR DESCRIPTION
**Pull request by dwrobel**
Compiling usercomp adxl345.comp
armv7hl-redhat-linux-gnueabi-gcc -DULAPI -I. -Imachinetalk/build -Imachinetalk/nanopb -Imachinetalk/include -Imachinetalk/webtalk -Ilibnml/linklist -Ilibnml/cms -Ilibnml/rcs -Ilibnml/inifile -Ilibnm
l/os_intf -Ilibnml/nml -Ilibnml/buffer -Ilibnml/posemath -Irtapi -Irtapi_export -Ihal/lib -Ihal/vtable-example -Ihal/userfunct-example -Ihal/drivers -Ihal/cython -Iemc/nml_intf -Iemc/kinematics -Iem
c/motion -Iemc/tp -Iemc/ini -Iemc/rs274ngc -Iemc/pythonplugin -I/usr/include/python2.7 -o ../bin/adxl345 -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-rpath-link,../lib -Wl,--no-as
-needed \
         objects/hal/user_comps/adxl345.c \
        ../lib/liblinuxcnchal.so.0 \
        ../lib/librtapi_math.so.0
/usr/bin/ld: /tmp/ccG0bkPM.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/tmp/ccG0bkPM.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
hal/user_comps/Submakefile:23: recipe for target '../bin/adxl345' failed

### CODE REVIEW

**Comment by dwrobel** [comment]
The linking issue affected armv7hl platform, however it revealed that some of the source files are compiled using different options (e.g. in this case usual CFLAGS wasn't applied while compiling adxl345.c).

**Comment by ArcEye** [comment]
I don't know enough about the differences between `armv7hl` and `armhf`, to tell if there are any potential conflict implications from this.

I'll defer to @cdsteinkuehler

**Comment by cdsteinkuehler** [comment]
It's not really an arm issue, it's a gcc issue.  The first of the two changes adds -fPIC to CFLAGS to create position independent code.  I'm not sure why this would be needed for armv7hl and not any of the other architectures we currently build for, or if this needs to be handled differently for user space programs and HAL components.

The second change is adding $CFLAGS to LDFLAGS.  I'm not enough of a gcc guru to know if that has any potentially nasty side effects, but I think this is the wrong fix.  It looks to me like LDFLAGS is used in the user_comp Submakefile when it should be CFLAGS:

https://github.com/machinekit/machinekit/blob/master/src/hal/user_comps/Submakefile#L27

I recommend fixing the user_comps/Submakefile to use CFLAGS, and if -fPIC is really needed it should probably be added to the Submakefile and not to the global Makefile (as is done in various other hal/ Submakefiles)

**Comment by machinekoder** [comment]
@dwrobel Is this still an issue? If so, can you please take a look at the suggested solution.

**Comment by dwrobel** [comment]
I could verify it on Fedora 26 using GCC 7 but unfortunately MK is no longer compilable on it due to #1152.

**Comment by ArcEye** [comment]
To keep the majority of peoples configs working, we are probably going to have to stick with the existing czmq version for the present.

There are other backwardly incompatible library changes in the pipeline before too long.
eg. https://github.com/machinekit/machinekit/issues/1193

**Comment by luminize** [comment]
Seems this PR has gone silent. If I'm in error then please re-open.

**Pull request closed without merging**
