### PR TITLE
Add IO to motion output  pins

### PR DESCRIPTION
**Pull request by strahlex**
Fix for the motion IO pin issue: https://github.com/machinekit/machinekit/issues/451

Uses a similar approach to fix the problem that outputs are driving a signal as the out-io pin of the lincurve component: https://github.com/machinekit/machinekit-man/blob/master/man9comp/lincurve.9comp.asciidoc#pins

### CODE REVIEW

**Comment by mhaberler** [comment]
I'm going to merge this because it addresses a problem you have, but I do not like it at all - it is just more of the motion patchwork on pin IO and I really suggest looking into an alternative

that said, I think this scheme should go away altogether and be replaced by a scheme where pin I/O can travel the motion queue properly (i.e as normal motion commands, not as haphazard piggyback on some move) and arbitrary pins at that (identified by handle for instance as in haltalk)

**Comment by mhaberler** [comment]
I do not see the interpreter work needed to talk to these pins. How is this going to happen?

**Comment by strahlex** [comment]
As mentioned in the man page it just replicates the state of the normal out pin, so no changed to the interpreter. The same solution has been used by the lincurve component. I do not like it either, but adding real I/O pins to motion would require introduction of new MCodes and work on the interpreter.

I also tought about combining in and output pins but that is not suitable for every application and would break compatibility with older configurations. Just making the output pins I/O would be even more ugly.

I would much appreachiate to the see real I/O support in motion and the interpreter.

**Comment by mhaberler** [comment]
do you mean these pins behave like the out pins, and are just mirrored? if yes, this is firmly kludge territory

please open an issue and start a requirements thread for "real I/O support" (I dont know what "real" is supposed to mean here), we must get rid of such hacks

**Comment by strahlex** [comment]
On Monday 26 January 2015 04:09:44 Michael Haberler wrote:
> do you mean these pins behave like the out pins, and are just mirrored? if
> yes, this is firmly kludge territory
> 
> please open an issue and start a requirements thread for "real I/O support"
> (I dont know what "real" is supposed to mean here), we must get rid of such
> hacks
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit/pull/465#issuecomment-71451710
There is one place where the output pins are set in the motion component. Now 
two pins are set instead of one. The out-io pins have no additional 
functionality like the normal output pins. They can't be queried by NML and 
are not mirrored in the NML memory structure. Input is ignored.

**Pull request merged**
