### PR TITLE
remove test for DTOV_STAT_APPLIED (device tree overlay applied)

### PR DESCRIPTION
**Pull request by the-snowwhite**
and increase delay of waiting for fpga configure end.

Signed-off-by: Michael Brown <producer@holotronic.dk>

This works great for me on both the DE10 and DE0 Nano SoC's

However please on a different  setup (ie. with Roberts image) before merging.

### CODE REVIEW

**Comment by cdsteinkuehler** [comment]
From my reply to the list:
I think that's the right direction, but I'm not sure just removing the
check for DTOV_STAT_APPLIED is safe in all instances.  I'd have to
crawl through the hm2_soc code (not enough time right now), but from
memory, I think it would be better to pass two strings to the code.
One string (mandatory) would indicate the uio device name to use for
mapping the memory region and interrupt.  The second (optional) string
would indicate a device-tree file to attempt to load/unload.

So without a device-tree overlay string, the driver will fail to load
if it doesn't find the proper uio device.  When passed a device-tree
overlay string, the driver should behave as it does now (attempt to
load or unload/reload the overlay).

How does that sound?

**Comment by cdsteinkuehler** [comment]
Upon further reflection, the "mandatory" uio device name should be optional and have a sensible default if it's not passed on the command line.  The optional device tree overlay name should not (so the driver doesn't do anything with loading/unloading device tree overlays if a specific overlay name isn't passed in).

**Comment by dkhughes** [comment]
Been away for a while - completely removing the check to see if the driver properly loaded firmware seems unsafe for the generic driver. I agree with @cdsteinkuehler, there should be a way to instruct the driver to check or load the firmware if desired. If it's already loaded, skip it.

**Comment by the-snowwhite** [comment]
I believe this commit:
#1328
Fixed this issue
Loading the firmware and running mk without firmware load worked fine in my latest DE10/DE0 Nano stretch releases with this config file:
https://github.com/machinekit/machinekit/blob/master/configs/hm2-soc-stepper/5i25-soc-cramps_no-fw-load.ini

Only part left:

I'm not sure if this instruction ever made it into the docs:
  
     hal driver initialisation example:

    newinst HOSTMOT2 [HOSTMOT2]DEVNAME already_programmed=1 -- config=HOSTMOT2

**Comment by luminize** [comment]
> On 2 Aug 2018, at 10:29, Michael Brown <notifications@github.com> wrote:
> 
> Only part left:
> 
> I'm not sure if this instruction ever made it into the docs:
> 
>  hal driver initialisation example:
> 
> newinst HOSTMOT2 [HOSTMOT2]DEVNAME already_programmed=1 -- config=HOSTMOT2

Can you check that and update if needed?

**Comment by the-snowwhite** [comment]
@luminize 
done:
https://github.com/machinekit/machinekit-docs/blob/master/docs/man/man9/hm2_soc_ol.asciidoc

**Comment by luminize** [comment]
Great! Thx

**Pull request closed without merging**
