### PR TITLE
Haltalk command cleanup

### PR DESCRIPTION
**Pull request by machinekoder**
Follow up to https://github.com/machinekit/machinekit/pull/1172

@ArcEye I did take another close look at the haltalk_command code and fixed more potential problems. I think we need to do a complete review at some point.

### CODE REVIEW

**Comment by machinekoder** [comment]
Sorry for the whitespace cleanup but the mixup of tabs and spaces is unbearable.

**Comment by luminize** [comment]
> On 15 Mar 2017, at 17:54, Alexander Rössler <notifications@github.com> wrote:
> 
> Sorry for the whitespace cleanup but the mixup of tabs and spaces is unbearable.
> 
I don't mind, as long as the whitespace fixes are not together with other changes. And there's a setting for not viewing whitespace changes on github
https://github.com/blog/967-github-secrets

It's been a long standing "issue" of code standaards. I'm not really into standaards, but more on consistency, at least in one file. Could we adopt a common practice, with instructions on setting up for example emacs?

**Comment by ArcEye** [comment]
> Could we adopt a common practice, with instructions on setting up for example emacs?

Wouldn't do anything for me, I don't use emacs on principle ( the principle being that it is the 21st century not 1980 :stuck_out_tongue_closed_eyes:  )

**Comment by machinekoder** [comment]
@ArcEye That's one reason why there is http://editorconfig.org/

**Comment by luminize** [comment]
> On 15 Mar 2017, at 18:39, ArcEye wrote:
> 
> Could we adopt a common practice, with instructions on setting up for example emacs?
> 
> Wouldn't do anything for me, I don't use emacs on principle ( the principle being that it is the 21st century not 1980 😝 )
> 
Yeah, but sometimes when i'm working on a BBB from ssh what does one get? At least i get around a bit better than vi :)

I also use atom.io a lot on my pc, or sublime text...

Open to suggestions

**Comment by machinekoder** [comment]
@luminize Choose your editor: http://editorconfig.org/#download

**Pull request merged**
