### PR TITLE
limit3 comp:  fix 1st order limit violations and drift

### PR DESCRIPTION
**Pull request by zultron**
This is a rework done for LCNC a year or so ago.  It keeps track of
the input signal and the min/max limits separately so that when the
input signal exceeds a limit, the output doesn't crash into the limit
trying to follow it.  It also tries to be a little smarter by looking
at the input signal velocity to predict when it will come back in
limit, and starts accelerating early to meet it.

It also fixes the problem where output can drift away from input at
zero velocity, fixed separately by @machinekoder back in July.

See related discussion at these issues & PRs:

https://github.com/LinuxCNC/linuxcnc/issues/240
https://github.com/LinuxCNC/linuxcnc/pull/351
https://github.com/LinuxCNC/linuxcnc/issues/378
https://github.com/LinuxCNC/linuxcnc/pull/396
https://github.com/machinekit/machinekit/pull/1384

### CODE REVIEW

**Comment by zultron** [comment]
BTW, this is my first try at a v2 comp.  Please pass eyeballs over, and also let me know if the extra set of tests should be done differently.

**Comment by zultron** [comment]
The tests failed because of the `threads.0` test, unrelated to this patch.

**Comment by ArcEye** [comment]
> BTW, this is my first try at a v2 comp. Please pass eyeballs over, and also let me know if the extra set of tests should be done differently.****

The tests all pass
```
Running test: tests/limit3/constraints
Running test: tests/limit3/limit-accel-and-max
Running test: tests/limit3/limit-max-velocity
Running test: tests/limit3/lock-on-input-and-limits
Running test: tests/limit3/min-max-overshoot
Running test: tests/limit3/runaway
Running test: tests/limit3/sunny-day
Running test: tests/limit3v2/constraints
Running test: tests/limit3v2/limit-accel-and-max
Running test: tests/limit3v2/limit-max-velocity
Running test: tests/limit3v2/lock-on-input-and-limits
Running test: tests/limit3v2/min-max-overshoot
Running test: tests/limit3v2/runaway
Running test: tests/limit3v2/sunny-day
```
so don't see a problem.

The v2 components are really just about declaring `pin_ptr` and using the get/set methods to access them rather than direct pointer dereferencing and you seem to have done that fine.

If the buildtests problem IS restricted to Jessie, I can just switch that build to Stretch and run this again.

**Comment by ArcEye** [comment]
Did we determine that the threads.0 failure was just under Jessie?

If so I can switch the runtests build to Stretch and try that

**Comment by zultron** [comment]
@ArcEye I don't understand your question.  Is the `threads.0` failure relevant here?  I thought it was a spurious error, as elaborated on in machinekit/machinekit-hal#173, and further testing isn't necessary.  If you think otherwise, I'll gladly follow your lead.

**Comment by ArcEye** [comment]
@zultron at some point I am sure you said that the threads.0 test error only occurred in Jessie.

If that is the case, I was saying I could change the PR runtest element to use Stretch and avoid getting failures from this error.

I will change it anyway and re-run the PR build - see what happens :smiling_imp:

**Comment by zultron** [comment]
Ugh, my memory is horrible.  Thanks for re-running this build.

**Comment by ArcEye** [comment]
Looks like I changed to Stretch tests some while back, so that shoots down that theory:(
I will just merge it, everything else passed

**Comment by zultron** [comment]
Actually, I'm happy the Stretch `threads.0` tests continue to fail:  my theory in machinekit/machinekit-hal#173 still stands, and we have a potential fix.

Thanks for the merge.

**Pull request merged**
