### PR TITLE
Remove troff man pages - do not merge yet - will break docs[1]

### PR DESCRIPTION
**Pull request by ArcEye**
Make generated asciidoc option only.

Asciidoc pages now in /man/man1-3-9
Generated pages are only built if specifically required with
configure switch --enable-build-documentation
(the =type value is deprecated as this is the only document type used)

[1]
Will require some minimal path re-jigging in the site rendering
infrastructure, to pull the new generated asciidoc repo path.
ie. change /man/docs/man? to /man/man?

Signed-off-by: Mick arceye@mgware.co.uk

### CODE REVIEW

**Comment by ArcEye** [comment]
That is legacy troff man pages all removed, with an alternative terminal viewing mechanism added.

Ready to merge when the docs side of it has the path amended.

I think that changing https://jenkins.machinekit.io/view/machinekit/job/machinekit-manpages/configure
> Post Build Actions > Archive the artifacts path to /man/man9/*
should just enable the site docs to be updated as required.

@mhaberler if you can confirm that please, not sure if there is a separate destination path elsewhere.

**Comment by ArcEye** [comment]
Minor edit to existing commit - no action required

**Comment by ArcEye** [comment]
Ditto

**Comment by mhaberler** [comment]
hm, still a conflict

are you sure we want a filename  rtapi_app_exitrtapi.asciidoc ? (I dont quite see what the trailing rtapi before .asciidoc adds - there's already a leading rtapi_ ? if it is meant as a section, wouldnt that be more like foo.3rtapi.asciidoc?)

as for artefacts and carrying over static manpages: seems you and @luminize want static manpages in mk/mk - so let's clarify what needs to be done:

- what does this now mean for the artefacts carry-over in jenkins -  do I need to store ALL of man/* in the artefacts?
- what happens to the existing static manpages in mk/mk-docs/ - note that several pages in https://github.com/machinekit/machinekit-docs/tree/master/docs/man have already been edited so for those  somebody needs to decide which is the latest one, and keep that in whatever is the proper place - I assume  move back the modified static manpages to mk/mk and erase them in mk/mk-docs?

speaking of artefacts: I think we should keep the generated manpages in a branch of mk/mk and adapt the build process (package build on merge) to store them so they can be easily imported with a git pull

**Comment by ArcEye** [comment]
> hm, still a conflict

That arises because the files in this PR  (principally comp and instcomp) have been amended in other PRs in the interim, I can just rebase this (if that is the correct terminology) onto a current pull of master and they will disappear.

> are you sure we want a filename rtapi_app_exitrtapi.asciidoc ? (I dont quite see what the trailing rtapi before .asciidoc adds - there's already a leading rtapi_ ? if it is meant as a section, wouldnt that be more like foo.3rtapi.asciidoc?)

No. That is just an accident of bulk renaming from hopelessly convoluted original file names.
Easy to fix

> as for artefacts and carrying over static manpages: seems you and @luminize want static manpages in mk/mk - so let's clarify what needs to be done:

I assume that all future references to `man pages` mean `asciidoc manual pages`

I think the only sane thing to do is to have all the manual pages in mk/mk and pull en bloc.
Any 'edit this page' should go to mk/mk, not the copy in mk/mk-docs or whatever
So long as the bulk of man9 pages are generated and their contents potentially unknown until build time, I cannot see any other option.

A possible solution from this 'serpent eating its tail' situation is to make all manual documents a separate package.
If that was held in a separate repo, which had generated asciidocs updated from builds if components changed, that might solve the issue.

It might help clarify boundaries at least :unamused:

**Comment by mhaberler** [comment]
> A possible solution from this 'serpent eating its tail' situation is to make all manual documents a separate package.
If that was held in a separate repo, which had generated asciidocs updated from builds if components changed, that might solve the issue.

what if that separate package is in fact machinekit-docs containing both static and generated manpages?

Nothing prevents us from pushing generated asciidoc to this repo automatically, it would take care of the "vanishing generated pages", and one would have a single workflow for working on static manpages and other website content

and in case we find a way to generate legacy man pages from asciidoc, the mk-man package build would be tacked on the mk-docs build

**Comment by ArcEye** [comment]
> what if that separate package is in fact machinekit-docs containing both static and generated manpages?

> Nothing prevents us from pushing generated asciidoc to this repo automatically, it would take care of the "vanishing generated pages", and one would have a single workflow for working on static manpages and other website content

That is fine.
All static manual pages removed to the mk-docs repo, 
generation of component manual pages only via an unadvertised configure switch, which we expect only 'buildbots' to use.

It could even be disabled for RIP builds and /man removed completely - but that would probably be inconvenient to those - like me - who only ever use RIPs.
If you write a new component, no way to check the generated manual doc.

If a user wants asciidoc manual pages, they install a package built from mk-docs to a path that mank will search and they can view them.

The only other bone of contention is generated manual docs, these need clearly labelling in some way to show that they cannot be edited directly in any meaningful way.

**Comment by ArcEye** [comment]
All conversation moved to Issue #995 
This PR is not workable in its current form and withdrawn

**Pull request closed without merging**
