### PR TITLE
hal_bb_gpio:  add PocketBeagle GPIOs

### PR DESCRIPTION
**Pull request by zultron**
- Add PocketBeagle GPIO pin data
- Add new `board={BeagleBone,PocketBeagle}` driver option, default BB
- Set macros for per-board info
- Work macros into logic
- Add `get_pin_data.py` script to help scrape new future boards

### CODE REVIEW

**Comment by ArcEye** [comment]
Can one of the admins verify this patch?

**Comment by zultron** [comment]
Yeah, any problems here won't be caught in the regression tests.

I've tested only on the PocketBeagle so far, and I have a BeagleBone (white) in my hand.

**Comment by ArcEye** [comment]
This won't put any packages in the repo at present.
I will merge as soon as I need to test the system again

**Comment by ArcEye** [comment]
Closing and opening to try to trigger PR webhook

**Comment by ArcEye** [comment]
Can one of the admins verify this patch?

**Comment by ArcEye** [comment]
Now switching back to TravisCI, as the error appears to be at the server end

**Pull request merged**
