### PR TITLE
Bug fix instantiated components

### PR DESCRIPTION
**Pull request by ArcEye**
Use of kernel module params led to unwanted persistence in parameters
between instances
Were never designed to be used more than once

At each exit, components now reset pincount param to -1

Components now check value of pincount param, if -1 set
will set value to DEFAULTCOUNT, and then
copy to localpincount variable in inst_data struct,
resetting pincount to -1 at exit

Ensures that if no size is specified, component gets default number of
pins and any previous size cannot persist and affect next instance where
no size is specified.

MAXCOUNT and DEFAULTCOUNT options added to instcomp, which must
be set if pincount is used to set pin array sizes

Affected components, docs amended

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
Runtests to follow, but in interim to see behavior
DEBUG=5 realtime restart
loadrt debounce
(will load default 8 filters)
newinst debounce debounce.1 pincount=2
(will load new inst with 2 filters)
newinst debounce debounce.2
(will load default 8 filters)

Then see linuxcnc.log for dbg messages showing the value in pincount at differing stages
Initially -1 in 2 instances and then set to DEFAULTCOUNT of 8

**Comment by mhaberler** [comment]
kicking the tire..

                        If a component uses the pincount parameter
                        to set array sizes
                        both MAXCOUNT and DEFAULTCOUNT must be set.

hal/i_components/Submakefile:46: recipe for target 'halcomp-srcs/hal/i_components/select8.c' failed
make: *** [halcomp-srcs/hal/i_components/select8.c] Error 1

**Comment by ArcEye** [comment]
It does not use pincount any more, I forgot to update it !!
reset and fresh push comming soon

**Comment by mhaberler** [comment]
the select8 comp is a tad weird, it's one of these 'let me engrave this in concrete' type examples which could be done much more flexibly with the new API

I dont see why it couldnt be a selectN where N is anything from 2 upwards to some reasonable upper limit

but then lets just fix selec8 for now, see if any configs use it, and get smarter if time permits

**Comment by ArcEye** [comment]
Refreshed and select8 is in there now

**Comment by ArcEye** [comment]
mux16 refreshed also
Running out of time and rushing, if there is anything else , will have to wait until later, sorry

**Comment by ArcEye** [comment]
OK back
Those 2 files were in the last commit, which I squashed to prevent a load of 'changes to changes' in the new commit and they got left out

Just cloned and built Ok so hopefully all complete

**Comment by mhaberler** [comment]
ah, removing the unused funct in the comp makes runtests unhappy. Man, this "regression test" thing is so lame :-/

**Comment by ArcEye** [comment]
OK, back home.
Just needs to be run through, then swap results file for expected and run through again
In process now

**Comment by ArcEye** [comment]
139 of 139 passed and update the PR

**Comment by mhaberler** [comment]
yeee-haw!!

**Comment by ArcEye** [comment]
Dont worry about it, I will fix it when I get back, just needs to be run through then swap result file for expected and run through again

Should be home in an hour

Sent from my HTC

----- Reply message -----

**Pull request merged**
