### PR TITLE
Update hal_gpio driver for Raspberry Pi 3

### PR DESCRIPTION
**Pull request by rtolesnikov**
/proc/cpuinfo returns

Hardware        : BCM2709
Revision        : a22082

I am unable to compile and test this patch at the moment due to configuration challenges.

### CODE REVIEW

**Comment by ArcEye** [comment]
Looks as though this failed on all builds, because https://api.rubygems.org/specs.4.8.gz was not available

That downloads manually now, so closing and reopening to trigger a build to test the system.

**Comment by ArcEye** [comment]
Fails because of incomplete switch / case  statement (no colon after `case 4` )
```
hal/drivers/hal_gpio.c:223:7: error: expected ':' or '...' before 'rtapi_print_msg'
       rtapi_print_msg(RTAPI_MSG_INFO, "Raspberry3\n");
```

Once fixed I think it will need testing for real to confirm the revision number is recognised programmatically. 
Not many people are going to have this board.

**Comment by ArcEye** [comment]
@koppi 
Did you test that this board revision was recognised by the driver?

Only reason I delayed, was that the author seemed unwilling to test for some strange reason, given he had the board he wanted supported, and no-one else was coming forward to do so and confirm.

**Comment by devilmind** [comment]
Hi guys,
I have an RPI 3 model B 

Hardware        : BCM2835
Revision        : a02082

 I need to use the GPIO to use my machine but I not understood how install the patch or the drivers for GPIO.
when I try to compile the hal_gpio.c also I obtain 

root@raspberrypi:~# comp --compile hal_gpio.c
Traceback (most recent call last):
File "/usr/bin/comp", line 26, in <module>
from yapps import runtime
ImportError: No module named yapps
root@raspberrypi:~# 

Can you explain or share me the steps to install the patch if required or what is missing to compile it pls?

Thanks a lot.

**Comment by ArcEye** [comment]
There is no 'patch', the revision is supported, you need to update machinekit.
https://github.com/machinekit/machinekit/blob/master/src/hal/drivers/cpuinfo.c#L77

**Comment by devilmind** [comment]
Oh great!
I have installed the machinekit today, so I think that I have the latest version, right?
Thank you

**Comment by luminize** [comment]
> On 10 Aug 2017, at 18:07, devilmind <notifications@github.com> wrote:
> 
> Oh great!
> I have installed the machinekit today, so I think that I have the latest version, right?
> Thank you
> 
That depends on what (if) image you used. If you followed the installation instructions then "apt-get update" and "apt-get upgrade" should get you the latest.

**Comment by devilmind** [comment]
I have installed it following the doc at http://www.machinekit.io/docs/getting-started/APT-packages-jessie/
but I haven't performed apt-get upgrade.  I need to do that?

**Pull request merged**
