### PR TITLE
Home offset

### PR DESCRIPTION
**Pull request by cdsteinkuehler**
Exports joint home and home_offset positions via HAL
Resolves machinekit/machinekit#423

### CODE REVIEW

**Comment by zultron** [comment]
There's a bunch of cruft left in `#if 0` blocks and lines commented out with `//`, is that intentional?

**Comment by cdsteinkuehler** [comment]
On 1/12/2015 11:52 PM, John Morris wrote:
> There's a bunch of cruft left in `#if 0` blocks and lines commented out with `//`, is that intentional?

There are three spots where the previous joints arrays were being
allocated that fit that description.  If that's what you're referring to
I left the code there for hints in case of merge conflicts pulling
updates in from g.l.o.  I haven't tried merging much from g.l.o. into
Machinekit...if you don't think the breadcrumbs are needed they can get
deleted.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by zultron** [comment]
Ah, seems you're more thoughtful than I am.  :)  What does the merge-master, @mhaberler, think?

**Comment by mhaberler** [comment]
do I feel somebody pulling my leg here?

**Comment by mhaberler** [comment]
there are two minor things I'd do before merging, other than that I think it's fine

make param a pin
use the the value of num_joints as the loopcount for the number of pins

(happy to do that if you want me to)

downstream I see two changes coming this direction:

"axis..." will become "joint..." as jaX gets merged
technically that is a case for a persistent tunable config item, so it will serve as a great use case once we have it

re the CONFIG_CHANGE/config_num mechanism.. I just read through the logic and it doesnt affect this patch because emcmot_config_t (https://github.com/machinekit/machinekit/blob/master/src/emc/motion/motion.h#L739) doesnt hold any himing related values, so those are ships in the night

**Comment by mhaberler** [comment]
@zultron : I never thought you would use such an un-C4.1-ish term like "merge master", which positively goes against fundamental values held dearly in our egalitarian flat world ;)

**Comment by zultron** [comment]
@mhaberler, sorry about that, I've been chastened.  Rephrase:

As someone who's done a huge amount of merging from glo in the past, what is your opinion about how leaving those lines in vs. taking them out affects difficulty of merging?

I like to take that kind of cruft out, since while refactoring code, I've come across a lot of that, left in from ancient times, didn't know why it was left there, and had to make a decision about what to do with it.  On the other hand, Charles has a good point I've never considered.  Opinion?

**Comment by zultron** [comment]
Over IRC, @mhaberler said "<mhaberler> I dont lean either way really; dont think it matters".  Thanks!

**Comment by cdsteinkuehler** [comment]
On 1/13/2015 12:45 PM, John Morris wrote:
> 
> I like to take that kind of cruft out, since while refactoring code,
> I've come across a lot of that, left in from ancient times, didn't
> know why it was left there, and had to make a decision about what to
> do with it.  On the other hand, Charles has a good point I've never
> considered.  Opinion?

When refactoring or otherwise cleaning up code, you're killing the
ability to (easily) merge from g.l.o. regardless, so feel free to remove
any cruft.

I'll leave it to Michael to comment on if leaving the lines in makes
sense for now.  I guess I left them partly as breadcrumbs for potential
merge conflicts, and partly because I'm not familiar enough with the
code to be 100% sure I'm doing the right thing.  It's pretty tricky
figuring out exactly what's going on in motion.  :-/

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
I didnt touch the comments, but made the HAL params HAL pins: https://github.com/mhaberler/machinekit/commit/a09b61451fc1535f35b9a5514c4abee263f5de41

cursory testing looks ok - second pair of eyeballs warranted

**Comment by cdsteinkuehler** [comment]
On 1/14/2015 2:39 AM, Michael Haberler wrote:
> 
> cursory testing looks ok - second pair of eyeballs warranted

The code changes look OK, but I'm wondering why you didn't switch the
HOME parameter as well:

https://github.com/machinekit/machinekit/pull/431/files#diff-94c2356f179cc869f93b7ac94ccf2472R1011

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
duh, sorry. Repair in progress.

**Comment by zultron** [comment]
On 01/13/2015 12:52 PM, cdsteinkuehler wrote:
> On 1/13/2015 12:45 PM, John Morris wrote:
>  >
>  > I like to take that kind of cruft out, since while refactoring code,
>  > I've come across a lot of that, left in from ancient times, didn't
>  > know why it was left there, and had to make a decision about what to
>  > do with it. On the other hand, Charles has a good point I've never
>  > considered. Opinion?
>
> When refactoring or otherwise cleaning up code, you're killing the
> ability to (easily) merge from g.l.o. regardless, so feel free to remove
> any cruft.

Yes, but the point was, when refactoring, I spend a lot of time 
reverse-engineering what the last developer wrote to ensure nothing is 
forgotten.  If there's a block of code disabled with `#if 0`, I have to 
try to figure out what that was for (breadcrumbs, debugging, something 
for the future, etc.) and whether to keep it.  If the last dev had 
either removed it entirely or written a comment (e.g. `//left for merge 
breadcrumbs`), it would be way easier.

Anyway, if the above still doesn't make sense, I'll drop it.  I think 
this just triggers painful memories of cleaning up thousands of lines in 
`src/rtapi`.  ;)

**Comment by cdsteinkuehler** [comment]
That makes sense, John.

I added comments just above the #if 0 lines, but perhaps I didn't make
them clear enough?

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by zultron** [comment]
You certainly did, and I lost sight of that over the two days since the PR and my fervor for dropping the baggage of the past.  Sorry about that.  I'll merge this whenever it's ready.

**Comment by mhaberler** [comment]
my tickle PR passed the bot: https://github.com/machinekit/machinekit/pull/439

should we merge #439 or brush up this PR?

**Comment by cdsteinkuehler** [comment]
PR 439 is ready to go, so I'd say just merge that.  I'd merge it but even though it's not my PR, I authored all but one of the commits, so I'll leave it to someone else.

**Pull request merged**
