### PR TITLE
Hal pru generic update

### PR DESCRIPTION
**Pull request by machinekoder**
This PR ports back a selection of relevant fixes from the upstream pruss driver:
https://github.com/beagleboard/am335x_pru_package

### CODE REVIEW

**Comment by ArcEye** [comment]
Have you tested this actually building packages on armhf?

I changed machinekit-hal to generate the pru_generic files for all armhf builds, so that they were available for rt-preempt and even posix if required.
I found that the way that components and modules are built for all flavours in a ` for each` loop led to failures of the package builds
This is what happened the last time it was tried.

The solution was just to build for posix and then copy across (they are byte identical)

You also need to change the packaging, or the files will be created but won't go anywhere.

See https://github.com/machinekit/Machinekit-HAL/commit/c9f59e09865bc9a62a033f5a005b6af6a81f71d6 and the last bit of this https://github.com/machinekit/Machinekit-HAL/commit/e45f4056bafe3a3107d3c2077e13ea78aaa93a09 which was sublimated into the later commit.

If you want to remove commit 8bdobd, I can introduce the packaging changes etc from machinekit-hal in a follow up PR, I was going to do it anyway.

**Comment by machinekoder** [comment]
Building the binary for posix only will give you trouble when you build without the posix flavor in RIP development situation. I suggest re-enabling the `TARGET` line and building it flavor independently. It would make more sense to place the PRU binary in the flavor independent lib folder anyway.

I will remove the commit for now as this PR is independent of this change.

**Comment by ArcEye** [comment]
> Building the binary for posix only will give you trouble when you build without the posix flavor in RIP development situation

That is a corner case, only occurring where someone has not installed an OS first, or has deliberately deleted the posix kernel, that I still have to overcome.

The main argument is that these binaries are a fixed format, independent of the flavour and _should_ only be built once.  The trick is to do it in a way that works for RIP builds and packages

>  suggest re-enabling the TARGET line and building it flavor independently.

Unfortunately that is the crux of the problem when building packages that I sought to overcome.
If you remove the xenomai requirement to build, it builds correctly for the first flavour but then screws up trying to copy over the files for the subsequent flavours, into directories which don't exist yet.

This is what caused the failures requiring reversion of the commit, the last time it was tried.
https://github.com/machinekit/machinekit/commit/598b4c73691d8535633186d7e58d17ac169547af

> It would make more sense to place the PRU binary in the flavor independent lib folder anyway.

Agreed, it would make more sense to put these and all the modules in a single directory.
They are exactly the same, now we have removed hard kernel threads.

If you comment out the flavour check at rtapi_main.c:128, machinekit will run quite happily on a rt-preempt kernel but using posix modules, I've tried it.

I need to think some more on it, the machinekit-hal code was really only a stopgap to get things built on rt-preempt.

If the PASM stuff could be separated from the main pru build that would work.

What I don't know is the mechanism by which the BBB looks for the pru_generic.bin etc
Is that path set in a script etc that can be altered, or will it always look in the same path as the modules?

**Comment by darenschwenke** [comment]
The path to use is set on the loadrt line in the hal, which comes from the ini:
https://github.com/machinekit/machinekit/blob/master/configs/ARM/BeagleBone/CRAMPS/CRAMPS.hal#L28
https://github.com/machinekit/machinekit/blob/master/configs/ARM/BeagleBone/CRAMPS/CRAMPS.ini#L4

**Comment by ArcEye** [comment]
Thanks, apparently there is also hard coded stuff in hal_pru.c too
I need to make sure I catch it all 😆

**Pull request merged**
