### PR TITLE
Revamp of instcomp man page generation

### PR DESCRIPTION
**Pull request by ArcEye**
Changed to explain instantiable component loading via newinst
and show alternative pin naming if newinst used

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
Ooooh how I hate troff :(

**Comment by ArcEye** [comment]
Produces a man page in this format
```
DEBOUNCE(9)                                                                                      HAL Component                                                                                     DEBOUNCE(9)

INSTANTIABLE COMPONENTS
       All instantiable components can be loaded in two manners

       Using loadrt with or without count= | names= parameters as per legacy components

       Using newinst, which names the instance and allows further parameters and arguments,

       primarily pincount= which can set the number of pins created for that instance (where applicable)

NAME
       debounce - Debounce filter for Machinekit HAL

SYNOPSIS
       debounce

SYNOPSIS
       loadrt debounce

       newinst debounce <newinstname> [ pincount=N | iprefix=prefix ] [instanceparamX=X | argX=X ]

FUNCTIONS
       debounce.N.funct
              OR <newinstname>.funct (requires a floating-point thread)

PINS
       debounce.N.#.in  bit in (M=0..pincount)
              ( OR <newinstname>.#.in  bit in (M=0..pincount)  )

       debounce.N.#.out  bit out (M=0..pincount)
              ( OR <newinstname>.#.out  bit out (M=0..pincount)  )

       debounce.N.#.state  s32 io (M=0..pincount)
              ( OR <newinstname>.#.state  s32 io (M=0..pincount)  )

       debounce.N.delay  s32 io (default: 5)
              ( OR <newinstname>.delay  s32 io (default: 5) )

INST_PARAMETERS
       pincount int (default: 8)

AUTHOR
       John Kasunich, adapted by ArcEye

LICENSE
       GPL

Machinekit Documentation                                                                          2015-11-01
```

**Comment by ArcEye** [comment]
Thanks Bas, 

This was niggling at the back of my mind and I finally had the time and inspiration to do it.
Hopefully will take the pressure off the documentation, when specific components are the issue.

Need to give some thought to a simple way to convert all the man pages to asciidoc with a view to augmenting https://github.com/machinekit/machinekit-docs/blob/master/src/hal/components.asciidoc
so as hold the details on line

**Comment by luminize** [comment]
I worked on that for creating the machinekit-man repo.
have a look at this (by no means perfect, some glitches in the generated asciidoc):
https://github.com/machinekit/machinekit/blob/master/scripts/troff-to-asciidoc.py

my branch where everything is:
https://github.com/luminize/machinekit/commits/machinekit-man

It was the idea to generate asciidoc files when you compile. Still on my todo list to get these files in an automated way into machinekit/machinekit-man

**Pull request merged**
