### PR TITLE
Configs

### PR DESCRIPTION
**Pull request by muggins**
This pull modifies the configs for Xylotex (DB25) so that it runs on a CandCNC BOB.

https://github.com/machinekit/machinekit/pull/1441/commits/eb850232ff6c97d7cb6960213e895d81feea3996

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by muggins** [comment]
I think I finally got the corrected commit ready for a pull.

**Comment by luminize** [comment]
@muggins I think something went wrong with rebasing. You have some merge conflicts. (see https://github.com/machinekit/machinekit/pull/1441/conflicts ). You can remove the part between the ====== and <<<<<< or >>>>>> that's wrong, just add that fix in a commit, push that to your branch so it appears in this PR. (or use the Github web editor, I got no experience with that though)

**Comment by ArcEye** [comment]
I am looking at it in the github interface at the moment.
Just need to bring up the existing files in another window to double check what changed.

**Comment by ArcEye** [comment]
I have resolved the conflicts.
Will let the tests run, even though they are meaningless regards this and then merge

**Pull request merged**
