### PR TITLE
Final cross-build tweaks

### PR DESCRIPTION
**Pull request by zultron**
These are a last few tweaks needed for cross-building (or maybe "arising out of the cross-building effort").

- Remove package build-deps needed for building kernel threads
  - This could be avoided, but it's easier than installing them into build container images, and aren't kthreads obsolete?
- Remove a FIFO left behind by one group of regression tests that isn't removed by `git clean` but that chokes `dpkg-source`
  - Also not strictly needed for cross-building, but makes testing cross-building packages and RIP+tests from the same tree much easier

### CODE REVIEW

**Comment by ArcEye** [comment]
I can see that having removed the dependency upon kmod | module-init-tools, one cannot then test for the presence of its contents, even if it is practically impossible to have a functioning system in which they are not present.

I am a little uneasy about removing the tests for insmod in that section of configure.ac only, when so many other references to it exist in the code and indeed we are still building `linuxcnc_module_helper`

Could I be a pain and ask that the tests are just commented out, with a brief note as to why.

This could make things far more easily understood, if at some point a root and branch removal of kthread code is conducted.

**Comment by zultron** [comment]
@ArcEye Sure, that's absolutely fair.  I'll even take a stab at conditionally disabling them if kthreads aren't to be built, which is what we'd do if kthreads weren't deprecated.

**Comment by ArcEye** [comment]
Thanks, that's a much better solution than just commenting out stuff

**Comment by zultron** [comment]
@ArcEye I think this approach is a little overboard, since we'll end up just pulling it back out along with the whole kthreads system at some point, but anyway the userland threads tests pass.  I did just a little checking to see if `debian/configure` could enable kthreads, but no testing further than that.

**Comment by zultron** [comment]
Ah, merged!  Thanks.

**Pull request merged**
