### PR TITLE
indextablev2.icomp: add indextable component

### PR DESCRIPTION
**Pull request by luminize**
This component is meant for controlling an indexing table.

### CODE REVIEW

**Comment by luminize** [comment]
Just occured to me. Should this component have the trailing v2?

**Comment by ArcEye** [comment]
Yes, it must be the same name as the file, or instcomp will error.
Michael and I were looking at automatic detection of system capabilities and loading v2 if supported, but until something like that is done, it needs to be obvious what it is.
You could always modify it to a v1 component too and add that for the full complement :smile:

**Comment by luminize** [comment]
> On 16 May 2017, at 13:22, ArcEye wrote:
> Yes, it must be the same name as the file, or instcomp will error.
> Michael and I were looking at automatic detection of system capabilities and loading v2 if supported, but until something like that is done, it needs to be obvious what it is.
> 
I see, v2 after the name is ok.
> You could always modify it to a v1 component too and add that for the full complement 😄
> 
Well, I prefer to go forward. So adding only v2 components might make adaption of new features speed up. v1 components are mostly still around for not breaking existing configurations, right?

**Comment by ArcEye** [comment]
Onwards and upwards

**Pull request merged**
