### PR TITLE
Mklauncher: add support for importance/favorites

### PR DESCRIPTION
**Pull request by machinekoder**
This PR adds support for launcher importance to mklauncher. The feature can be used to implement user based favorites on the client.

### CODE REVIEW

**Comment by machinekoder** [comment]
@luminize This PR needs to be synchronized with Machinekit HAL.

**Comment by ArcEye** [comment]
@machinekoder 
Do you want me to merge this?

Transferring to Machinekit-HAL may not be easy, because it contains a merge and a squash commit which tends to bugger up cherry-picking.
But I'll leave @luminize that pleasure 😈

**Comment by luminize** [comment]
> On 8 Sep 2017, at 12:23, ArcEye <notifications@github.com> wrote:
> 
> @machinekoder
> Do you want me to merge this?
> 
> Transferring to Machinekit-HAL may not be easy, because it contains a merge and a squash commit which tends to bugger up cherry-picking.
> But I'll leave @luminize that pleasure 😈
> 
I was hoping @machinekoder could do this since he knows exactly what's going on...

If not I'll try

**Comment by machinekoder** [comment]
@ArcEye here it is https://github.com/machinekit/machinekit/pull/1271

**Comment by ArcEye** [comment]
I assume you mean Machinekit-HAL:#35

**Comment by machinekoder** [comment]
@ArcEye Yes, sorry. Too many tabs.

**Pull request merged**
