### PR TITLE
Prefer to use /dev/gpiomem over /dev/mem

### PR DESCRIPTION
**Pull request by dwrobel**

### CODE REVIEW

**Comment by ArcEye** [comment]
@dwrobel 
There is no description of why this should be the preferred access.
It would help if you described the rationale in PR's.

AFAICT 
`/dev/mem` is bullet-proof, but requires root access
`/dev/gpiomem` is user accessible, but requires the user to have a late raspbian kernel patched with this device, that will not exist on earlier kernels (Ben Croston patched in early 2016)

This method tries the `/dev/gpiomem` route first and then falls back onto `/dev/mem`, if that fails.

This extract from the PR explains why adopted
```
Currently, libraries such as RPi.GPIO are accessing /dev/mem to get to the GPIO registers directly, 
which works very well but has a number of issues, not the least of them the fact that you have to run
as root whenever you touch GPIO.

As a first step away from this, we're adding a device, /dev/gpiomem, which gives you access to the 
GPIO registers without root permission. It will always map your pointer to the correct location of the 
registers, so there is no need to parse /proc/devicetree to try and figure out where they are.
```

I'll await a comment from someone more knowledgeable as to whether this change is necessary in a component that can work quite happily with `/dev/mem` irrespective of kernel version.

**Comment by dwrobel** [comment]
The rationale for this change is to allow machinekit to run without root access. Currently with this PR + the following two changes:

1. remove superfluous checking geteuid() != 0

```
diff --git a/src/rtapi/rtapi_app.cc b/src/rtapi/rtapi_app.cc
index a872047..c7e2691 100644
--- a/src/rtapi/rtapi_app.cc
+++ b/src/rtapi/rtapi_app.cc
@@ -1186,18 +1186,6 @@ static int mainloop(size_t  argc, char **argv)
        exit(EXIT_FAILURE);
     }

-    // make sure we're setuid root when we need to
-    if (use_drivers || (flavor->flags & FLAVOR_DOES_IO)) {
-       if (geteuid() != 0) {
-           rtapi_print_msg(RTAPI_MSG_ERR,
-                           "rtapi_app:%d need to"
-                           " 'sudo make setuid' to access I/O?\n",
-                           instance_id);
-           global_data->rtapi_app_pid = 0;
-           exit(EXIT_FAILURE);
-       }
-    }
-
     // assorted RT incantations - memory locking, prefaulting etc
     if ((retval = harden_rt())) {
        rtapi_print_msg(RTAPI_MSG_ERR,
```
2. additionally /usr/libexec/linuxcnc/rtapi_app_rt-preempt doesn't use _set-user-ID_ but only ['cap_sys_nice'](http://man7.org/linux/man-pages/man7/capabilities.7.html).

Thanks to this MK can be run as an ordinary user (I'm using it on kernel: 4.4.30-400rt.c1f53f1.bcm2709.fc24.armv7hl).

**Comment by ArcEye** [comment]
It appears that root access requirement, would be replaced by a requirement that the user be a member of the `gpio` group, which is not automatically implemented in all distros with raspbian kernels having the `/dev/gpiomem` device.

> remove superfluous checking geteuid() != 0

I am struggling to see how the geteuid() checking would be superfluous, for anything other than this particular rpi2/3 driver 'corner case'.

> Thanks to this MK can be run as an ordinary user

Not familiar at all with the raspbian builds, but for all other builds you _have_ to run MK as an ordinary user, or are you talking about building without setuid?

**Comment by cdsteinkuehler** [comment]
I'm not sure /dev/gpiomem is going to stick around, but since this is only changing the RPi driver (which is AFAIK the only place one can find /dev/gpiomem), it seems like a reasonable change.

**Comment by dwrobel** [comment]
@ArcEye

> you have to run MK as an ordinary user,

Yes, but in standard installation _rtapi_app_rt-preempt_ runs effectively as a root user anyway.

> or are you talking about building without setuid?

I'm talking about installing it without setuid and use only: cap_sys_nice, cap_sys_rawio capabilities for rtapi_app_rt-preempt. Then even for accessing /dev/mem you don't need to use setuid.

**Comment by ArcEye** [comment]
>    you have to run MK as an ordinary user,
Yes, but in standard installation rtapi_app_rt-preempt runs effectively as a root user anyway.

That is the object of the setuid obviously

>I'm talking about installing it without setuid and use only: cap_sys_nice, cap_sys_rawio capabilities for rtapi_app_rt-preempt. Then even for accessing /dev/mem you don't need to use setuid.

If you think all the checks and conditional action alterations required in the make process, to potentially deal with this minority interest board differently from every other one, are worth it, 
feel free to make a full PR.

I personally can't get excited about running without setuid, the board should not be exposed on an externally accessible network anyway, security being the only valid reason I can see. 

But each to their own.  :smile:

**Pull request merged**
