### PR TITLE
document and brush up RT symbol exports and linking method

### PR DESCRIPTION
**Pull request by mhaberler**
The purpose of this PR is to:

- drop support for the POWERPC architecture which was bitrot since long
- document the somewhat arcane linking method of userland RT modules - how they emulate kernel symbol visibility to aid Gemi with the cmake build
- finally, adopt Jeff Epler's commit "build: use a different method to expose symbols"   from https://github.com/LinuxCNC/linuxcnc/commit/e4b94a5df9968bd3fec0b18e38e2fb3b856482a7

this is not only more portable but will work on the aarch64 as well (and possibly on the powerpc)

this locally runtests fine - criticial review appreciated!

### CODE REVIEW

**Comment by ArcEye** [comment]
The IS_POWERPC stuff in Makefile.modinc surprised me when I saw it.

Does anyone use them?

**Comment by mhaberler** [comment]
nope, that's dead since long

however, I do not exclude it actually works after this commit (post fixing); just nobody has a powerpc platform these days

**Comment by mhaberler** [comment]
@ArcEye I cannot reproduce this travis error - fine on amd64 jessie, armhf jessie here

could you give this branch a spin? I'd really appreciate it - just if the build passes

for instance, a build fails with
`````
Linking ../rtlib/xenomai/pbmsgs.so
/usr/bin/ld:objects/xenomai/pbmsgs.ver:2: syntax error in VERSION script
collect2: error: ld returned 1 exit status
Makefile:1577: recipe for target '../rtlib/xenomai/pbmsgs.so' failed
`````

however, locally that pbmsgs.ver file looks ok - as per above there should be something wrong with line 2: 

`````
{ global : 
rtapi_info_author;
rtapi_info_description;
rtapi_info_license;
rtapi_app_main;
rtapi_app_exit;
pb_Container_fields;
pb_Function_fields;
pb_Instance_fields;
pb_Pin_fields;
pb_Param_fields;
pb_Signal_fields;
pb_Group_fields;
pb_Ring_fields;
pb_Component_fields;
pb_Application_fields;
pb_File_fields;
pb_Preview_fields;
pb_MotionCommand_fields;
pb_MotionStatus_fields;
pb_RTAPI_Message_fields;
pb_RTAPICommand_fields;
pb_LogMessage_fields;
msginfo;
local : * ; };
``````

**Comment by ArcEye** [comment]
I'll be able to in a while, what platform do you want it built on?

**Comment by ArcEye** [comment]
Jessie amd64 - builds fine here too

**Comment by ArcEye** [comment]
Wheezy amd64 - builds fine too

I will try Wheezy Xenomai in a while

**Comment by ArcEye** [comment]
Also builds on 3.8.1-xenomai-x86-amd64

If you want x86 builds will take a while, would need to install build environment on that partition, just have packages.

**Comment by mhaberler** [comment]
I guess we need to try with the travis docker image

**Comment by mhaberler** [comment]
ok, I think I found it, using the docker image roughly so: https://github.com/machinekit/machinekit/issues/791#issuecomment-166331935 (jessie-64 instead of wheezy-armhf)

root@7269c6154bd6:/usr/src/machinekit/src# cat objects/rt-preempt/ringload.ver
{ global :
local : * ; };

simple case of no exported symbols..

**Comment by mhaberler** [comment]
I suspect it is the /dev/stdout usage in a container, plus this issue: https://github.com/docker/docker/issues/11462

**Comment by ArcEye** [comment]
Glad you found it.

All greek to me, I stopped following the docker stuff when Gemi and Bob engaged warp drive :smile:

**Comment by mhaberler** [comment]
it was not a case of no exported symbols - it was just /dev/stdout failing under docker
seems to pass now

**Comment by ArcEye** [comment]
FYI now have a x86 Xenomai Wheezy build environment set up too, your branch built fine on that too.

**Comment by mhaberler** [comment]
thanks! 
I think it is good to merge

**Pull request merged**
