### PR TITLE
Add demo sim config using instantiable components

### PR DESCRIPTION
**Pull request by ArcEye**
Clean up instcomp, unused vars and comments etc

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by strahlex** [comment]
Created a PR yesterday, not sure it covers all uses of the .funct suffix: https://github.com/machinekit/machinekit/pull/567

**Comment by mhaberler** [comment]
no it doesnt, see buildbot

**Comment by ArcEye** [comment]
I already have a full commit, just finishing testing the runtests.

Incidentally, I see i_multiclick  is still in there, I thought you had removed it, or did you just discount the buildbot failure as an aberation?

**Comment by ArcEye** [comment]
PR submitted #571 
passes 154 of 154, with the caveat re i_multiclick working on the buildbot

**Pull request merged**
