### PR TITLE
Cosmetic rebranding to MachineKit from Linuxcnc

### PR DESCRIPTION
**Pull request by ArcEye**
Visual elements and text output related to name changed
to MachineKit. Underlying libs etc unchanged.

Allows invocation with 'machinekit' and that is the name seen
by the user.

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
I initially created a patch, but that seemed to have difficulty dealing with the binary .gif, .png, .xcf files
and did not change them.
Hopefully this will do so.

**Comment by zultron** [comment]
@ArcEye, thanks for doing this!  I hope you did this automatically with e.g. a recursive `sed -i`?  We've been using the non-camel-case `Machinekit` on the website and other places.  D'oh!

**Comment by ArcEye** [comment]
Unfortunately you can only do so much with sed.
There are so many spaghetti code links, especially in the tcl code, you have to be very careful or you break everything.
How do I know!  I started with a brute force sed on the whole repo to see how it shook out!
Everything ran until Axis loaded and it could not load modules from machinekit.so despite it just being the new name for linuxcnc.so

' We've been using the non-camel-case Machinekit on the website and other places. D'oh!'

I have used MachineKit where LinuxCNC was used, all upper for all upper and all lower for lower
That can be changed, but now is the time to decide

**Comment by cdsteinkuehler** [comment]
On 2/18/2015 9:52 AM, ArcEye wrote:
> 
> I have used MachineKit where LinuxCNC was used, all upper for all upper and all lower for lower
> That can be changed, but now is the time to decide

My understanding is it's supposed to be either Machinekit (one upper
case letter) or machinekit (all lower case), with the possible exception
of the logo font (which uses "small caps" for lower case, as seen on
machinekit.io), but I don't this has been expressly written down anywhere.

I think we need something official, like they have in the U-Boot readme:

http://lxr.missinglinkelectronics.com/#uboot+v2012.04/README#L104

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
That is fine if there is consensus.
The rationale behind my capitalisation was largely that machinekit is not a word per se, so I picked out the constituent words, in a similar but not quite analogous way to the separation of Linux and CNC.
I have no strong views on it, but as I said, now is the time to decide, whilst it is simply amended pre commit

**Comment by strahlex** [comment]
Reminds me of http://www.xconomy.com/national/2011/12/22/how-not-to-name-a-startup-the-curse-of-the-camel-case/ 
Machinekit is not a word but a brand name. All lower-case Machinekit makes only sense for comand line applications. Well, companies like facebook or twitter for some reason have small letters in their logo but upper case letters as company name.

Btw. the Machinekit logo is not all upper case that's just the face of the font whe use.

**Comment by ArcEye** [comment]
OK, 3 against 'camel-case' seems to be a concensus.

I have changed 'MachineKit' to 'Machinekit' throughout.

There are huge dangers to trying to change 'MACHINEKIT' to anything else, as it is used throughout in environment variables and ini file section headers, so left that well alone.

The symlink to enable launch from the commandline, remains lowercase 'machinekit'

**Comment by cdsteinkuehler** [comment]
This all sounds great to me!

The use of MACHINEKIT in the ini headers and environment variables fits
with the U-Boot example where you can have different uses for things
like source code variables and defines.

So if we follow the U-Boot folks model, it sounds like we have:

Official name: Machinekit

File names and similar: machinekit

Variables and similar: MACHINEKIT or machinekit

Example:

This is the README file for the Machinekit project.

Custom configurations should be placed in the ~/machinekit directory.

To enable foo, export the MACHINEKIT_FOO environment variable.

Sound good?

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
Sounds fine to me

A Machinekit spokesman said "No dromedaries were harmed during the making of this commit"

**Comment by strahlex** [comment]
Yes sounds good.

cdsteinkuehler writes:

> This all sounds great to me!
>
> The use of MACHINEKIT in the ini headers and environment variables fits
> with the U-Boot example where you can have different uses for things
> like source code variables and defines.
>
> So if we follow the U-Boot folks model, it sounds like we have:
>
> Official name: Machinekit
>
> File names and similar: machinekit
>
> Variables and similar: MACHINEKIT or machinekit
>
> Example:
>
> This is the README file for the Machinekit project.
>
> Custom configurations should be placed in the ~/machinekit directory.
>
> To enable foo, export the MACHINEKIT_FOO environment variable.
>
> Sound good?

-- 
Alexander Rössler

**Comment by ArcEye** [comment]
I am currently checking if I can replace all the instances of hardcoded addresses, i.e.
'~/linuxcnc',  with '~/machinekit', without throwing problems elsewhere.
The biggest problem is with tcl, which does not use the ~/ syntax and creates / regerences the directory through a contorted regex as part of the pickconfig dialog.

**Comment by ArcEye** [comment]
pickconfig.tcl is 866 lines of macro script and bwidget s**t which I am not going to bother with
It would be better to rewrite the config picker in Qt, which is what I will probably do

Commit stands as it is for decision, a replacement config picker and rename of the ~/linuxcnc dir can be a seperate issue

**Comment by cdsteinkuehler** [comment]
On 2/19/2015 9:21 AM, ArcEye wrote:
> pickconfig.tcl is 866 lines of macro script and bwidget s**t which I
> am not going to bother with It would be better to rewrite the config
> picker in Qt, which is what I will probably do
> 
> Commit stands as it is for decision, a replacement config picker and
> rename of the ~/linuxcnc dir can be a seperate issue

I'm in favor of committing what we can and making incremental progress.

It doesn't all need to be done at once, but it would be good if anything
that moves directories around (ie: ~/linuxcnc -> ~/machinekit) is
self-consistent enough it doesn't break everything!  :)

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
pickconfig.tcl  and Qt - doing this rewrite in Qt will make Qt a machinekit build- and runtime dependency for all, which I dont think is a good idea

using gtk will not do this; I will post Drogge's attempt at pickconfig using gtk from a wile back

**Comment by ArcEye** [comment]
OK, I have now found the linuxcnc.tcl file, so the env variable macros make more sense
Will have a look at it with a clear head tomorrow, need to go through the .in file and make substitutions by hand to make sure I don't clobber files that have kept their linuxcnc.??? names

**Comment by strahlex** [comment]
Is pickconfig a necessity? A useful tool but would be a lot better to have remotely too. I would keep a simple cli version with Machinekit and split a remote compatible version as extra package.

**Comment by strahlex** [comment]
On a desktop install both Qt and Gtk should be availabe and when SSHing into a device why not using a simple cli interface.

**Comment by strahlex** [comment]
Thought about this already. Could be another Machinetalk service that provides the configuration and starts configurations. How does this tool currently find configurations? Would be useful to specify a run command for each config to deal with run scripts. This should then be compatible with any UI. The host side is probably a small Python script (like configserver, oh we have a name conflict here). The client side could for example be implemented with QtQuickVcp.

Btw. we should create something like a machine-configuration file where one can specify an image to display in the launcher too (or should add these variables to the INI?)

So in particular:
- A CLI script that searches the config dir for INI files and displays a selection. Using a veriable in the ini it should be possible to specifiy the application to execute (machinekit, run.py, etc).
- The same application may also be startable in a daemon mode where it creates a launcher Machinekit service.
- On a desktop installation it may also start the GUI client if available.

**Comment by ArcEye** [comment]
"Is pickconfig a necessity? A useful tool but would be a lot better to have remotely too. I would keep a simple cli version with Machinekit and split a remote compatible version as extra package."

It is a necessary evil unfortunately.  Without it 80% + of first time users would get no further.
It also needs to be in a language natively available without extra dependencies, Michael is right about that. Just wish that didn't have to include tcl.

"On a desktop install both Qt and Gtk should be availabe "

Unfortunately not, since we nailed our colours to the Qt5 mast, it is not in Wheezy, just qt4

The pickconfig tree implementation is laughable compared to the speed and slickness of QFilesystemModel and QTreeView I started playing with yesterday.

It can be done much better in Qt, but not right now probably.

Hopefully I will have an imperfect interim solution soon.

**Comment by strahlex** [comment]
The language of the GUI client is unimportant. A script that provides
the configurations using Machinetalk would avoid us double or even
triple work. Should be a few hundred lines in Python.

It is similar simple for a client application. Just display the list in
a tree like view and send a run command to the host.

All tree client implementations (CLI, Gtk and Qt) could use the
Machintalk service. Would be a lot easier to maintain than x different
launchers that use their own look-up methods.

ArcEye writes:

> "Is pickconfig a necessity? A useful tool but would be a lot better to have remotely too. I would keep a simple cli version with Machinekit and split a remote compatible version as extra package."
>
> It is a necessary evil unfortunately.  Without it 80% + of first time users would get no further.
> It also needs to be in a language natively available without extra dependencies, Michael is right about that. Just wish that didn't have to include tcl.
>
> "On a desktop install both Qt and Gtk should be availabe "
>
> Unfortunately not, since we nailed our colours to the Qt5 mast, it is not in Wheezy, just qt4
>
> The pickconfig tree implementation is laughable compared to the speed and slickness of QFilesystemModel and QTreeView I started playing with yesterday.
>
> It can be done much better in Qt, but not right now probably.
>
> Hopefully I will have an imperfect interim solution soon.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit/pull/494#issuecomment-75209875

-- 
Alexander Rössler

**Comment by ArcEye** [comment]
OK, pickconfig is working properly now, looking for ~/machinekit/configs and creating ~/.machinekitrc

Just sorting out the right place for scripting the symlinks / new dirs required to finish the rebranding
for both RIPs and /usr installs

Going to have to do a /usr install to check, I only ever use RIPs normally

**Comment by ArcEye** [comment]
And of course this opens a new can of worms.
Going to have to re-write some of the debian postinstall stuff to rebrand the log etc and then add 
necessary symlinks or directory creation
I am going to close this PR and come back when it is done
Good news is that runtests are fine, none of the internal components are renamed so they run
139 out of 139

**Pull request closed without merging**
