### PR TITLE
machinetalk-protobuf: fix package install

### PR DESCRIPTION
**Pull request by strahlex**
Please check before merging!

Possibly fix for https://github.com/machinekit/machinekit/issues/999
How can I build the deb package locally?

### CODE REVIEW

**Comment by strahlex** [comment]
nope, not good enough

**Comment by mhaberler** [comment]
well I already explored that in https://github.com/machinekit/machinekit/pull/1000

as I said in https://github.com/machinekit/machinekit/issues/999#issuecomment-232930234: the issue is with the install targets of the protobuf Submakefile

the 'make install' step has no bearing on debian/machinekit.install so the above patch cannot possibly fix it

any proper fix must contain your change above, and revert https://github.com/machinekit/machinekit/commit/f8598752e000cfb5b989ec41508ffc60cada65d6 because this just hides the underlying problem
plus whatever is needed in src/machinetalk/Submakefile for the install step, probably some TARGER* macro

**Comment by strahlex** [comment]
currently testing with reverts

**Comment by strahlex** [comment]
should work now

**Comment by strahlex** [comment]
doing another test, second line might be unnecessary

**Comment by mhaberler** [comment]
this looks better:

````
mah@jessie64:~/machinekit-patch/src$ find /tmp/install|grep dist-packages/machinetalk
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/firmware_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/types_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/rtapi_message_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/__init__.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/message_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/nanopb_generator.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/test_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/preview_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/value_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/nanopb_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/status_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/canon_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/motcmds_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/config_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/object_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/rtapicommand_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/emcclass_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/task_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/protobuf/log_pb2.py
/tmp/install/usr/lib/python2.7/dist-packages/machinetalk/__init__.py

````

**Comment by mhaberler** [comment]
yes I think the second line can be removed

**Comment by strahlex** [comment]
okay finally, does work for me with the package build

**Comment by mhaberler** [comment]
super!

**Pull request merged**
