### PR TITLE
emcmotcfg.h: set EMCMOT_MAX_DIO as 128, tp.c: remove dio_mask

### PR DESCRIPTION
**Pull request by yishinli**
Increase the DIO limitation from 64 to 128

### CODE REVIEW

**Comment by mhaberler** [comment]
Hi Yishin

sure removal of the mask does not break things? what about the planner code?

**Comment by yishinli** [comment]
For tp.c, the original dio_mask implementation may get a few performance boost only when a few DIO bits were set. However there's no benefit if there was no bits being set, which was masked out by tc->syncdio.anychanged. Moreover, it limited the DIO channels to 64, the size of iomask_t.

In order to support more than 64 bits of DIO, I suggest to remove dio_mask in tp.c.

**Comment by strahlex** [comment]
@yishinli Make sure you do not brake the IO signals. They should only get updated when something has changed.

**Comment by mhaberler** [comment]
sorry to be a PITA..;) would you rebase 7d5ccb7 ontop of master and renew? unsure where the merge commit came in?

**Comment by yishinli** [comment]
Michael, I've rebased the dio_mask modification to [57db8ca](https://github.com/machinekit/machinekit/commit/57db8ca2a66c13e894d74988297e3cb47daf4c76). Please advise if the rebase work is correct.

**Comment by mhaberler** [comment]
Hi Yishin, not quite sure, that looks a bit diverged from master - I know very well it is easy to get entangled in git ;)

since it's only one commit, try this, make a work branch on current master and cherry pick your commit, then push this to github and recreate the PR

In your case you want to do something like so:

````
# get current master history
git fetch machinekit
# this contains your 57db8ca2a66c
git fetch arais
# create 'work' branch off current machinekit/master:
git checkout -b work machinekit/master
# pick your change ontop of 'work'
git cherry-pick 57db8ca2a66c
# push this into your arais repo, it will appear there as work-branch
git push arais work:work-branch  
# now recreate PR against machinekit:master from arais:work-branch
`````

**Pull request closed without merging**
