### PR TITLE
dual thread type support in RT

### PR DESCRIPTION
**Pull request by mhaberler**
halcmd: newthread baz 4000000 posix
halcmd: show thread
Realtime Threads (flavor: posix) :
     Period  FP     Name               (     Time, Max-Time ) flags
    4000000  NO                    baz (        0,        0 ) posix 
    2000000  NO                    bar (        0,        0 ) posix nowait
    1000000  NO                    foo (        0,        0 )

### CODE REVIEW

**Comment by zultron** [comment]
WTF???  Neato!

**Comment by mhaberler** [comment]
glad you appreciate the idea ;) I admit it's kind of a 'duh' thing..

it needs love - the whole logic of thread period verification is meaningless in the posix case, but I'll go for it only if this is verified to work and actually be useful

Philippe was extremely helpful on the Xenomai list - what I took from that discussion:  seems this 'intentional relax' of an RT thread is a generally useful idea for others as well

**Comment by mhaberler** [comment]
hm, that harpoons xenomai-kernel at least, investigating
sorry for the bot mess

**Comment by zultron** [comment]
No problem, MCSE tool #1 applied.

**Comment by mhaberler** [comment]
I've reproduced locally. Will push only after that bug is squashed.

**Comment by mhaberler** [comment]
good chance this comes out green, but dont merge yet - I picked the protobuf change into machinetalk protobuf and will replace that with a subtree merge

**Comment by mhaberler** [comment]
ok, if this one comes out green, it's good to merge

**Comment by mhaberler** [comment]
yee-haw!

**Pull request merged**
