### PR TITLE
Silence warnings take 42

### PR DESCRIPTION
**Pull request by zultron**
This PR fixes the rest of the compiler warnings in Stretch and Jessie, all architectures.  A couple of patches were picked over from LCNC; thanks to @jepler for these non-trivial fixes.

In order to prevent future backslide, `./scripts/build_docker -c deb` sets `-Werror` will now fail upon encountering compiler warnings.  This may be a small surprise to both contributors and Maintainers, but the error is easy to understand:

```
Compiling hal/utils/halcmd_commands.c
hal/utils/halcmd_commands.c: In function ‘print_script_sig_info’:
hal/utils/halcmd_commands.c:2291:2: error: #warning fixme [-Werror=cpp]
 #warning fixme
  ^
cc1: all warnings being treated as errors
Makefile:407: recipe for target 'objects/hal/utils/halcmd_commands.o' failed
make: *** [objects/hal/utils/halcmd_commands.o] Error 1
```

Other changes that snuck in:
- Do a little more cleanup on build output
- Minor fixes to `Makefile` rules
- Minor fix to `scripts/build_docker`

Fixes machinekit/machinekit-cnc#45

### CODE REVIEW

**Comment by zultron** [comment]
Note that issue machinekit/machinekit-hal#162 replaces one of the warnings.

**Comment by zultron** [comment]
It seems Jenkins is out to lunch.

**Comment by ArcEye** [comment]
@zultron 
Sorry setting `-Werror` will not work, it will make Buster and sid unusable.

With gcc 8.x there are intractable warnings, some caused by coding style, all over the project.

This is just a taster of one of them, caused by always allocating buffers and using reference sizes
from #defines such as PATH_MAX.
If you allocate a buffer of size PATH_MAX, 
concatenate characters to what is in the buffer effectively, by a sprintf operation adding to the contents and then restrict the buffer to PATH_MAX when copying it say to prevent overruns,
you are always going to get a warning in gcc > 8.x of both potential overrun from one operation and truncation of data from the other.

There are many more warnings specific to gcc >8.x.

```
rtapi/posix/rtapi_compat.c:396:39: warning: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
   snprintf(kmodule_dir,PATH_MAX,"%s/%s/%s",
                                       ^
rtapi/posix/rtapi_compat.c:396:3: note: ‘snprintf’ output 3 or more bytes (assuming 4162) into a destination of size 4096
   snprintf(kmodule_dir,PATH_MAX,"%s/%s/%s",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     buf, default_flavor()->name, uts.release);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I am out until later and will sit down then and work through the PRs

**Comment by ArcEye** [comment]
Please leave this for now.
I will look later at why no PR builds are taking place
The last 7 github webhook attempts were unable to get through.

**Comment by ArcEye** [comment]
I built this PR locally and made packages in all flavours / architectures so it works.
Jenkins is now back up and PR tests pass.

I will leave the `-Werror` CFLAG in for this merge and then do an additional commit later that tests for the tag number and only adds it for `_8` and `_9`, because it will fail with my `_10` dockers

**Comment by ArcEye** [comment]
Well done @zultron 
I have just watched a stretch package build without a single warning in it, a bit surreal.

I have done a PR to allow warning on `*_10` tags, which works fine. https://github.com/machinekit/machinekit/pull/1427

**Comment by zultron** [comment]
@ArcEye, Of course your concern about `-Werror` on Buster is well-founded, and I'd have addressed it in the same way you did in #1427.  Thanks for the review (and for fixing CI)!

**Pull request merged**
