### PR TITLE
xhc-whb04b-6 pendant HAL component

### PR DESCRIPTION
**Pull request by rubienr**
# xhc-whb04b-6 HAL component

## Hi folks,

I implemented a HAL component for the [xhc-whb04b-6](http://cdxhctech.com/html/eProduct/view_363.html) jog dial, which is the successor of xhc-hb04. The xhc-whb04b-6 is a wireless 6-axis  jog dial.  The component is 99% feature complete and works stable. 
 Since it was a pile of work, I thought this component may be helpful for others. The man page can be found preliminarily [here](https://github.com/rubienr/machinekit-docs/blob/master/docs/man/man1/xhc-whb04b-6.asciidoc) (docs pull request here: https://github.com/machinekit/machinekit-docs/pull/295).

## What works
* all features described in the manual, except of those two that are listed as missing

## What is missing
* the "Lead" labeled position (2nd rotary button): no clue what it means/should do
* CRC check for incoming packets from the device: don't know which CRC method to use ([more technical notes on this cheat sheet](https://github.com/rubienr/machinekit/tree/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6))

If somebody is willing to review, I appreciate feedback!

PS: I also fixed some off-topic issues with the hy_vfd HAL component on the fly while fiddling around with the jog dial (updated and finished documentation, fixed some code issues) - sorry for the mixing up things!

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by ArcEye** [comment]
ok to test

**Comment by ArcEye** [comment]
@rubienr 
Assuming this passes you will need to squash it down to a max of say 10 commits.

There are 24 commits which relate to the `main .md`  and another 24 relating to the `xhc-whb04b-6-layout.md` alone.

That is fine for keeping track during development but unmanageable to merge into a repo.

If you need advice as to best way to do this, just ask.

**Comment by rubienr** [comment]
Created another pull request https://github.com/machinekit/machinekit/pull/1431 for a new suqashed feature branch that has been merged with: `git merge --squash feature-xhc-whb04b-6`.

**Comment by ArcEye** [comment]
I have seen that one thanks, just running it through the PR tester
I will close this one.

**Pull request closed without merging**
