### PR TITLE
Added joint offset hal pins to lineardeltakins

### PR DESCRIPTION
**Pull request by jpmoniz**
There are changes in the gladevcp_tab.ini file that should not be used. Don't know what I should do  without screwing up and adding yet another commit.  Suggestions?

### CODE REVIEW

**Comment by zultron** [comment]
No problem.  Do an interactive rebase on the top two commits:

```
jman@foo:machinekit-test/src$ git rev-parse HEAD  # verify commit sha1 from PR
bebbcb036af51a9ed000726bd89949c6a342dff3
jman@foo:machinekit-test/src$ git log -2  # verify log messages from PR
commit bebbcb036af51a9ed000726bd89949c6a342dff3
Author: jpmoniz <jpmoniz@pmiautomation.com>
Date:   Mon Jan 12 16:06:13 2015 -0500

    Added offsets to inverse kinematics

commit a8172d9950ca781008104006df6494c82ad271c0
Author: jpmoniz <jpmoniz@pmiautomation.com>
Date:   Sat Jan 10 10:58:11 2015 -0500

    Added Hal pins to lineardeltakins  to allow joint offsets for
    Calibration
jman@foo:machinekit-test/src$ git rebase -i HEAD~2 # interactive rebase top 2 commits
```

This will start an `$EDITOR` to `squash` the top commit into its parent:
```
pick a8172d9 Added Hal pins to lineardeltakins  to allow joint offsets for Calibration
squash bebbcb0 Added offsets to inverse kinematics

# Rebase d7434d3..bebbcb0 onto d7434d3
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

The `squash` will fork another `$EDITOR` to edit the resulting commit log; example below; note the first subject line, followed by empty line, followed by the log message body:
```
# This is a combination of 2 commits.
# The first commit's message is:

Added Hal pins to lineardeltakins  to allow joint offsets for
Calibration

# This is the 2nd commit message:

Added offsets to inverse kinematics

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    jpmoniz <jpmoniz@pmiautomation.com>
#
# rebase in progress; onto d7434d3
# You are currently editing a commit while rebasing branch 'asciidoc-test' on 'd7434d3'.
#
# Changes to be committed:
#	modified:   configs/sim/axis/gladevcp/gladevcp_tab.ini
#	modified:   configs/sim/axis/sim_rostock.hal
#	modified:   src/emc/kinematics/lineardeltakins-common.h
#	modified:   src/emc/kinematics/lineardeltakins.c
#	modified:   src/emc/kinematics/lineardeltakins.cc
#
# Untracked files:
#	man/
#
```

The rebase finishes as follows, then check your work:
```
[detached HEAD fa9d879] Added Hal pins to lineardeltakins
 Author: jpmoniz <jpmoniz@pmiautomation.com>
 5 files changed, 69 insertions(+), 67 deletions(-)
Successfully rebased and updated refs/heads/asciidoc-test.
jman@foo:machinekit-test/src$ git log -1   # new combined commit (example log message)
commit fa9d87927e5a56e96ed0f6a5775cf51d9c4ecc31
Author: jpmoniz <jpmoniz@pmiautomation.com>
Date:   Sat Jan 10 10:58:11 2015 -0500

    Added Hal pins to lineardeltakins
    
    - Allow joint offsets for Calibration
    - Added offsets to inverse kinematics
jman@foo:machinekit-test/src$ 
```

**Comment by zultron** [comment]
...and then do a git force push to your github repo, same branch, and the PR will be updated with the new commit & Buildbot will rerun build.

**Comment by jpmoniz** [comment]
Thanks!

**Comment by luminize** [comment]
@jpmoniz did the rework work? Can I merge this PR?

**Comment by luminize** [comment]
@zultron is there an easy way I can see the results of the build after @jpmoniz his commit from 9 days ago?

**Comment by jpmoniz** [comment]
@luminize   As far as I can tell. I tried to check buildbot results but could not find them.  Does build bot run automatically upon submission of a PR?

**Comment by luminize** [comment]
It runs each time a new commit is made.

Since your last commit was some days ago you can trigger it by doing (trick I learned from John):

`git rebase HEAD~ -f`
And after that push
`git push -f`

This will be a new commit from which the buildbot will trigger.

**Comment by jpmoniz** [comment]
@luminize  Did the trick.   My commit on Git webpage still shows 20 Days old. Is buildbot down?  Trying to view grid and page will not load?

**Comment by luminize** [comment]
Possibly some other PR is building. It builds one at a time

**Comment by luminize** [comment]
The build went well. As a last thing, would you mind updating the [manpage for the lineardeltakins](https://github.com/machinekit/machinekit/blob/master/man/man9/lineardeltakins.9) with the descriptions of the working of your pins?

**Comment by zultron** [comment]
On 01/30/2015 04:50 AM, Bas de Bruijn wrote:
> @zultron <https://github.com/zultron> is there an easy way I can see the
> results of the build after @jpmoniz <https://github.com/jpmoniz> his
> commit from 9 days ago?

Sorry Bas, I don't know how to do something so obvious and useful.  :P

There's the ['console' view][1], but I don't see his earlier build in there.

[1]: http://buildbot.dovetail-automata.com/console

	John

**Comment by jpmoniz** [comment]
Of course!!!  As a general rule of thumb. I will wait for the PR to get merged before I update the supporting documentation.JP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: Bas de BruijnSent: Friday, January 30, 2015 12:59 PMTo: machinekit/machinekitReply To: machinekit/machinekitCc: Jean-Paul MonizSubject: Re: [machinekit] Added joint offset hal pins to lineardeltakins (#454)The build went well. As a last thing, would you mind updating the manpage for the lineardeltakins with the descriptions of the working of your pins?

—Reply to this email directly or view it on GitHub.

**Comment by luminize** [comment]
I couldn't find anything about a must of documentation to go with changes in [C4](http://www.machinekit.io/docs/C4/) so nothing to stand in the way of merging :)

**Pull request merged**
