### PR TITLE
A few fixes for TP and state tags

### PR DESCRIPTION
**Pull request by robEllenberg**
This branch has a few improvements for my recent fixes:
* Refactored blend greediness constant
* Fix for rigid tapping return height issue and target function (from linuxcnc 2.7)
* Added check for state tags to prevent restoring state from within remapped code

### CODE REVIEW

**Comment by strahlex** [comment]
For some reason this patch makes lookahead not working anymore for me. Has something changed regarding the lookahead settings?

**Comment by robEllenberg** [comment]
Sorry about that! A recent change of mine broke one of the checks in the
optimizer. Sam / Chris found and fixed it in 2.7, and I have a branch
almost ready to merge that will fix it in machinekit.

Rob

**Comment by strahlex** [comment]
Okay, I use the pr520 packages for now. Do you know anything about a
change in the M66 behavior too? Last Friday it seemed to work more
responsive than today, but could also be that I just haven't noticed
that it doesn't behave exactly like I want. Not sure which PR I had
installed on Friday.

Robert Ellenberg writes:

> Sorry about that! A recent change of mine broke one of the checks in the
> optimizer. Sam / Chris found and fixed it in 2.7, and I have a branch
> almost ready to merge that will fix it in machinekit.
>
> Rob
> On Mar 9, 2015 5:23 AM, "Alexander Rössler" <notifications@github.com>
> wrote:
>
>> For some reason this patch makes lookahead not working anymore for me. Has
>> something changed regarding the lookahead settings?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/machinekit/machinekit/pull/521#issuecomment-77821858>.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit/pull/521#issuecomment-77823507

-- 
Alexander Rössler

**Comment by strahlex** [comment]
@robEllenberg Any progress on the fix?

**Comment by robEllenberg** [comment]
I'm doing a bit of rebasing to pull the latest stuff from 2.7. I should
have a new PR for this today.

On Thu, Mar 12, 2015 at 8:54 AM, Alexander Rössler <notifications@github.com

**Pull request merged**
