### PR TITLE
Replicape configuration updated for Debian Stretch on BeagleBoneBlack…

### PR DESCRIPTION
**Pull request by airborneastro**
… with kernel 4.14.x rt-preempt and Delta printer support
This is an adaptation of an earlier FDM velocity extrusion config for a Replicape board on a BeagleBoneBlack contributed by Sam Wong in 2015 (sam0737/machinekit-replicape) to a more recent Debian Stretch distribution and a kernel 4.14.x with rt-preempt and u-boot overlays. Support for Delta printers and functionality for several M-codes was added, as detailed in the README. This adaptation was tested on a Kossel Mini printer with Replicape board rev B3A.

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by luminize** [comment]
add to whitelist

**Comment by airborneastro** [comment]
hal_temp_bb is only part of the ARM.Replicape.A4A folder which I left unchanged from the earlier version by Sam Wong. Actually, this folder could be deleted completely, because it would work only with earlier distributions and is not needed for this Debian Stretch version.

**Comment by machinekoder** [comment]
@airborneastro If it is not necessary we should remove it.If I understand correctly that's probably https://github.com/machinekit/machinekit/blob/master/src/hal/user_comps/hal_temp_bbb.py

**Comment by airborneastro** [comment]
@machinekoder That is correct. I suggest to remove the ARM.Replicape.A4A folder completely. I left it in originally to make sure I did not violate the copyright of the original version that I updated and enhanced. Do I need to close this PR and open a new one after making the change or can I simply make a new commit to my fork? I am new to this.

**Comment by luminize** [comment]
@airborneastro you can make a new commit to your branch. Then when you push your local branch to your GH repo the commit will show up here.

**Comment by luminize** [comment]
Thanks @airborneastro

**Comment by airborneastro** [comment]
Thanks @ArcEye, @luminize, @machinekoder for your help with this PR, I learned a lot.

**Pull request merged**
