### PR TITLE
Cramps config

### PR DESCRIPTION
**Pull request by omija1**

### CODE REVIEW

**Comment by cdsteinkuehler** [comment]
Any particular reason you are trying to pull configurations for my
personal machines into the main repository?

The CRAMPS config (and various others) could stand to be updated to
use the latest HAL features (like building the HAL setup with python
instead of a HAL file, examples using machinetalk for the UI, etc),
but I'm not sure what good will come from pulling in my working but
fairly dated configurations.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by omija1** [comment]
Dear Charles,

I am trying to use CRAMPS on BBB with linuxcnc to control my 5 axis mill.
And can not find a manual or help file for the CRAMPS board.

It's why I cloned the whole repository tree and try to find where I can get the right information.

Any suggestion?

with best regards.

Yours Alex



logicalmetal
 
From: cdsteinkuehler
Date: 2016-08-23 01:41
To: machinekit/machinekit
CC: omija1; Author
Subject: Re: [machinekit/machinekit] Cramps config (#1046)
Any particular reason you are trying to pull configurations for my
personal machines into the main repository?

The CRAMPS config (and various others) could stand to be updated to
use the latest HAL features (like building the HAL setup with python
instead of a HAL file, examples using machinetalk for the UI, etc),
but I'm not sure what good will come from pulling in my working but
fairly dated configurations.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by cdsteinkuehler** [comment]
On 8/22/2016 8:47 PM, omija1 wrote:
> Dear Charles,
> 
> I am trying to use CRAMPS on BBB with linuxcnc to control my 5 axis mill.
> And can not find a manual or help file for the CRAMPS board.

There is no manual for the CRAMPS board, but the design files are all
online.  What documentation is available is generally collected on the
RepRap wiki:

http://reprap.org/wiki/CRAMPS

> It's why I cloned the whole repository tree and try to find where I can get the 
> right information.
> 
> Any suggestion?

Ask for help using questions as specific as possible on the Machinekit
list/Google-group.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by luminize** [comment]
If anyone disagrees, please re-open

**Pull request closed without merging**
