### PR TITLE
M30 remap interaction

### PR DESCRIPTION
**Pull request by zultron**
M30 or M02 combined in a block with a remapped code triggers the error 'BUG: remap_level < 0 : -1'.

M02 and M30 take care of resetting the interpreter call and remap levels.  When a remapped code is in the same block, the usual call to `leave_remap()` at the end of the block's execution should be skipped.

### CODE REVIEW

**Comment by mhaberler** [comment]
good catch!

**Comment by dkhughes** [comment]
Shouldn't this be caught as an error in the parser? M2 and M30 on the same line is illegal syntax in all of the mills/lathes that I run regularly. I know (and really like actually) that the g code interpreter deviates from standards in places, I'm mostly curious about the use case for allowing a rewind and a program stop on the same line.

**Comment by zultron** [comment]
Hrm.  The build job [`TAG=jessie-64 CMD=run_tests`][1] failed during the `/usr/src/machinekit/tests/threads.0` test.  All others passed.  The error message:

```
line 1565: got 0, expected 9 or 1
*** /usr/src/machinekit/tests/threads.0: FAIL: checkresult exited with 1
```

It looks like this problem is unrelated to this PR, and it's safe to merge.

******
The TravisCI error is not helpful:

```
The log length has exceeded the limit of 4 MB \
    (this usually means that the test suite is raising \
    the same exception over and over).

The job has been terminated
```

Investigation shows 86k+ lines in the log, compared to 65k from the [same test][2] for PR #1015.  The extra log length comes from a `cat /var/log/linuxcnc.log` (truncated) following the error.  I wonder if there's a way to make these logs accessible other than through the TravisCI web UI?

[1]: https://travis-ci.org/machinekit/machinekit/jobs/149278816
[2]: https://travis-ci.org/machinekit/machinekit/jobs/149176324

**Comment by zultron** [comment]
@dkhughes, M2 and M30 in the same block is and should be illegal, yes.

I updated the original description to read "M30 **or** M02 combined in a block with a remapped code triggers the error 'BUG: remap_level < 0 : -1'."  Maybe that's more clear.

The block that first triggered the error for me was `T0 M06 M02`, where M6 was remapped.

**Comment by dkhughes** [comment]
@zultron Ah, okay, that does help. Neat feature that you can do that, as all of the controls I interact with regularly will barf with multiple M codes in a single block.

**Comment by ArcEye** [comment]
> Shouldn't this be caught as an error in the parser? M2 and M30 on the same line is illegal syntax in all of the mills/lathes that I run regularly.

The bigger problem with M2 and M30, is that they both do the same thing.

On most CNC systems I have used, M30 will rewind without removing tool comp. etc. 
But on Linuxcnc (and now Machinekit), they will:

*   Change from Auto mode to MDI mode.
*   Origin offsets are set to the default (like G54).
*   Selected plane is set to XY plane (like G17).
*    Distance mode is set to absolute mode (like G90).
*    Feed rate mode is set to units per minute (like G94).
*    Feed and speed overrides are set to ON (like M48).
*    Cutter compensation is turned off (like G40).
*    The spindle is stopped (like M5).
*    The current motion mode is set to feed (like G1).
*    Coolant is turned off (like M9).

On ngcgui for instance, this caused so many problems, the code blocks are often delimited with `%` to prevent this.

**Comment by dkhughes** [comment]
@ArcEye We could create an issue to discuss that behavior more in depth. It seems very counterintuitive that a modal is changed by end of program. Setting MCodes back to their defaults (spindle off, coolant off, etc.) is pretty common when hitting the M30 or M02 I think, and I don't see any penalty there since M code controlled outputs off *should* be a safe machine state by design.

**Comment by zultron** [comment]
The `TAG=jessie-64 CMD=run_tests` re-ran fine, and all tests pass.  Thanks!

**Comment by ArcEye** [comment]
>  @ArcEye We could create an issue to discuss that behavior more in depth.

It has been discussed to death in Linuxcnc, that just resulted in clearer warnings of what using either code does and Dewey Garrett shifting to `%` delimited code blocks inside ngcgui.

Unless someone has the appetite for a wholesale rewrite, everyone will just continue as they are at present.

I personally never use M30 and just use M2 to terminate programs.
Then you get what you and anyone else reading the code expects.

**Comment by zultron** [comment]
Thanks for the merge.

FWIW, it looks like the only difference between M02 and M30 is the latter calls a `PALLET_SHUTTLE()`.  See [`interp::convert_stop()`][1].

[1]: https://github.com/machinekit/machinekit/blob/master/src/emc/rs274ngc/interp_convert.cc#L4396-L4397

**Pull request merged**
