### PR TITLE
Deprecate send container string dest

### PR DESCRIPTION
**Pull request by mhaberler**
originally all string socket identity was assumed on the client side - this is not a robust assumption;
zeroMQ default is to autogenerate a binary blob for identity

the string-based API was partially removed by @strahlex a while ago; this completes it for the sending side

@strahlex - can I ask you for a review, in particular pbutil.cc:send_container and the FAST define - I think this is equivalent but quicker than the current code

pls do not merge yet

### CODE REVIEW

**Comment by zhivko** [comment]
I think this is right place to add stack trace:

```
(gdb) continue
Continuing.

Program received signal SIGSEGV, Segmentation fault.
halpr_describe_funct (funct=0xb6790e08, pbfunct=0xea0e8) at hal/lib/halpb.cc:97
97        pbfunct->set_runtime(*(funct->runtime));
(gdb) backtrace
#0  halpr_describe_funct (funct=0xb6790e08, pbfunct=0xea0e8) at hal/lib/halpb.cc:97
#1  0x0000fe26 in describe_funct_cb (funct=0xb6790e08, arg=0xbeff25d8)
    at machinetalk/haltalk/haltalk_introspect.cc:129
#2  0xb6dc546c in halpr_foreach_funct (name=0x0, 
    callback=0xfde1 <describe_funct_cb(hal_funct_t*, void*)>, cb_data=0xbeff25d8)
    at hal/lib/hal_iter.c:155
#3  0x0000ff42 in process_describe (self=0xbeff25d8, from=0x2fbf0, socket=0x32f80)
    at machinetalk/haltalk/haltalk_introspect.cc:44
#4  0x0000eff4 in dispatch_request (socket=0x32f80, from=0x2fbf0, self=0xbeff25d8)
    at machinetalk/haltalk/haltalk_command.cc:481
#5  handle_command_input (loop=<optimized out>, poller=<optimized out>, arg=0xbeff25d8)
    at machinetalk/haltalk/haltalk_command.cc:60
#6  0xb6c2ce50 in zloop_start () from /usr/lib/arm-linux-gnueabihf/libczmq.so.1
#7  0x0000b980 in mainloop (self=0xbeff25d8) at machinetalk/haltalk/haltalk_main.cc:113
#8  main (argc=3, argv=<optimized out>) at machinetalk/haltalk/haltalk_main.cc:467
```

**Comment by zhivko** [comment]
linuxcnc log
[linuxcnc.log.txt](https://github.com/machinekit/machinekit/files/318976/linuxcnc.log.txt)

**Comment by strahlex** [comment]
Socket identity is per default a UUID generated by ZeroMQ. Furthermore, multiple identities are added to messages in case the message was sent over a broker. The patch was indented to fix this problem.

I will take a look at the commit.

**Comment by mhaberler** [comment]
@strahlex ping?

**Comment by strahlex** [comment]
back

**Comment by mhaberler** [comment]
good to hear you are back ;) does this branch work for you - and if so: could you merge it?

**Comment by luminize** [comment]
@mhaberler I have no way of reviewing, want me to merge?

**Comment by luminize** [comment]
@machinekoder @mhaberler what to do with this PR, Alex, can you look at this and decide?

**Comment by luminize** [comment]
4 months inactivity. @machinekoder what must he done?

**Comment by machinekoder** [comment]
@luminize We need to port an review this patch to the current master.

**Comment by luminize** [comment]
Sorry, i have no idea what this is about :)

**Comment by machinekoder** [comment]
continued in https://github.com/machinekit/machinekit/pull/1201

**Pull request closed without merging**
