### PR TITLE
Cosmetic rebranding to Machinekit from Linuxcnc

### PR DESCRIPTION
**Pull request by ArcEye**
Graphics and text changes to show Machinekit running
Symlinks to original user dirs and new ones created if not present
Text changes to configs etc

Changes just skin deep, underlying libs, logs etc same

Signed-off-by: Mick Grant <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by cdsteinkuehler** [comment]
Buildbot fails building packages.  It looks like the relevant snippet from one of the build logs is:

```
install -m 0755 -o root ../scripts/linuxcnc /var/lib/buildslave/d7-bb-bldtest/build/source/machinekit-0.1.1014/src/../debian/tmp/usr/bin
install -m 0755 -o root ../scripts/machinekit /var/lib/buildslave/d7-bb-bldtest/build/source/machinekit-0.1.1014/src/../debian/tmp/usr/bin
install: cannot stat `../scripts/machinekit': No such file or directory
make[1]: *** [install-kernel-indep] Error 1
```

**Comment by ArcEye** [comment]
OK, That was the bit I could not test because the debian build failed for bizarre reasons.
The missing file is just a symlink, which should be created by the postinst script.
I will look at it again a bit later

**Comment by adbensi** [comment]
Did you have screen shots? Best regards
Em 26/02/2015 09:26, "ArcEye" <notifications@github.com> escreveu:

**Comment by ArcEye** [comment]
Yeah, just quick ones
Same grapics that Charles and Alex made
Startup to pickconfig
chooser
Splash
launch
Running
running
regards

**Comment by ArcEye** [comment]
Charles

Commit amended so that the buildbot has something to copy over.
The previous setup worked fine with RIP and /usr builds and the completed package should have created the machinekit link as part of the postinst, but that left the hole in the middle I could not test properly, making the package itself.
Now a script called machinekit in /scripts which just calls linuxcnc, so all possibilities covered hopefully

regards

Mick

**Comment by adbensi** [comment]
Very nice! Machinekit logo too, amazing,
Congratulations!
Em 28/02/2015 08:50, "ArcEye" <notifications@github.com> escreveu:

**Comment by strahlex** [comment]
Nice.

ArcEye writes:

> Yeah, just quick ones
> Same grapics that Charles and Alex made
> Startup to pickconfig
> chooser
> Splash
> launch
> Running
> running
> regards
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit/pull/507#issuecomment-76522946

-- 
Alexander Rössler

**Comment by cdsteinkuehler** [comment]
Looks like the added script name has a typo.  I've emailed ArcEye to update the PR since I don't currently know how to update a PR I didn't initiate.

**Comment by ArcEye** [comment]
Hopefully will build on the buildbot now, stupid typo amended :(

**Comment by cdsteinkuehler** [comment]
Buildbot failed again, but it doesn't look like the PR has changed.  How did you push the update?
I don't see a new commit, and the most recent commit above still has the typo in the machinekit script name: https://github.com/ArcEye/machinekit/commit/947717e615acafd7fc8aa8d2bffa9e17773b814e

**Comment by ArcEye** [comment]
https://github.com/ArcEye/machinekit/commit/947717e615acafd7fc8aa8d2bffa9e17773b814e#commitcomment-10172865
clearly shows the filename correctly spelt and the contents as required

I don't know why the PR is not updating, I will just have to close this PR and open a new one and hope it works properly

**Comment by ArcEye** [comment]
OK, mea culpa

I have been altering the file the buildbot originally fell over on bin/machinekit
You have been talking about scripts/machinekit

They are the same file in 2 different places to try to cater for many ways of building and installing, to have a command 'machinekit' that can be invoked.

Hopefully now all sorted
Thanks for your patience - how I love git:)

**Comment by ArcEye** [comment]
It is not letting me re-open, so new PR coming up

**Pull request closed without merging**
