### PR TITLE
docs: Added lineardeltakins.JNoff pins & Descriptions

### PR DESCRIPTION
**Pull request by jpmoniz**

### CODE REVIEW

**Comment by luminize** [comment]
@jpmoniz Seems that you have a very "old" version of Machinekit. The docs have recently got a big rework and are in another location now. Because of that this PR cannot be automatically merged, can you pull the latest and rebase?

**Comment by jpmoniz** [comment]
Sorry! Should of known with the change in directory structure. Re-base complete.

**Comment by luminize** [comment]
@zultron we have a problem that is think is buildbot related. All builds, except [this message about setting a property](http://buildbot.dovetail-automata.com/builders/ant/builds/937)

**Comment by zultron** [comment]
@luminize:  Thanks for pointing it out.  Faulty assumption in one of my GitHub-API-scraping scripts should be fixed.

I re-poked the failed merge to master.  The two PR failures can be treated as a pass, since the actual builds and tests passed.

**Comment by luminize** [comment]
@jpmoniz thanks for the update

**Comment by luminize** [comment]
@zultron thanks for the heads-up

**Pull request merged**
