### PR TITLE
Add hy_vfd to Machinekit repo

### PR DESCRIPTION
**Pull request by ArcEye**
A user space component for controlling a huanyang spindle inverter with machinekit.

Component originally written by S Alford and published at
http://www.cnczone.com/forums/phase-converters/91847-huanyang-vfd-rs485-modbus-3.html#post704008

Changes were contributed to fix problems with the rebranding of emc2 to linuxcnc.
These were contributed by alan_3301, also on the cnczone forum.

Seb Kuzminsky <https://github.com/SebKuzminsky> added the code to the Linuxcnc repo and made
numerous changes, edits and bugfixes including:

Creating a Submakefile so as to build within the source tree
Ensuring clean shutdown
Fixed frequency calculation
Improved comms error handling
Read retry if initial one fails
Added spindle speed pins
Enabled setting params from command line
Fixed partial reads bug

Brian Hicks <hicksbr@gmail.com>:
Fixed spindle_at_speed when running in reverse

https://github.com/LinuxCNC/linuxcnc/tree/master/src/hal/user_comps/huanyang-vfd

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
I originally tried to do this via a merge strategy.
However the repos are sufficiently diverged for this to be very problematic.
Figured that as long as everyone is credited, does not need the full Linuxcnc commit history.

**Comment by luminize** [comment]
Or maybe a link to the current Linuxcnc commit shows the history?

**Comment by ArcEye** [comment]
OK, added a link.

The problem was there are 37 commits in the history for the folder, the first of which was moving it from the 'wrong place', in a form in which it would not have built and didn't exist in our repo anyway.

Looks like someone dropped the standalone original version into the repo and then Seb had to sort it out into a form that made sense in the source tree and corrected some errors along the way.

**Comment by ArcEye** [comment]
@JanKlopper 
Are you interested in adding this to the repo, or is it a private solution?
Looks like the configs would not be interchangeable, but would be a `lite` version of the same.

I really don't know how many people besides yourself and Otto use this vfd, especially with a BBB.

**Pull request merged**
