### PR TITLE
Hal lib fix

### PR DESCRIPTION
**Pull request by mhaberler**
this carries over two extensions from git.linuxcnc.org which I found useful

### CODE REVIEW

**Comment by mhaberler** [comment]
bbot passed.

**Comment by the-snowwhite** [comment]
Hmmm Is bbot down ?
I lost contact to:
http://buildbot.dovetail-automata.com/grid
a few hours ago
And doing apt-get update on my BBB now returns:
---
Fetched 14 B in 11s (1 B/s)
Reading package lists... Done
W: Failed to fetch 
http://deb.dovetail-automata.com/dists/wheezy/Release.gpg  Could not 
connect to deb.dovetail-automata.com:80 (188.226.207.175). - connect 
(111: Connection refused)

W: Some index files failed to download. They have been ignored, or old 
ones used instead.
---

Otherwise my internet connection is working fine.

**Comment by mhaberler** [comment]
I guess that comment better goes to the mailing list, or John Morris directly, and it has nothing to do with this PR

**Comment by the-snowwhite** [comment]
Ok

**Pull request merged**
