### PR TITLE
final PR on the instantiable branch

### PR DESCRIPTION
**Pull request by mhaberler**
runtests fine on all of my platforms
@zultron I guess the buildbot needs a kick

### CODE REVIEW

**Comment by zultron** [comment]
@mhaberler, Buildbot kicked.  But:

Not sure why the BBB tests fail.  They're taking over 30 minutes and get killed.  I can't tell if they're hanging or if they're taking longer than in the past.  Will rebuild older PR to test....

http://buildbot.dovetail-automata.com/builders/d7-bb-x-tst/builds/492/steps/runtests/logs/stdio

**Comment by zultron** [comment]
Watching this build:  http://buildbot.dovetail-automata.com/builders/ant/builds/1123

**Comment by mhaberler** [comment]
yes, it's now 155 runtests - Mick has duplicated the component tests under tests/i_components

see my goodwill at nosetests/unittest_instbindings.py - not that those are much faster..

**Comment by zultron** [comment]
Ok, that's a great reason for tests taking longer!

Bumped the timeout to 45 minutes.  Also introduced a new error & then backed it out, so an additional rebuild will be required, sorry.  :-/

**Comment by mhaberler** [comment]
we have one test failure left, this silly multiclick timing-dependent 'measurement', and it works fine on my atom/rtai 3.8 as well as amd64/rtai 3.8.

I'm disabling this test.

**Comment by mhaberler** [comment]
all green.

**Comment by ArcEye** [comment]
Excellent - just pulled, built and runs fine. 
All the runtests work on my amd64-i7 too, but then they would, that's what I wrote them on;)

Tested it runs the icomp-demo-sim, which uses all available instantiable versions of the components

That missed the cut, still sitting as a PR on your icomp-rc3 branch.  I will redo it as a PR to the main Machinekit repo a bit later and submit direct.

Reading the hal file probably explains as much as you need, to be able to use the components in a basic way.

**Comment by mhaberler** [comment]
> Am 12.04.2015 um 11:13 schrieb ArcEye <notifications@github.com>:
> 
> Excellent - just pulled, built and runs fine. 
> All the runtests work on my amd64-i7 too, but then they would, that's what I wrote them on;)
> 
> Tested it runs the icomp-demo-sim, which uses all available instantiable versions of the components
> 
> That missed the cut, still sitting as a PR on your icomp-rc3 branch. I will redo it as a PR to the main Machinekit repo a bit later and submit direct.
> 


ah sorry, will merge it asap

**Pull request merged**
