### PR TITLE
Fanuc-style m98/m99 subroutines

### PR DESCRIPTION
**Pull request by zultron**
## Implementation

In essence, `M98` and `M99` are O-words.  O-words are handled
specially compared to M- and G-words, both when being read
(e.g. parsed earlier in interp loop than other codes) and when being
executed (e.g. own translation unit with functions for searching and
seeking across g-code file blocks).  Therefore, they are implemented
next to other O-word code, and as much as possible they share the same
read and execute flow.

`M98 P1` is mostly similar to `O1 call`, and they share the
`Interp::execute_call()` function.  When `M98` is followed by an
L-word (repeat count), it maintains a loop counter in the parent
context `m98_loop_counter` field, and special logic in
`execute_call()` manages call return block location for iteration.

Other minor changes are spread around `interp_read.cc`,
`rs274ngc_pre.cc` and related header files, some requiring distributed
coordination.  To carry this state, new values are established for the
`context_struct` and `block_struct` fields, `call_type` and `o_type`.

## Fanuc compatibility

No changes to existing rs274ngc-style G-code compatibility are made.
The Fanuc compatibility specifics:

- `O....` == `O.... sub`
  - Online examples show the bare `O....` marking the start of a
    subroutine called from `M98`
- `M99` == `O.... endsub`, except params are not restored (*)
- `M98 P....` == `O.... call`, with differences:
  - `M98` passes params `#1` to `#30` into sub context (*)
  - Params may not be passed in the `M98` block, unlike O-word call
    (e.g. `O.... call [...] [...]`)
  - `M98` calls have no return value
  - `M98 P.... L2` == `O... repeat [2]`, `O.... call`, `O... endrepeat`
  - The `OWORD_N_ARGS` feature will not work
- Subroutines may follow main program
  - (After a bugfix, there is no difference with rs274ngc-style
    G-code.)
- Fanuc-style subroutines my be disabled by placing
  `ENABLE_FANUC_STYLE_SUB = false` in the `[RS274NGC]`
  section of the `.ini` file.

## * Subroutines

O-word calls pass local parameters `#1` to `#30` in the O-word block,
and parameter scope is limited to the subroutine, e.g. the value of
param`#10` defined in the main program will not be visible in the
scope of the sub.

By contrast, Fanuc parameters always have global scope, including
numbers `#1` to `#30`, are global.  Setting low-numbered parameters
(`#1 = 30`) in blocks previos to the M98 call.

## Fanuc and rs274ngc sub call coexistence

Fanuc and rs274ngc sub block syntax styles are easily and
unambiguously differentiated in all three block types.  However,
`O...`, `M99`, `M98` each needed additional somewhat inelegant
handling in `interp_read.cc` `Interp::_read()` to graft in syntax
parsing.

Though the syntax differences create no parsing ambiguities, during
conversion the two styles share nearly the same code paths, with
differences switchable by the detected O-word or call style.  The
major addition to conversion is a section of code turned on for `M98`
in `Interp::execute_call()` that does most of the parameter
processing, `M98 L` loop logic, etc.

Additional checks ban mixing rs274ngc and Fanuc sub blocks within one
call/return cycle.  They are meant to reduce confusion arising from
careless mixing and the unintended side-effects of style differences.

If there is reason to disable Fanuc subroutines, this may be accomplished
by placing `ENABLE_FANUC_STYLE_SUB = false` in the `[RS274NGC]`
section of the `.ini` file.

### CODE REVIEW

**Comment by luminize** [comment]
@zultron we got a merge conflict that must be resolved

**Comment by zultron** [comment]
Yes, this is expected.  I'll clean this up soon & submit a PR here and at the docs repo.

**Comment by luminize** [comment]
Ok, thought it was something i did :)
All in due time

**Comment by abc838** [comment]
发那克

**Comment by luminize** [comment]
No activity, so I'll close this one.
please re-open when needed.

**Pull request closed without merging**
