### PR TITLE
adding FDM library and configs

### PR DESCRIPTION
**Pull request by machinekoder**
Adds the Python `fdm.config` library and sample configurations.

### CODE REVIEW

**Comment by machinekoder** [comment]
Not sure if we should pull configurations into the Machinekit repository. However, I think there should be some examples on how to use the FDM core. This library helps to make the configuration of 3D printers a lot easier.

**Comment by cdsteinkuehler** [comment]
On 9/12/2016 3:11 PM, Alexander Rössler wrote:
> Not sure if we should pull configurations into the Machinekit repository. 
> However, I think there should be some examples on how to use the FDM core. This 
> library helps to make the configuration of 3D printers a lot easier.

I think having example configurations is extremely important,
especially with the new FDM and Python HAL stuff you've setup.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by machinekoder** [comment]
@cdsteinkuehler Can you take a look the rest? We should merge to this make the life for newcomers easier.

**Comment by cdsteinkuehler** [comment]
Looks great!
Thanks for the new python based configs...I'll see if I can migrate my MendelMax over to Python using your example.

**Pull request merged**
