### PR TITLE
Use boolean values and tests for hal_bit_t data types

### PR DESCRIPTION
**Pull request by ArcEye**
Further to Issue #635
and Fix unsafe type usages - Issue #663 & use of params - Issue #610

hal_bit_t variables in components will only ever hold 0 or 1 and thus are
boolean values
Readability of components will be improved if treated as such

instcomp defines true and false to ensure they are valid for that component
and undefs TRUE and FALSE, which are not valid C defines

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by strahlex** [comment]
buildbot fails, there is a `TRUE` left in the match8 component

**Comment by ArcEye** [comment]
Bugger!
I built the wrong repo to test it, symlink still pointing to the old one.

Found another not in the commit whilst checking this one, leave it for now and I will
look again tomorrow.

**Comment by ArcEye** [comment]
Built the correct repo this time and 140 / 140 runtests passed

Found a few more float initialisations to 0 instead of 0.0 along the way in addition to the boolean conversions.

**Comment by strahlex** [comment]
d64 runtests failed, not sure if this is buildbot related

**Comment by ArcEye** [comment]
What is d64?

**Comment by strahlex** [comment]
Debian 64

**Comment by ArcEye** [comment]
OK, I have found it on the buildbot grid.

It is actually d7-64, which I assume is Wheezy, d8-64 is OK.
I built and tested on Jessie amd64, which would be d8-64 I guess.

I will switch to a Wheezy partition, clone my repo and build it and see what happens.
Hard to see what the difference could be, but I'll try it.

**Comment by ArcEye** [comment]
This is the error and it is nothing to do with the components
```
pushd /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/tests/interp/subroutine-return
+ exitcode=0
+ '[' 1 -eq 1 ']'
+ runtests -l bash -x test.sh
+ cp -f orig.ngc test.ngc
+ cp -f subs/orig-sub.ngc subs/sub.ngc
+ linuxcnc -r interp.ini
Machine configuration file is 'interp.ini'
Starting Machinekit...
Jun 30 06:50:45 msgd:0: startup pid=5280 flavor=posix rtlevel=5 usrlevel=5 halsize=524288 shm=Posix gcc=4.7.2 version=git not installed at configure time
Jun 30 06:50:45 msgd:0: ØMQ=4.0.4 czmq=2.2.0 protobuf=2.4.1
Jun 30 06:50:45 msgd:0: configured: sha=git not installed or executable
Jun 30 06:50:45 msgd:0: built:      Jun 30 2015 11:42:06 sha=git not installed or executable
Jun 30 06:50:45 msgd:0: register_stuff: actual hostname as announced by avahi='d7-64-rtpreempt.local'
Jun 30 06:50:45 msgd:0: zeroconf: registering: 'Log service on d7-64-rtpreempt.local pid 5280'
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user rtapi:0: cannot create core dumps - /proc/sys/fs/suid_dumpable contains 0
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user you might have to run 'echo 1 > /proc/sys/fs/suid_dumpable' as root to enable rtapi_app core dumps
Jun 30 06:50:45 msgd:0: rtapi:5287:rt RTAPI:0  posix git not installed at configure time init
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user rtapi: loaded from rtapi.so
Jun 30 06:50:45 msgd:0: rtapi:5287:rt rtapi_app_main:196 HAL: initializing RT hal_lib support
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt hal_xinit:68 HAL: initializing component 'hal_lib' type=4 arg1=0 arg2=0/0x0
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt RTAPI: initing module HAL_hal_lib
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt RTAPI: module 'HAL_hal_lib' loaded, ID: 32769
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt hal_export_xfunctfv:70 HAL: exporting function 'newinst' type 2
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt hal_export_xfunctfv:70 HAL: exporting function 'delinst' type 2
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt hal_xinit:239 HAL: hal_lib initialization complete
Jun 30 06:50:45 msgd:0: hal_lib:5287:rt rtapi_app_main:200 HAL: RT hal_lib support initialized rc=0
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user hal_lib: loaded from hal_lib.so
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user accepting commands at ipc:///tmp/0.rtapi.a42c8c6b-4025-4f83-ba28-dad21114744a
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user rtapi_app:0 ready flavor=posix gcc=4.7.2 git=git not installed at configure time
io started
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user pid=5287 flavor=posix gcc=4.7.2 git=git not installed at configure time
Jun 30 06:50:45 msgd:0: ulapi:5288:user hal_xinit:239 HAL: hal_lib5288 initialization complete
Jun 30 06:50:45 msgd:0: hal_lib:5288:user hal_xinit:246 HAL: legacy component 'halcmd5288' id=69 initialized
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user pid=5287 flavor=posix gcc=4.7.2 git=git not installed at configure time
Jun 30 06:50:45 msgd:0: hal_lib:5288:user hal_exit:258 HAL: removing component 69
Jun 30 06:50:45 msgd:0: hal_lib:5288:user hal_exit:258 HAL: removing component 68
Jun 30 06:50:45 msgd:0: hal_lib:5288:user ULAPI:0 git not installed at configure time exit
<commandline>:0: Component 'iocontrol' ready
<commandline>:0: Program 'io' started
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user pid=5287 flavor=posix gcc=4.7.2 git=git not installed at configure time
Jun 30 06:50:45 msgd:0: ulapi:5293:user hal_xinit:239 HAL: hal_lib5293 initialization complete
Jun 30 06:50:45 msgd:0: hal_lib:5293:user hal_xinit:246 HAL: legacy component 'halcmd5293' id=71 initialized
Jun 30 06:50:45 msgd:0: hal_lib:5296:user io 
Jun 30 06:50:45 msgd:0: hal_lib:5296:user -ini 
Jun 30 06:50:45 msgd:0: hal_lib:5296:user /tmp/tmp.lEugcGvZ5m 
Jun 30 06:50:45 msgd:0: hal_lib:5296:user 
Jun 30 06:50:45 msgd:0: ulapi:5296:user hal_xinit:239 HAL: hal_lib5296 initialization complete
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_xinit:246 HAL: legacy component 'iocontrol' id=73 initialized
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.user-enable-out'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.user-request-enable'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.coolant-flood'
libnml/os_intf/_shm.c 209: halcmd loadusr io started
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.coolant-mist'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.lube'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-prepare'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-number'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-prep-number'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-prep-pocket'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-prepared'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-change'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.tool-changed'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.emc-enable-in'
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_pin_new:121 HAL: creating pin 'iocontrol.0.lube_level'
shmget(1004(0x3EC),1024,0) failed: (errno = 2): No such file or directory
libnml/os_intf/_shm.c 228: No shared memory buffer exists for this key and the IPC_CREAT was not given.
libnml/os_intf/_shm.c 416: rcs_shm_nattch: shmctl failed: Invalid argument
libnml/cms/cms_cfg.cc 916: cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occured during SHMEM create.
Jun 30 06:50:45 msgd:0: hal_lib:5296:user iocontrol: machine: 'unknown'  version 'unknown'
Jun 30 06:50:45 msgd:0: hal_lib:5293:user hal_exit:258 HAL: removing component 71
Jun 30 06:50:45 msgd:0: hal_lib:5293:user hal_exit:258 HAL: removing component 70
Jun 30 06:50:45 msgd:0: hal_lib:5293:user ULAPI:0 git not installed at configure time exit
libnml/nml/nml.cc 368: NML: cms_config returned -1.

**********************************************************
* Current Directory = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/tests/interp/subroutine-return
* 
**********************************************************
* BufferName = toolCmd
* BufferType = 0
* ProcessName = tool
* Configuration File = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
* CMS Status = -4 (CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.)
* Recent errors repeated:
cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occ
NML: cms_config returned -1.

No shared memory buffer exists for this key and the IPC_CREAT was not given.

rcs_shm_nattch: shmctl failed: Invalid argument

* BufferLine: B toolCmd               SHMEM   localhost       1024    0       0       4       16 1004 TCP=5005 xdr
* ProcessLine: P tool          toolCmd         LOCAL   localhost       R       0       1.0     0       3
* Config File = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
* error_type = 0 (NML_NO_ERROR)
************************************************************

libnml/os_intf/_shm.c 209: shmget(1005(0x3ED),8192,0) failed: (errno = 2): No such file or directory
libnml/os_intf/_shm.c 228: No shared memory buffer exists for this key and the IPC_CREAT was not given.
libnml/os_intf/_shm.c 416: rcs_shm_nattch: shmctl failed: Invalid argument
libnml/cms/cms_cfg.cc 916: cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occured during SHMEM create.
libnml/nml/nml.cc 368: NML: cms_config returned -1.

**********************************************************
* BufferName = toolSts
* BufferType = 0
* ProcessName = tool
* Configuration File = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
* CMS Status = -4 (CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.)
* Recent errors repeated:
rcs_shm_nattch: shmctl failed: Invalid argument

cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occ
NML: cms_config returned -1.

No shared memory buffer exists for this key and the IPC_CREAT was not given.

* BufferLine: B toolSts               SHMEM   localhost       8192    0       0       5       16 1005 TCP=5005 xdr
* ProcessLine: P tool          toolSts         LOCAL   localhost       W       0       1.0     0       3
* Config File = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
* error_type = 0 (NML_NO_ERROR)
************************************************************

libnml/os_intf/_shm.c 209: shmget(1003(0x3EB),8192,0) failed: (errno = 2): No such file or directory
libnml/os_intf/_shm.c 228: No shared memory buffer exists for this key and the IPC_CREAT was not given.
libnml/os_intf/_shm.c 416: rcs_shm_nattch: shmctl failed: Invalid argument
libnml/cms/cms_cfg.cc 916: cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occured during SHMEM create.

**********************************************************
* BufferName = emcError
* BufferType = 0
* ProcessName = tool
* Configuration File = /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
* CMS Status = -4 (CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.)
* Recent errors repeated:
No shared memory buffer exists for this key and the IPC_CREAT was not given.

rcs_shm_nattch: shmctl failed: Invalid argument

cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occ
shmget(1003(0x3EB),8192,0) failed: (errno = 2): No such file or directory

* BufferLine: B emcError              SHMEM   localhost       8192    0       0       3       16 1003 TCP=5005 xdr queue
* ProcessLine: P tool          emcError        LOCAL   localhost       W       0       1.0     0       3
* error_type = 6 (NML_NO_MASTER_ERROR)
************************************************************

Jun 30 06:50:45 msgd:0: hal_lib:5296:user emcToolCmd buffer not available
Jun 30 06:50:45 msgd:0: hal_lib:5296:user toolSts buffer not available
Jun 30 06:50:45 msgd:0: hal_lib:5296:user emcError buffer not available
Jun 30 06:50:45 msgd:0: hal_lib:5296:user can't connect to NML buffers in /var/lib/buildslave/d7-64-bldtest/build/source/machinekit/configs/common/linuxcnc.nml
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_exit:258 HAL: removing component 73
Jun 30 06:50:45 msgd:0: hal_lib:5296:user hal_exit:258 HAL: removing component 72
Jun 30 06:50:45 msgd:0: hal_lib:5296:user ULAPI:0 git not installed at configure time exit
Jun 30 06:50:45 msgd:0: rtapi_app:5287:user pid=5287 flavor=posix gcc=4.7.2 git=git not installed at configure time
libnml/os_intf/_shm.c 209: shmget(1001(0x3E9),8192,0) failed: (errno = 2): No such file or directory
libnml/os_intf/_shm.c 228: No shared memory buffer exists for this key and the IPC_CREAT was not given.
libnml/os_intf/_shm.c 416: rcs_shm_nattch: shmctl failed: Invalid argument
libnml/cms/cms_cfg.cc 916: cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occured during SHMEM create.
libnml/nml/nml.cc 368: NML: cms_config returned -1.
```
and more besides

principally
```
cms_config: -4(CMS_NO_MASTER_ERROR: An error occured becouse the master was not started.) Error occ
shmget(1003(0x3EB),8192,0) failed: (errno = 2): No such file or directory
```

I will switch to a Wheezy partition and try from there.

**Comment by strahlex** [comment]
looks like the buildbot needs a reboot

**Comment by ArcEye** [comment]
Built OK on Wheezy, just done the interp tests for now as that was what failed, all good
```
Running test: tests/interp/abort-hot-comment
Running test: tests/interp/bad
Running test: tests/interp/cam-nisley
Running test: tests/interp/crazy-paths
Running test: tests/interp/do-while-break
Running test: tests/interp/exists
Running test: tests/interp/flowsnake
Running test: tests/interp/fractional-linenumbers
Running test: tests/interp/g10/g10-l1-l10
Running test: tests/interp/g10/g10-l1
Running test: tests/interp/g10/g10-l11
Running test: tests/interp/g10/g10-l2-while-active
Running test: tests/interp/g10/g10-l20-while-active
Running test: tests/interp/g10/g10-with-g92
Running test: tests/interp/g6164
Running test: tests/interp/g76
Running test: tests/interp/iniparam-failassign
Running test: tests/interp/iniparam
Running test: tests/interp/inside-corners
Running test: tests/interp/inverse-time-with-comp
Running test: tests/interp/m19
Running test: tests/interp/oword-bug315-p2
Running test: tests/interp/oword-bug315
Running test: tests/interp/oword-unwind
Running test: tests/interp/plug
Running test: tests/interp/pymove
Running test: tests/interp/python-self
Running test: tests/interp/return-value
Running test: tests/interp/sequence-number
Running test: tests/interp/subroutine-return
Running test: tests/interp/value-returned
Runtest: 31 tests run, 31 successful, 0 failed + 0 expected
```

I will run them all to be sure before I boot back to Jessie, but looks like it is a glitch
in the buildbot.

**Comment by ArcEye** [comment]
140 of 140 runtests passed on a wheezy build.
Must be the buildbot, as you say.

**Comment by mhaberler** [comment]
actually it looks like this kernel does not have SystemV IPC enabled

**Comment by strahlex** [comment]
@zultron It looks like the builbot needs a reboot

**Pull request merged**
