### PR TITLE
Revert "Remove hard kernel threads references"

### PR DESCRIPTION
**Pull request by ArcEye**
Reverts machinekit/machinekit#1409

This appears to be the cause of bizarre problems with i386 architecture only.
There is no quickly apparent culprit, since the merge largely deals with removing build artifacts which are unused anyway (rtai and hard xenomai kernels)

Remove the merge and then filter the commits through locally until the problem manifests itself.

### CODE REVIEW

**Comment by ArcEye** [comment]
@luminize 
When this completes test build, can you merge.
I have kept a local copy of the repo in case need arises.
Once packages are built I can run them in a VM and see if they appear OK again.

Then I will look at individual commits and try to find what on earth is going on :frowning_face:

**Comment by ArcEye** [comment]
Tested a set of locally reverted packages in a i386 VM and they work the same as earlier ones
Now building on amd64 and testing to make sure.
Yes that builds and runs a sim without problems.

I am going to press the button myself, it removes my commits in any case, then we will get a fully functioning repo and can do a post-mortem into 'why' at leisure

**Comment by luminize** [comment]
Sure, was a bit preoccupied, apologies.

**Comment by ArcEye** [comment]
No problem, just wanted to get it sorted whilst I had time.

**Pull request merged**
