### PR TITLE
Add "State Tags" to motion segments

### PR DESCRIPTION
**Pull request by robEllenberg**
From:
http://sourceforge.net/p/emc/mailman/emc-developers/thread/CAHK1zX_tbM1b0AO_we00XGrphoPZKHBF3iKm0OYvz2DMwJ04pQ%40mail.gmail.com/#msg33300348

I've been doing some work on making the "Active G-Codes" display match between the running program and what's displayed in the GUI. The idea is basically to pack the relevant parts of the interpreter's active state into a minimal size "tag", and stick this tag onto every motion command. This way, the status reported from motion contains all the active G codes as well. The tag itself is pretty small (~30 bytes), so it shouldn't introduce much overhead.

### CODE REVIEW

**Comment by zultron** [comment]
[Buildbot fails][1] on RTAI module build

[1]: http://buildbot.dovetail-automata.com/builders/d7-32-bld/builds/603/steps/chroot-make/logs/stdio

```
  gcc -Wp,-MD,/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/lib/.hal_lib.o.d  -nostdinc -isystem /usr/lib/gcc/i486-linux-gnu/4.7/include -I/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include -Iarch/x86/include/generated  -I/usr/src/linux-headers-3.8-1-common-rtai.x86/include -Iinclude -I/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.8-1-common-rtai.x86/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/kconfig.h   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -maccumulate-outgoing-args -Wa,-mtune=generic32 -ffreestanding -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -msse -mpreferred-stack-boundary=4 -funsafe-math-optimizations -D_IEEE_LIBM -D_ISOC99_SOURCE -D_SVID_SOURCE  -I/usr/src/linux-headers-3.8-1-common-rtai.x86/. -I.  -I/usr/src/linux-headers-3.8-1-common-rtai.x86/. -I.   -I/usr/include/rtai -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -ffast-math -mhard-float -Wno-undef   -I/usr/include -DTHREAD_FLAVOR_ID=4 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0 -DPB_FIELD_32BIT '-DPB_SYSTEM_HEADER=<'machinetalk'/include/pb-linuxcnc.h>' -D__MODULE__   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/linklist   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/cms   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/rcs   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/inifile   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/os_intf   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/nml   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/buffer   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/libnml/posemath   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/protobuf/nanopb   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/rtapi   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/hal/lib   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/nml_intf   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/kinematics   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/motion   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/tp   -I/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/machinetalk/nanopb -DSEQUENTIAL_SUPPORT -DHAL_SUPPORT -DDYNAMIC_PLCSIZE -DRT_SUPPORT -DOLD_TIMERS_MONOS_SUPPORT -DMODBUS_IO_MASTER -mieee-fp -msse -mpreferred-stack-boundary=4 -funsafe-math-optimizations -Wframe-larger-than=2560 -Wno-declaration-after-statement  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(hal_lib)"  -D"KBUILD_MODNAME=KBUILD_STR(hal_lib)" -c -o /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/lib/.tmp_hal_lib.o /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/hal/lib/hal_lib.c
make[2]: Leaving directory `/usr/src/linux-headers-3.8-1-rtai.x86-686-pae'
In file included from /usr/include/stdint.h:26:0,
                 from /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/motion/state_tag.h:19,
                 from /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/emc/motion/motion.h:88,
                 from /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/emc/kinematics/gantrykins.c:13:
/usr/include/features.h:323:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.
make[5]: *** [/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae/emc/kinematics/gantrykins.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [_module_/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src/objects/rtai-kernel/3.8-1-rtai.x86-686-pae] Error 2
make[3]: *** [sub-make] Error 2
make[2]: *** [all] Error 2
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src'
make: *** [modules] Error 2
make: Leaving directory `/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.943/src'
```

**Comment by robEllenberg** [comment]
I think the cause of RT build issues was trying to pull in the int16 type. I reverted that change and pulled in some fixes from the linuxcnc 2.7 flavor of this fix. Can we give this another shot on the buildbot?

**Comment by zultron** [comment]
@robEllenberg, the Buildbot automatically picked up the commits you pushed.  Pass!

Patch looks good, except a few extremely long lines.  If you fix those I'll merge, or if I'm the only one who gives a carp, another Maintainer can merge now.  ;)

**Comment by robEllenberg** [comment]
Sure, I'll wrap the long lines. I could do it via rebasing / force update
if you want a cleaner history.

-Rob

**Comment by robEllenberg** [comment]
I just did a rebase over the branch and tried to eliminate any really lone
lines from the commits. Is there anything else I should address?

-Rob

**Comment by zultron** [comment]
Looking good, thanks Rob.  Stand by for merge....

**Comment by strahlex** [comment]
After the patch I grt a missing symbol error for the rs274 lib:

    Traceback (most recent call last):
      File "/usr/bin/mkwrapper", line 19, in <module>
    import preview
    ImportError: /usr/lib/librs274.so.0: undefined symbol: _Z10UPDATE_TAG8StateTag

**Comment by strahlex** [comment]
When I import the rs274 module before the preview module I do not get this error.

**Comment by strahlex** [comment]
Found it, fixed it and created PR: https://github.com/machinekit/machinekit/pull/483

**Pull request merged**
