### PR TITLE
Cpusets

### PR DESCRIPTION
**Pull request by zultron**
This PR adds a new, optional argument to the HAL command `newthread [...] cgname=${RT_CGNAME}` that will cause the thread to run in the `cpuset` cgroup of the specified name.  Of course, the cgroup must be set up outside of Machinekit, e.g. with these commands

    RT_CGNAME=/rt  # cgroup path
    RT_CPUS=2,3   # CPUs in cgroup
    cgcreate -g cpuset:${RT_CGNAME}
    cgset -r cpuset.mems=0 ${RT_CGNAME}
    cgset -r cpuset.cpus=${RT_CPUS} ${RT_CGNAME}
    cgset -r cpuset.cpu_exclusive=1 ${RT_CGNAME}
    cgset -r cpuset.sched_load_balance=0 ${RT_CGNAME}

In combination with a kernel command line argument `isolcpus=${RT_CPUS}`, a HAL RT thread can run on its own, dedicated CPU.  On an Intel J1900 with CPUs 2 & 3 (which share L2 cache), `latency-test` results on `rt-preempt` threads went from max 40us to max 6us, an order of magnitude difference, and on `posix` threads from max 3000us to the same max 6us, three orders of magnitude.

This PR requires `libcgroup` packages not in current Docker images, so it won't pass tests until #1425 is merged and Jenkins is configured to point at new images.

### CODE REVIEW

**Comment by ArcEye** [comment]
Please leave this for now.
I will look later at why no PR builds are taking place
The last 7 github webhook attempts were unable to get through.

**Comment by ArcEye** [comment]
Build issue is resolved, hold until conditions met as per https://github.com/machinekit/machinekit/pull/1426#issue-236752394 above.

**Comment by zultron** [comment]
Woo hoo, the build now passes!  This PR is what triggered me to clean up the stale CI images (#1426) in the first place.

**Comment by luminize** [comment]
Congrats @zultron and thanks for the help @ArcEye !

**Comment by luminize** [comment]
@ArcEye declare ignorance on the build system. Anything preventing merging this PR?

**Comment by ArcEye** [comment]
No, I think now that the lib for cpusets are in the dockers,all is OK.
@zultron pushed to this yesterday which prompted a build which passed.
I missed that amongst the clutter of other emails

**Comment by luminize** [comment]
Great!

🎉

**Comment by ArcEye** [comment]
@zultron 
Could I ask that you do a short how-to doc on using cpusets ( the practical aspect ) to add to the documentation.

If we can get these kind of figures from rt-preempt, that potentially opens the way for software stepping, which will revolutionise the post rtai kernel machinekit capabilities.

I read your commit text and was instantly confused by the line
`In combination with a kernel command line argument isolcpus=${RT_CPUS}`
since that would require a system variable to be set up prior to even kernel boot.

I assume you just meant `isolcpus=2,3` , which is what you put in `RT_CPUS` later?

**Comment by zultron** [comment]
I'm happy to write a doc, I assume to add to the machinekit.github.io repo.

I see at least the [`halcmd`][1] man page where the new `newthread cgname=/rt` option should be added.  However, the description of the related `cpu=N` is barely adequate to do more than note the option's existence.  A mk.io site search for `"newthread"` or `"threads" "cpu"` or `multicore` doesn't turn up any obvious in-depth discussion on threads or CPUs.

Can you suggest a location to write something with a little more detail, whether a new or existing page?

[1]: http://www.machinekit.io/docs/man/man1/halcmd/

**Comment by ArcEye** [comment]
If you let me have sight of a doc when done, we can try to work out how best to insert it and link to it ,
to get the info in place and searchable with the minimum effort.

**Pull request merged**
