### PR TITLE
Implement G52 offsets

### PR DESCRIPTION
**Pull request by zultron**
This implementation of `G52` is intended to be compatible with Fanuc,
including sharing offset registers with `G92`.

LinuxCNC rs274ngc persists `G92` offsets across machine startup, M02
and M30, but Fanuc does not.  Because users familiar with Fanuc may
expect the offset to be volatile, and be surprised (perhaps badly)
when the offset persists, this patch disables `G92` offset persistence
by default, but adds a `.ini` file option to enable it for users of
LinuxCNC who desire it.

Other implementation details:

- `G52` shares registers with `G92`, `#5210` (flag) and `#5211`
  through `#5219` (9 axis offsets)
- `G52` offsets are applied in the same way as `G92`, after workpiece
  coordinate offsets and rotation.
- `G52` and `G92`/`G92.n` may be freely mixed, and in the light of the
  shared registers, interactions behave as expected.
  - `G52 X0 Y0` zeros the offsets, but does not reset the `#5210`
    flag.  This is not expected to cause unexpected behavior; the flag
    apparently exists only to implement `G92.2` and `G92.3`.
  - `G52` and `G92` share DRO readouts and preview offset display.
- `G92` offset persistence may be enabled by setting
  `PERSISTENT_G92_OFFSET = true` in the `[RS274NGC]` section of the
  `.ini` file.  By default, `G92` is volatile.

### CODE REVIEW

**Comment by luminize** [comment]
I can merge but I cannot technically review this. Since the buildbot builds I have no problems merging.
Can you document these changes (as well as #777 ) in machinekit/machinekit-docs?

**Comment by luminize** [comment]
any chance of documenting these changes in the docs? Or make an issue at machinekit-docs for that, cross referencing to here?

**Comment by zultron** [comment]
Hi @luminize, thanks for the merge!

Yes, I already have documentation.  When my head's out of the water on this Buildbot business, I'll post a PR.

**Comment by luminize** [comment]
Just an issue on machinekit-docs cross linking is enough for the time being.
Thx
Bas

**Pull request merged**
