### PR TITLE
docs: removed docs directory and passes relevant buildbot tests.

### PR DESCRIPTION
**Pull request by luminize**
previous PR #421 doesn't get there. Second go.

### CODE REVIEW

**Comment by luminize** [comment]
@zultron @mhaberler 
I notified [the forum about the splitting of docs](https://groups.google.com/forum/#!topic/machinekit/7CXpiVPioOo) and nobody responded, so from my point of view, unless one of you both have any objections then please merge and we can close #100

**Comment by zultron** [comment]
I'm good with merging, but would like to synch with disabling the Buildbot's doc builder.  Can we delay until Monday when I can concentrate on that (and any potential fallout)?

Also, Monday might be a big Buildbot update festival, since my OBS-built x86-arch MK deps are nearly done, and the builders need to be pointed to those and RCN's ARM pkg archive.

**Comment by luminize** [comment]
As Michael would say: Wunderbar!
no problems from my side. Syncing with buildbot work sounds very logical.

Could I help you with making a PR specifically to the new buildbot?

**Comment by zultron** [comment]
@luminize, looking at your PR.  The Buildbot is already updated to stop building docs, btw, and this PR builds all green now.

I'm wondering about the `man/man-generated` directory. I guess the intent is to have searchable manpages online in the main machinekit repo?

I'm pretty wary of checking generated sources into git for a number of reasons.

My understanding from our phone call was we'd have a third repo called 'machinekit-man' that would have these docs.  Did I get that wrong?

**Comment by zultron** [comment]
Most everything else looks peachy.  Very thorough & conscientious job, thanks!

Small problem:
- In `rip-environment.in`, `MANPATH` needs updating

A couple more nits that I won't hold you to:
- All refs to `docs` can be removed from debian/configure.  Nobody uses this except me and @kinsamanka, AFAIK, so the cruft can go.
- I'm sure that `/directory.map` is pathetically out of date, but the `/docs` tree could be removed
- Can `/src/doxconfig` simply be removed?

**Comment by luminize** [comment]
> On 12 Jan 2015, at 17:29, John Morris <notifications@github.com> wrote:
> 
> @luminize, looking at your PR. The Buildbot is already updated to stop building docs, btw, and this PR builds all green now.
> 
> I'm wondering about the man/man-generated directory. I guess the intent is to have searchable manpages online in the main machinekit repo?
> 
> I'm pretty wary of checking generated sources into git for a number of reasons.
> 
> My understanding from our phone call was we'd have a third repo called 'machinekit-man' that would have these docs. Did I get that wrong?
> 
No you're correct

I haven't gotten to making machinekit-man and this slipped my mind. We can exclude the `*.asciidoc` in `man/man-generated` from git, and I'll generate them and push to machinekit-man manually.

I'll remove them and adjust the `.gitignore' and make a commit before the merge.

Then we can take our time figuring out how to build and push them automatically.

For anybody who builds themselves they will be generated and available.

**Comment by luminize** [comment]
> On 12 Jan 2015, at 18:17, John Morris <notifications@github.com> wrote:
> 
> Most everything else looks peachy. Very thorough & conscientious job, thanks!
> 
> Small problem:
> 
> In rip-environment.in, MANPATH needs updating
> A couple more nits that I won't hold you to:
> 
> All refs to docs can be removed from debian/configure. Nobody uses this except me and @kinsamanka, AFAIK, so the cruft can go.
> I'm sure that /directory.map is pathetically out of date, but the /docs tree could be removed
> Can /src/doxconfig simply be removed?
I'll have a look, will make a commit and see if it builds correctly=

**Comment by zultron** [comment]
Perfect!  I'll be happy to make `machinekit-man` updates a Buildbot job when we're ready for it.

**Comment by luminize** [comment]
@zultron 
buildbot won't start, probably because the `d` in the configure arguments, see commit https://github.com/luminize/machinekit/commit/10ee459fd3879ea0a6308c3ed4ef03d5970926c1
```
+ /var/lib/buildslave/ant/build/source/debian/configure -prxdt 8.5
```

**Pull request merged**
