### PR TITLE
machinetalk-protobuf: add rapidrate

### PR DESCRIPTION
**Pull request by machinekoder**
Adds fields which are missing since the multi-core merge.

### CODE REVIEW

**Comment by machinekoder** [comment]
https://github.com/machinekit/machinekit/issues/1123

**Comment by ArcEye** [comment]
This commit was in the master that multicore was merged into, but must have clobbered those fields.
Well spotted

**Comment by bschousek** [comment]
This commit does not seem to be in the latest package. Here is a snip of program output showing a thrown error, followed by an apt dump showing the installed version.

Error message:
```
sending interp message
Exception in thread process_sockets:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/mkwrapper", line 605, in process_sockets
    self.update_status(self.stat)
  File "/usr/bin/mkwrapper", line 1422, in update_status
    self.update_motion(stat)
  File "/usr/bin/mkwrapper", line 1271, in update_motion
    self.status.motion.rapidrate = 0.0
AttributeError: 'EmcStatusMotion' object has no attribute 'rapidrate'

```

apt output
```
apt-cache policy machinekit
machinekit:
  Installed: 0.1.1495389287-1mk.travis.master.git466cbe1f~1jessie
  Candidate: 0.1.1495389287-1mk.travis.master.git466cbe1f~1jessie
  Version table:
 *** 0.1.1495389287-1mk.travis.master.git466cbe1f~1jessie 0
        500 http://deb.machinekit.io/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by bschousek** [comment]
It turns out that I had two copies of status_pb2.py, one in /usr/lib and one in /usr/local/lib. One has rapidrate, the other does not, and obviously the one without must be earlier in the search path. I don't know how I ended up with two copies, but some early fumbling with the Vagrant install is certainly to blame.

**Pull request merged**
