### PR TITLE
Reversal of machinekit-dev repackaging test

### PR DESCRIPTION
**Pull request by ArcEye**
Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
This PR build failed because the wheezy run tests did not finish.
The jessie run tests had already passed.

I think this is just a bizarre glitch in the build system, possibly linked to my updating the PR in mid build, when I realised I had omitted a file.

I will close and re-open the PR to force a rebuild and hopefully that will pass.

**Comment by ArcEye** [comment]
I don't know what to make of this.
It is not failing per se, it is running out of time and log space on the wheezy runtests.

The log exceeds 4MB, has 28 warnings of async_syslog overflow, with log entries lost
There are only 9 in the jessie runtests log

There are 54 warnings of being unable to set FIFO policy when trying to set thread affinity on a posix kernel
There are only 26 in the jessie runtests log.
This tends to indicate it is duplicating tests for some reason

We have had problems with the runtests before and this commit only reverts the debian files back to their original state and should have no effect on runtests.

The other option is to try reverting the original merge, but I am reluctant to try that, as it is rather messy and should not be required at all.

Thoughts?

**Comment by cdsteinkuehler** [comment]
On 10/2/2016 4:46 AM, ArcEye wrote:
> 
> The other option is to try reverting the original merge, but I am reluctant to 
> try that, as it is rather messy and should not be required at all.
> 
> Thoughts?

I'm not sure what to make of this either, but I'm not against a
force-push to eliminate the test merge and get back to where we were.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
The only other merge is your change of pager in mank, if that is lost it can be resubmitted easily.

If this was my own repo, I would just do a `git reset --hard <SHA> to take it back before the test merge and then put in a new PR for your pager change.

I don't know if that can be done directly through github, or if you have to push a PR that effectively does it,
but either way I think we have to square up the repo soonest, before too many people 'upgrade' to the test packages.

**Comment by cdsteinkuehler** [comment]
On 10/2/2016 11:16 AM, ArcEye wrote:
> The only other merge is your change of pager in mank, if that is lost it can be 
> resubmitted easily.
> 
> If this was my own repo, I would just do a `git reset --hard to take it back 
> before the test merge and then put in a new PR for your pager change.
> 
> I don't know if that can be done directly through github, or if you have to push 
> a PR that effectively does it,
> but either way I think we have to square up the repo soonest, before too many 
> people 'upgrade' to the test packages.

Just reset your local repo back to how it was (using git reset
--hard), then do a direct push (with --force) to the MK repo, not a PR.

This will technically violate C4 and whatnot, but I think there's
enough discussion about what was being tested here in the issue that
it's not worth muddying the git history with various "unwind" commits,
and if the reset _still_ doesn't work, we'll know something is broken
with the build infrastructure.  And we've got input from several
developers, so it's not really a personal push to the repo which is
what the PR was intended to avoid (making sure at least two people had
"eyes-on" and responsibility for any commit).

If the git gymnastics make you nervous, I can do it, but I'll be in
and out today so it might not be until late.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
Hard reset done 0920 03102016
PR #1069 submitted to reinstate @cdsteinkuehler 's commit which was lost in that process and as a PR build test

**Comment by ArcEye** [comment]
Hurrah, forced reset worked, Charles's commit reinstated, all is hunky dory again

**Pull request closed without merging**
