### PR TITLE
Add Decamux Support

### PR DESCRIPTION
**Pull request by cdsteinkuehler**
This PR needs code review and a build test, but should combine both Bas' original changes, the updates made by gjsmo along with some tweaks by me to setup for building two PRU binary files.

Intended to supersede PR # 578, if all looks good.

### CODE REVIEW

**Comment by cdsteinkuehler** [comment]
Looks like something is wrong with the build, but I'm not sure what.  Nothing that changed should have altered the x86 builds, and the ARM builds succeeded.  Any ideas?

**Comment by mhaberler** [comment]
looking into it now

**Comment by mhaberler** [comment]
unsure what is wrong, see #578 - I think it is ok to go ahead with a merge

**Comment by cdsteinkuehler** [comment]
So does someone want to merge this and kill #578?  Any idea why the x86 tests are suddenly failing on the BuildBot?

**Comment by mhaberler** [comment]
I looked as well and didnt see any relevant log entries

**Comment by gjsmo** [comment]
I managed to test this on my setup and it does work. There is one change missing: since the PRU binary has changed, line 5 of the .ini needs to change from "PRUBIN=xenomai/pru_generic.bin" to "PRUBIN=xenomai/pru_decamux.bin". This does seem like a better solution than creating one universal binary though.

**Comment by mhaberler** [comment]
want to post a PR?

**Pull request merged**
