### PR TITLE
Deprecate send container string dest

### PR DESCRIPTION
**Pull request by machinekoder**
Continuation of https://github.com/machinekit/machinekit/pull/969

@ArcEye Can you please take a look at this patch.

I still need verify if the FAST road also works.

### CODE REVIEW

**Comment by machinekoder** [comment]
I enabled the fast track. The zmsg_send command also deletes the complete message and makes any additional deletes invalid. I have only encountered the zmsg_destroy in haltalk so far.

**Comment by zhivko** [comment]
I tried to build ```machinekit:master``` and I get this when mk starts:

```
NML_INTERP_LIST::append(nml_msg_ptr{size=160,type=EMC_TRAJ_SET_G92}) : list_size=4, line_number=0
NML_INTERP_LIST::append(nml_msg_ptr{size=96,type=EMC_TRAJ_SET_ROTATION}) : list_size=5, line_number=0
emcTaskPlanInit() returned 0
Issuing EMC_TASK_PLAN_SYNCH --   (+516,+24,    +0,)
emcTaskPlanSynch() returned 0
Issuing EMC_TRAJ_SET_TERM_COND --        (+222,+104,    +0,    +2,0.000000,)
Issuing EMC_TRAJ_SET_G5X --      (+224,+168,    +0,    +1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,)
Issuing EMC_TRAJ_SET_G92 --      (+227,+160,    +0,0.000000,-40.000000,-40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,)
Issuing EMC_TRAJ_SET_ROTATION --         (+226,+96,    +0,0.000000,)
announcing mkwrapper
service: dsname = ftp://%(fqdn)s:38169 port = 38169 txtrec = ['dsn=ftp://%(fqdn)s:38169', 'uuid=a42c8c6b-4025-4f83-ba28-dad21114744a', 'instance=48ec90a8-1ea3-11e7-ae0f-080027165e4c', 'service=file'] name = File service on %(fqdn)s pid 28255
/usr/lib/python2.7/dist-packages/pyftpdlib/authorizers.py:262: RuntimeWarning: write permissions assigned to anonymous user.
  RuntimeWarning)
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/machinekit/git/machinekitOff/bin/mkwrapper", line 298, in run
    import preview  # must be imported in new process to work properly
ImportError: /usr/lib/python2.7/dist-packages/preview.x86_64-linux-gnu.so: undefined symbol: _Z16send_pbcontainerRKSsRN11machinetalk9ContainerEPv
```

**Comment by ArcEye** [comment]
@machinekoder 
I imagine this means you did not find all the instances of `send_pbcontainer` which still use the old
args (std::string &dest, ...............)
```ImportError: /usr/lib/python2.7/dist-packages/preview.x86_64-linux-gnu.so: undefined symbol: _Z16send_pbcontainerRKSsRN11machinetalk9ContainerEPv```

I have nothing to test this with.

**Comment by ArcEye** [comment]
Either that or @zhivko is calling it directly from a custom script ?

**Comment by zhivko** [comment]
just ordinary machinekit start for my sim config that worked 2 week back.

**Comment by zhivko** [comment]
It starts mkwrapper from hal file.
Ini is here:

https://github.com/zhivko/machinekit/blob/master/myini/sim/CRAMPS.ini

**Comment by ArcEye** [comment]
I am reverting until @machinekoder has time to fully test and correct as necessary.
With holidays, the meeting coming up etc. that could be a while

**Pull request merged**
