### PR TITLE
gmoccapy update to latest version

### PR DESCRIPTION
**Pull request by gmoccapy**
Updated all to the latest stable version, see release notes for details

### CODE REVIEW

**Comment by luminize** [comment]
Hi @gmoccapy I noticed that while merging the /docs directory which we took out of the tree sneaked back in. Gan we find a way of only merging the gmoccapy changes?

**Comment by gmoccapy** [comment]
Hallo Bas,

I made small mistakes merging my changes, as I was not informes, that 
2.6 to 2.7 in linuxcnc does handle the docs in a different way.
I will be pleased to send you the new file, or I could also fork the 
docs repo and make the changes there and create a pull request.

But as all of us, I am running short of time ;-)

Norbert

Am 29.11.2015 um 14:12 schrieb Bas de Bruijn:

**Comment by gmoccapy** [comment]
Hallo Bas,

I just pushed the most recent version of gmoccapy.txt to linuxcnc git repo.
Could you grep it from there?

Norbert

Am 29.11.2015 um 14:12 schrieb Bas de Bruijn:

**Comment by gmoccapy** [comment]
Bas, you will need to pick also all the images from /docs/src/gui/images, beginning with gmoccapy in its names.

Norbert

**Comment by luminize** [comment]
> Hallo Bas,
> 
> I just pushed the most recent version of gmoccapy.txt to linuxcnc git repo.
> Could you grep it from there?

Could you add a link where I can have a look? Maybe cherry picking commits works.

**Comment by gmoccapy** [comment]
Am 30.11.2015 um 14:01 schrieb Bas de Bruijn:
>
> > Hallo Bas,
> >
> > I just pushed the most recent version of gmoccapy.txt to linuxcnc 
> git repo.
> > Could you grep it from there?
>
> Could you add a link where I can have a look? Maybe cherry picking 
> commits works.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/machinekit/machinekit/pull/803#issuecomment-160621785>.
>
Hallo Bas,

Please find attached the complete doku including images and java script 
for the table of content.

Norbert

**Comment by gmoccapy** [comment]
Oh, I think attachments are not allowed ;-)

Please get it from my server:

http://bilder.schechner.info/gmoccapy/gmoccapy_docs.tar.bz2

Norbert

Am 30.11.2015 um 14:01 schrieb Bas de Bruijn:

**Comment by luminize** [comment]
Hi Norbert,

To be honest, I'm a bit lost now. Sorry about that. If I get it right then:
- this last commit in the PR https://github.com/gmoccapy/machinekit/commit/f06776c92bd96bdeea6b46e094c48ed3298fac43 is the actual gmoccapy update. which is about 2 files in share/gmoccapy/ and 5 files in /src/emc/user_intf/gmoccapy/
- the first commit in this PR https://github.com/gmoccapy/machinekit/commit/38a4a96e370c2aaaa9f6c777bfe777c0315c98c1 (labelled signed off by: you) are the re-introduction of docs directory we removed. In fact, this is mostly /docs/man
- the 3 commits in-between (where you merge the master branch), what do they do? If I read your commits they are merges of configurations.

if you could pull the latest machinekit:master, checkout a new branch and cherry-pick your commit f06776c92bd96bdeea6b46e094c48ed3298fac43 ? then I think we're where we need to be.

Sorry if I'm making wrong assumptions.
Bas

**Comment by gmoccapy** [comment]
Hallo Bas,

sorry for the late answer, I had to fix an Isue in linuxcnc gladevcp.
I will close this pull request, kill my repo, fork the repo again to have a clean copy and then include the newest stuff to create a new pull request.

Norbert

**Comment by luminize** [comment]
Hi Norbert,
Thanks a lot!

**Pull request closed without merging**
