### PR TITLE
hal_bb_gpio:  Fix input pins for PocketBeagle

### PR DESCRIPTION
**Pull request by zultron**
This is a bug fix.  Can it go into the main MK repo?  Thanks!

----

Thanks to @mlampert for identifying and reporting this, and @cdsteinkuehler for pointing out where to fix.

https://groups.google.com/forum/#!topic/machinekit/_RJ63TNH39k

https://github.com/machinekit/machinekit/issues/1481

### CODE REVIEW

**Comment by zultron** [comment]
This is totally untested, but hopefully it's simple enough that even I couldn't screw it up.

@mlampert  I'd appreciate it if you can test this, whether before or after a merge.

**Comment by luminize** [comment]
@zultron i’ll merge asap, if after the test it solved the case, can you make a PR to machinekit-... too (i guess it’s hal)?

**Comment by ArcEye** [comment]
The only issue I can see if whether **ALL** variations of the BBx, return board-id as being `BEAGLEBONE`.
If not, the logic could simply be reversed and the pin number NOT incremented for PocketBeagle board_id.

I don't have any, so can't help there I'm afraid.

**Comment by zultron** [comment]
Thanks for the reminder, @luminize ; see PR machinekit/machinekit-hal#208

@ArcEye :
> The only issue I can see if whether **ALL** variations of the BBx, return board-id as being `BEAGLEBONE`.

Yes.  The [logic][1] (actually added in #1296, not here) is really dumb with no automatic detection.  If a `loadrt hal_bb_gpio board=` parameter is given, it tries to set `board_id` based on that; otherwise, it defaults to `BEAGLEBONE`.  I did it that way because automatic board detection is hard (and usually unnecessary, and easier in a python HAL config anyway), and because it wouldn't break existing configs.  I'm guessing that particular part of the patch didn't break anyone or we'd have heard about it by now.  (In #1302 we did hear about things I broke with other bits of #1296.  :P ).

[1]: https://github.com/zultron/machinekit/blob/4240ec43/src/hal/drivers/hal_bb_gpio/hal_bb_gpio.c#L191-L203

**Pull request merged**
