### PR TITLE
Add toggle function for Mist/Flood/Lube

### PR DESCRIPTION
**Pull request by alkabal**
Add toggle function for Mist/Flood/Lube

Mist attached to macro16
Flood attached to macro15
Lube attached to macro2

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by ArcEye** [comment]
ok to test

**Comment by alkabal** [comment]
Also i have swapp display selection Absolue/relative to hardcoded safe-z button in place of macro5 and macro7.

Firstly i does not want to merge this part at same time, this is a mistake sorry...

**Comment by alkabal** [comment]
https://github.com/alkabal/machinekit/pull/1

**Comment by ArcEye** [comment]
If you want to remove the code which implements any of these elements, you will need to submit another PR.
So long as it works and the use is documented, I don't mind which way it is implemented, either in a binary or in the hal configuration.

**Pull request merged**
