### PR TITLE
More cross-build preparations for #1072

### PR DESCRIPTION
**Pull request by zultron**
Here's a stack of new commits to enable cross-building against a `--sysroot`.

See #1072 for background; the [`mk-builder-3` repo][1] for documentation; and the [Travis CI build results][2] (including regression tests) for inspiration.

[1]: https://github.com/zultron/mk-builder-3
[2]: https://travis-ci.org/Dovetail-Automata/emc2

### CODE REVIEW

**Comment by zultron** [comment]
Wheezy failures again.  I'll fix them tomorrow.

**Comment by zultron** [comment]
Thanks @ArcEye

**Comment by ArcEye** [comment]
@zultron 
Am I right in thinking that MK master will now cross-build using your docker image?
The commits seem to match https://github.com/zultron/machinekit/commits/mk-1072-xbuild-prep now.

**Comment by ArcEye** [comment]
> @zultron
Am I right in thinking that MK master will now cross-build using your docker image?
The commits seem to match https://github.com/zultron/machinekit/commits/mk-1072-xbuild-prep now.

Answered my own question, still configure.ac / Makefile / .travis changes not merged

**Pull request merged**
