### PR TITLE
Silence compile warnings

### PR DESCRIPTION
**Pull request by zultron**
This branch silences compile warnings, which are getting really out of hand with gcc-4.8.  A fringe benefit is we'll start to notice some of the bugs creeping in with new warnings.

### CODE REVIEW

**Comment by mhaberler** [comment]
what's the status of this PR?

if still relevant, I guess I should go through them?

**Comment by zultron** [comment]
@luminize [pointed out][1] where the merge conflicts are probably coming from.  Thanks!

[1]:  https://github.com/machinekit/machinekit/issues/236#issuecomment-69783582

**Comment by zultron** [comment]
After a review by @mhaberler, I'm trying to figure out how to handle two issues he raised.

One is commit c3e4744, 'machinetalk/lib/mk_backtrace.c: fix `syminfo_callback` declaration', where the prototype for `backtrace_syminfo_callback` [has been changed][1] ([rev. 2052028][2]) in versions of gcc newer than those in Wheezy and Trusty.  Spelunking in gcc CVS, it looks like it's released in gcc 4.9.0.

[1]:  https://gcc.gnu.org/ml/gcc-patches/2013-11/msg02095.html
[2]:  https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=205028

My impulse is to go with the gcc 4.8 prototype short-term, and long-term figure out a way to detect this in autoconf.  How does this sound to others?

**Comment by mhaberler** [comment]
sounds just fine!

**Comment by mhaberler** [comment]
should I merge this now?

**Comment by zultron** [comment]
Great, I'll use the `backtrace_syminfo_callback` signature from before gcc 4.9.0, and file a separate issue about the problem.

Still one more unresolved question about `strstore()`.  I'll update this after a little more thought.

**Comment by zultron** [comment]
About `strstore()`:  @mhaberler expressed concern about the second copy added to `python_plugin.cc`:  the `stringtable` storage set is intended to be a singleton shared by all using code.

This function could be moved into `libnml/inifile/inifile.cc`, since it's always used in the context of reading strings from `.ini` files or storing strings computed from `.ini` file strings.

**Comment by zultron** [comment]
The `strstore()` quiestion is addressed in 7e6b168.

Added one more commit to silence `dpkg-gencontrol` warnings.

Buildbot passes, and with no warnings!  Ready for merge.

**Comment by zultron** [comment]
Actually, I'm sneaking one more thing in so that #326 can be closed, too.

**Comment by mhaberler** [comment]
is there anything forthcoming or should we close this?

**Comment by zultron** [comment]
Whoa, never merged, ok let's close.

**Pull request closed without merging**
