### PR TITLE
Improved gcode-to-ngc, added g1-to-g23 as script

### PR DESCRIPTION
**Pull request by strahlex**
Improved the gcode-to-ngc script and adds the g1-to-g23 script by Frank Tkalcevic

### CODE REVIEW

**Comment by luminize** [comment]
I added the script in Machinekit some months ago for use with the velocity extruding. Wouldn't it be better to `git mv` move the script from the current place to the scripts location?

**Comment by strahlex** [comment]
@luminize It makes sense to remove the second script. I also changed a few things (the output was unnecessary big, stdin and stdout,...) Maybe it is necessary to change a few things in the velocity extruding conversion script

**Comment by strahlex** [comment]
Fixed it, now I moved the file and applied the changes. However, somehow git was not able to figure out what I changed

**Comment by luminize** [comment]
I remember having a little disagreement with the script a some point. Might be that the scripts ended up being the same?
Anyway, I think 2 scripts with the same in different locations are a source for confusion. I do not have any claim over it so if you prefer you could just remove it out of the config directory (or if you want I can do it myself later in the evening) and put the version with your mods in scripts/ (sorry if I got you into extra work)

**Comment by strahlex** [comment]
@luminize I have already done that (--force push) git now knows that the script has been moved.

**Comment by strahlex** [comment]
Turned out that the g1-to-g23 script optimzed some moves without extrusion and retract/unretract moves. This resulted in a wrong output. Furthermore the scripts did not preserve comments useful for debugging. Fixed this issues with the last commit.

**Comment by luminize** [comment]
I can't see the results of this build anymore. Did it pass? if you don't know then we need to trigger the buildbot again (I'm hesitant to merge, because i don't want to break things).

**Comment by zultron** [comment]
Irritating, huh?  You can get a wider 'grid' view by adding the `width` parameter to the URL, e.g.:

http://buildbot.dovetail-automata.com/grid?width=30

It passed.

**Comment by luminize** [comment]
@zultron thx! Good tip

**Pull request merged**
