### PR TITLE
TEST: buildbot results with removed docs directory

### PR DESCRIPTION
**Pull request by luminize**
For the purpose of seeing the buildbot results this branch is the same as PR #400 but with the removed docs directory which will soon live in its own machinekit/machinekit-docs repository.

### CODE REVIEW

**Comment by zultron** [comment]
Sheesh, who'ld'a thunk, the unit tests depend on a file in `/docs`.
```
+ cp ../../docs/src/hal/rand.comp .
cp: cannot stat `../../docs/src/hal/rand.comp': No such file or directory
```

**Comment by zultron** [comment]
I'd simply copy `docs/src/hal/rand.comp` to `tests/usercomp.0`, remove line 2 from `tests/usercomp.0/test.sh`, and be done with it.

**Comment by luminize** [comment]
Was interrupted by a phone call before i pushed. Also found the culprit :)
I moved it to src/hal/components/ and changed the path in test.sh

how should we go about not being able to build the docs? that one will fail always from now :)

**Comment by luminize** [comment]
I've been weeding the forrest of makefile and debian references to docs locations, next will be the last try for packages to build this : https://github.com/luminize/machinekit/commit/a92b7935ed73df86945c914f546c5ac54971b1b7
if after this it won't build then I need @zultron help because I probably won't find the solution.

**Comment by zultron** [comment]
If `rand.comp` was moved to `src/hal/components`, does that mean that it will now be distributed in packages in the same way as other comps?

Let me know if you need help with the packaging.  Looks like you're doing great!

**Comment by zultron** [comment]
Oh, and I'll remove the docs builder from the Buildbot when the time comes.  Trivial change.

**Comment by luminize** [comment]
On 09 Jan 2015, at 06:27, John Morris <notifications@github.com> wrote:

> If rand.comp was moved to src/hal/components, does that mean that it will now be distributed in packages in the same way as other comps?
> 
i moved it to the tests directory like you proposed, I got so a lot of errors when it was in src/hal/components
> Let me know if you need help with the packaging. Looks like you're doing great!
> 
a second set of eyes is useful, so if you’d look over the pruning i’m doing (just removing everything that throws an error) that would be helpfull.
I’m getting a lot of packages that fail building

**Comment by luminize** [comment]
I think I'm on the wrong track somehow.
the build before the removal of the docs went OK, but no matter what I remove, the errors keep continuing,

latest error:
```
../nc_files/toplevel.ngc ../nc_files/tort.ngc ../nc_files/torus.png ../nc_files/touchoff.ngc ../nc_files/useful-subroutines.ngc ../nc_files/x-trim.ngc /var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.831/src/../debian/tmp/usr/share/linuxcnc/ncfiles
cp: target `/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.831/src/../debian/tmp/usr/share/linuxcnc/ncfiles' is not a directory
make[1]: *** [install-kernel-indep] Error 1
make[1]: Leaving directory `/var/lib/buildslave/d7-32-bldtest/build/source/machinekit-0.1.831/src'
make: *** [install] Error 2
```

**Comment by luminize** [comment]
moving to #422

**Pull request closed without merging**
